package game;

import map.Territory;

/**
 * Handles attack logic in Battle Nations.
 *
 * <p>This service is responsible for resolving combat between two territories.
 * It validates that an attack is allowed, calculates attack and defense strength,
 * determines the outcome probabilistically, and updates troop counts and ownership
 * accordingly.</p>
 *
 * <p>The outcome of a battle is based on the relative strengths of the attacking
 * and defending territories, incorporating terrain bonuses.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public class AttackService {

    /**
     * Constructs an AttackService.
     */
    public AttackService() {
    }

    /**
     * Executes an attack between two territories.
     *
     * <p>If the attack is valid, the outcome is determined probabilistically
     * based on the attacking and defending strengths. The attacker retreats
     * once they have lost half their initial troops. Troop counts and ownership
     * are updated based on the result.</p>
     *
     * @param territoryAttacking the territory initiating the attack
     * @param territoryDefending the territory being attacked
     * @return the result of the attack attempt
     */
    public ValidationResult attack(Territory territoryAttacking, Territory territoryDefending) {
        ValidationResult validationResult = validateAttack(territoryAttacking, territoryDefending);

        // Stop if the attack is invalid
        if (!validationResult.isValid()) {
            return validationResult;
        }

        double attackStrength;
        double defenseStrength;
        double attackingPlayerKillingOdds;
        double generatedKillingOdds;
        int attackersLost = 0;
        int initialAttackers = territoryAttacking.getTroopAmount();

        // Attacker fights until they have 1 troop left or have lost half their starting troops
        while (territoryAttacking.getTroopAmount() > 1 && initialAttackers / 2 > attackersLost) {
            attackStrength = calculateEffectiveAttackStrength(territoryAttacking);
            defenseStrength = calculateEffectiveDefenseStrength(territoryDefending);

            // Probability of attacker winning this round based on relative strengths
            attackingPlayerKillingOdds = attackStrength / (attackStrength + defenseStrength);

            // Random value between 0 and 1 to determine this round's outcome
            generatedKillingOdds = Math.random();

            if (attackingPlayerKillingOdds >= generatedKillingOdds) {
                territoryDefending.setTroopAmount(territoryDefending.getTroopAmount() - 1);

                // Defender has been wiped out — transfer ownership to attacker
                if (territoryDefending.getTroopAmount() <= 0) {
                    territoryDefending.setPlayer(territoryAttacking.getPlayer());
                    territoryDefending.setTroopAmount(territoryAttacking.getTroopAmount() - 1);
                    territoryAttacking.setTroopAmount(1);
                    return new ValidationResult(true, "Attacker Wins");
                }
            } else {
                territoryAttacking.setTroopAmount(territoryAttacking.getTroopAmount() - 1);
                attackersLost++;
            }
        }

        // Attacker retreated after hitting their loss limit
        return new ValidationResult(true, "Attacker Lost");
    }

    /**
     * Calculates the effective attack strength of a territory.
     *
     * <p>Strength is the territory's troop count scaled by its terrain attack bonus.</p>
     *
     * @param territory the attacking territory
     * @return the calculated attack strength
     */
    private double calculateEffectiveAttackStrength(Territory territory) {
        return territory.getTroopAmount() * (1 + territory.getTerrain().getAttackBonus());
    }

    /**
     * Calculates the effective defense strength of a territory.
     *
     * <p>Strength is the territory's troop count scaled by its terrain defense bonus.</p>
     *
     * @param territory the defending territory
     * @return the calculated defense strength
     */
    private double calculateEffectiveDefenseStrength(Territory territory) {
        return territory.getTroopAmount() * (1 + territory.getTerrain().getDefenseBonus());
    }

    /**
     * Validates whether an attack is allowed.
     *
     * <p>An attack is valid only if both territories are non-null, both have
     * assigned players, the territories are owned by different players,
     * the attacking territory has at least two troops, and the territories
     * are neighbors.</p>
     *
     * @param attackingTerritory the attacking territory
     * @param defendingTerritory the defending territory
     * @return the result of validating the attack
     */
    private ValidationResult validateAttack(Territory attackingTerritory, Territory defendingTerritory) {
        if (attackingTerritory == null || defendingTerritory == null) {
            return new ValidationResult(false, "Territories cannot be null");
        } else if (attackingTerritory.getPlayer() == null || defendingTerritory.getPlayer() == null) {
            return new ValidationResult(false, "Both territories must have a player set");
        } else if (attackingTerritory.getPlayer().equals(defendingTerritory.getPlayer())) {
            return new ValidationResult(false, "Both territories cannot be controlled by the same player");
        } else if (attackingTerritory.getTroopAmount() <= 1) {
            // Must have at least 2 troops to attack (1 must remain behind)
            return new ValidationResult(false, "Attacking territory must have at least 2 troops");
        } else if (!areTerritoriesNeighbors(attackingTerritory, defendingTerritory)) {
            return new ValidationResult(false, "Territories must be neighboring, or touching a valid water route");
        }

        return new ValidationResult(true, "Valid Attack");
    }

    /**
     * Checks whether two territories are neighbors.
     *
     * @param attackingTerritory the attacking territory
     * @param defendingTerritory the defending territory
     * @return true if the territories are neighbors, false otherwise
     */
    private boolean areTerritoriesNeighbors(Territory attackingTerritory, Territory defendingTerritory) {
        return (attackingTerritory.hasNeighbor(defendingTerritory));
    }
}