package game;

import map.Territory;

/**
 * Handles attack logic in Battle Nations.
 *
 * <p>This service is responsible for resolving combat between two territories.
 * It validates that an attack is allowed, calculates attack and defense strength,
 * determines the outcome probabilistically, and updates troop counts and ownership
 * accordingly.</p>
 *
 * <p>The outcome of a battle is based on the relative strengths of the attacking
 * and defending territories, incorporating terrain bonuses.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class AttackService {

    /**
     * Constructs an AttackService.
     */
    public AttackService() {
    }

    /**
     * Executes an attack between two territories.
     *
     * <p>If the attack is valid, the outcome is determined using a probability
     * based on the attacking and defending strengths. Troop counts and ownership
     * are updated based on the result.</p>
     *
     * @param territoryAttacking the territory initiating the attack
     * @param territoryDefending the territory being attacked
     * @return the result of the attack attempt
     */
    public ValidationResult attack(Territory territoryAttacking, Territory territoryDefending) {
        ValidationResult validationResult = validateAttack(territoryAttacking, territoryDefending);

        // Stop if the attack is invalid
        if (!validationResult.isValid()) {
            return validationResult;
        }
        double attackStrength = calculateEffectiveAttackStrength(territoryAttacking);
        double defenseStrength = calculateEffectiveDefenseStrength(territoryDefending);

        // Probability of attacker winning based on relative strengths
        double attackingPlayerWinningOdds = attackStrength / (attackStrength + defenseStrength);

        // Random value between 0 and 1 to determine outcome
        double generatedWinningOdds = Math.random();

        int originalDefendingTroops = territoryDefending.getTroopAmount();
        // if attacker wins

        if (attackingPlayerWinningOdds >= generatedWinningOdds) {

            // Calculate surviving troops that will move into the captured territory
            // only let the attacker lose up to the amount the defender had
            int attackingTroopsAvailable = territoryAttacking.getTroopAmount() - 1;

            int survivingAttackingTroops = calculateRemainingTroops(attackingTroopsAvailable, originalDefendingTroops);

            // Attacking territory must leave at least 1 troop behind
            territoryAttacking.setTroopAmount(1);

            // Transfer ownership of the defending territory
            territoryDefending.setPlayer(territoryAttacking.getPlayer());

            // Place surviving troops into the captured territory
            territoryDefending.setTroopAmount(survivingAttackingTroops);

            return new ValidationResult(true, "Attacker Wins");
        } else {

            int originalAttackingTroops = territoryAttacking.getTroopAmount();

            // Attacker loses troops but retains control of the territory
            int newTroops = calculateRemainingTroops(originalAttackingTroops, originalDefendingTroops);

            territoryAttacking.setTroopAmount(newTroops);

            return new ValidationResult(true, "Attacker Lost");
        }
    }

    /**
     * Calculates the effective attack strength of a territory.
     *
     * <p>The strength is based on troop count and terrain attack bonuses.</p>
     *
     * @param territory the attacking territory
     * @return the calculated attack strength
     */
    private double calculateEffectiveAttackStrength(Territory territory) {
        return territory.getTroopAmount() * (1 + territory.getTerrain().getAttackBonus());
    }

    /**
     * Calculates the effective defense strength of a territory.
     *
     * <p>The strength is based on troop count and terrain defense bonuses.</p>
     *
     * @param territory the defending territory
     * @return the calculated defense strength
     */
    private double calculateEffectiveDefenseStrength(Territory territory) {
        return territory.getTroopAmount() * (1 + territory.getTerrain().getDefenseBonus());
    }

    /**
     * Calculates the number of troops remaining after a battle.
     *
     * <p>A random number of troops are lost, but at least one troop
     * will always remain in the territory.</p>
     *
     * @param troopAmount the original number of troops
     * @return the number of troops remaining after losses
     */
    private int calculateRemainingTroops(int troopAmount, int defendingTroops) {
        if (troopAmount <= 1) {
            return 1;
        }

        int maxLoss = Math.min(defendingTroops, troopAmount - 1);

        int troopsLost = (int) (Math.random() * (maxLoss + 1)); // 0 → maxLoss

        int remainingTroops = troopAmount - troopsLost;
        return Math.max(remainingTroops, 1);
    }
    /**
     * Validates whether an attack is allowed.
     *
     * <p>An attack is valid only if both territories are non-null, both have
     * assigned players, the territories are owned by different players, and
     * the attacking territory has at least two troops.</p>
     *
     * @param attackingTerritory the attacking territory
     * @param defendingTerritory the defending territory
     * @return the result of validating the attack
     */
    private ValidationResult validateAttack(Territory attackingTerritory, Territory defendingTerritory) {
        if (attackingTerritory == null || defendingTerritory == null) {
            return new ValidationResult(false, "Territories cannot be null");
        } else if (attackingTerritory.getPlayer() == null || defendingTerritory.getPlayer() == null) {
            return new ValidationResult(false, "Both territories must have a player set");
        } else if (attackingTerritory.getPlayer().equals(defendingTerritory.getPlayer())) {
            return new ValidationResult(false, "Both territories cannot be controlled by the same player");
        } else if (attackingTerritory.getTroopAmount() <= 1) {

            // Must have at least 2 troops to attack (1 must remain behind)
            return new ValidationResult(false, "Attacking territory must have at least 2 troops");
        }

        return new ValidationResult(true, "Valid Attack");

    }
}