package game;

import map.Territory;

/**
 * Handles fortification logic in Battle Nations.
 *
 * <p>This service is responsible for moving troops between territories
 * owned by the same player. It validates that the move is allowed and
 * then updates troop counts accordingly.</p>
 *
 * <p>Fortification allows players to strategically reposition troops
 * after attacking, preparing for future turns.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class FortifyService {

    /**
     * Constructs a FortifyService.
     */
    public FortifyService() {
    }

    /**
     * Moves troops from one territory to another.
     *
     * <p>If the move is valid, troops are removed from the source territory
     * and added to the destination territory.</p>
     *
     * @param territoryToTakeTroopsFrom the territory losing troops
     * @param territoryToAddTroopsTo    the territory gaining troops
     * @param troopsBeingMoved          the number of troops to move
     * @return the result of the fortify attempt
     */
    public ValidationResult fortify(Territory territoryToTakeTroopsFrom, Territory territoryToAddTroopsTo, int troopsBeingMoved) {

        ValidationResult result = validateFortify(territoryToTakeTroopsFrom, territoryToAddTroopsTo, troopsBeingMoved);

        // If validation fails, return the error result immediately
        if (!result.isValid()) {
            return result;
        }

        // Remove troops from the source territory
        territoryToTakeTroopsFrom.setTroopAmount(territoryToTakeTroopsFrom.getTroopAmount() - troopsBeingMoved);

        // Add troops to the destination territory
        territoryToAddTroopsTo.setTroopAmount(territoryToAddTroopsTo.getTroopAmount() + troopsBeingMoved);

        return new ValidationResult(true, "Fortify Move made.");
    }

    /**
     * Validates whether a fortification move is allowed.
     *
     * <p>A valid fortify move requires both territories to have owners,
     * the same player to own both territories, at least one troop to be moved,
     * and the source territory to have enough troops remaining.</p>
     *
     * @param territoryToTakeTroopsFrom the territory losing troops
     * @param territoryToAddTroopsTo    the territory gaining troops
     * @param troopsBeingMoved          the number of troops to move
     * @return the result of validating the fortify move
     */
    public ValidationResult validateFortify(Territory territoryToTakeTroopsFrom, Territory territoryToAddTroopsTo, int troopsBeingMoved) {
        if (territoryToTakeTroopsFrom.getPlayer() == null || territoryToAddTroopsTo.getPlayer() == null) {
            return new ValidationResult(false, "Territories cannot be null");
        } else if (!territoryToTakeTroopsFrom.getPlayer().equals(territoryToAddTroopsTo.getPlayer())) {
            return new ValidationResult(false, "Player must own both territories to move troops");
        } else if (territoryToTakeTroopsFrom.getTroopAmount() <= troopsBeingMoved) {
            return new ValidationResult(false, "Not enough troops to move");
        } else if (troopsBeingMoved < 1) {
            // Must leave at least 1 troop behind in the source territory
            return new ValidationResult(false, "At least 1 troop Must be moved");
        }
        return new ValidationResult(true, "Valid Fortify Move Has been made");
    }
}
