package game;

import map.Territory;

import java.util.ArrayList;

/**
 * Handles fortification logic in Battle Nations.
 *
 * <p>This service is responsible for moving troops between territories
 * owned by the same player. It validates that the move is allowed and
 * then updates troop counts accordingly.</p>
 *
 * <p>Fortification allows players to strategically reposition troops
 * after attacking, preparing for future turns.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Researched searching algorithms for the fortify chain logic.
 *   Found that depth-first search would be useful for traversing player-owned
 *   territory connections. Had ChatGPT implement a version of depth-first search
 *   tailored to our game. This includes the {@code areTerritoriesConnected},
 *   {@code getAllNeighboringOwnedTerritories}, and {@code searchNeighboringOwnedTerritories}
 *   methods. All code was reviewed by the author.</li>
 *
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public class FortifyService {

    /**
     * Constructs a FortifyService.
     */
    public FortifyService() {
    }

    /**
     * Moves troops from one territory to another.
     *
     * <p>If the move is valid, troops are removed from the source territory
     * and added to the destination territory.</p>
     *
     * @param territoryToTakeTroopsFrom the territory losing troops
     * @param territoryToAddTroopsTo    the territory gaining troops
     * @param troopsBeingMoved          the number of troops to move
     * @return the result of the fortify attempt
     */
    public ValidationResult fortify(Territory territoryToTakeTroopsFrom, Territory territoryToAddTroopsTo, int troopsBeingMoved) {
        ValidationResult result = validateFortify(territoryToTakeTroopsFrom, territoryToAddTroopsTo, troopsBeingMoved);

        // If validation fails, return the error result immediately
        if (!result.isValid()) {
            return result;
        }

        // Remove troops from the source territory
        territoryToTakeTroopsFrom.setTroopAmount(territoryToTakeTroopsFrom.getTroopAmount() - troopsBeingMoved);

        // Add troops to the destination territory
        territoryToAddTroopsTo.setTroopAmount(territoryToAddTroopsTo.getTroopAmount() + troopsBeingMoved);

        return new ValidationResult(true, "Fortify Move made.");
    }

    /**
     * Validates whether a fortification move is allowed.
     *
     * <p>A valid fortify move requires both territories to have owners,
     * the same player to own both territories, at least one troop to be moved,
     * the source territory to have enough troops to spare, and a valid
     * path of player-owned territories connecting the two.</p>
     *
     * @param territoryToTakeTroopsFrom the territory losing troops
     * @param territoryToAddTroopsTo    the territory gaining troops
     * @param troopsBeingMoved          the number of troops to move
     * @return the result of validating the fortify move
     */
    private ValidationResult validateFortify(Territory territoryToTakeTroopsFrom, Territory territoryToAddTroopsTo, int troopsBeingMoved) {
        if (territoryToTakeTroopsFrom.getPlayer() == null || territoryToAddTroopsTo.getPlayer() == null) {
            return new ValidationResult(false, "Territories cannot be null");
        } else if (!territoryToTakeTroopsFrom.getPlayer().equals(territoryToAddTroopsTo.getPlayer())) {
            return new ValidationResult(false, "Player must own both territories to move troops");
        } else if (territoryToTakeTroopsFrom.getTroopAmount() <= troopsBeingMoved) {
            return new ValidationResult(false, "Not enough troops to move");
        } else if (troopsBeingMoved < 1) {
            // Must move at least 1 troop — 0 or negative is not a valid fortify
            return new ValidationResult(false, "At least 1 troop Must be moved");
        } else if (!areTerritoriesConnected(territoryToTakeTroopsFrom, territoryToAddTroopsTo)) {
            return new ValidationResult(false, "Territories must be connected together by player Owned territories to fortify");
        }

        return new ValidationResult(true, "Valid Fortify Move Has been made");
    }

    // Start of code from ChatGPT

    /**
     * Determines whether two territories are connected through a chain of player-owned territories.
     *
     * <p>Checks each owned neighbor of the source territory as a potential starting
     * point, then performs a depth-first search to see if the destination can be reached.</p>
     *
     * @param attackingTerritory the territory to move troops from
     * @param defendingTerritory the territory to move troops to
     * @return true if a valid path exists between the two territories, false otherwise
     */
    private boolean areTerritoriesConnected(Territory attackingTerritory, Territory defendingTerritory) {
        ArrayList<Territory> neighboringPlayerOwnedTerritories = getAllNeighboringOwnedTerritories(attackingTerritory);

        for (Territory ownedTerritory : neighboringPlayerOwnedTerritories) {
            ArrayList<Territory> ownedTerritoriesVisited = new ArrayList<>();

            // Start a depth-first search from each owned neighbor
            // A fresh visited list is used per starting point to allow all paths to be explored
            if (searchNeighboringOwnedTerritories(ownedTerritory, defendingTerritory, ownedTerritoriesVisited)) {
                return true;
            }
        }

        // No path found through any owned neighbor
        return false;
    }

    /**
     * Returns all neighboring territories that are owned by the same player as the given territory.
     *
     * @param attackingTerritory the territory whose neighbors are being checked
     * @return a list of neighboring territories owned by the same player
     */
    private ArrayList<Territory> getAllNeighboringOwnedTerritories(Territory attackingTerritory) {
        ArrayList<Territory> neighboringOwnedTerritories = new ArrayList<>();

        for (Territory territory : attackingTerritory.getNeighboringTerritories()) {
            // Only include neighbors owned by the same player
            if (territory.getPlayer() == attackingTerritory.getPlayer()) {
                neighboringOwnedTerritories.add(territory);
            }
        }

        return neighboringOwnedTerritories;
    }

    /**
     * Recursively searches through player-owned neighboring territories to find a path
     * to the destination territory.
     *
     * <p>Uses a visited list to prevent revisiting territories and avoid infinite loops
     * in circular territory graphs.</p>
     *
     * @param neighboringOwnedTerritory the current territory being explored
     * @param defendingTerritory        the destination territory being searched for
     * @param ownedTerritoriesVisited   the list of territories already visited in this search
     * @return true if the destination territory is reachable from the current territory, false otherwise
     */
    private boolean searchNeighboringOwnedTerritories(Territory neighboringOwnedTerritory, Territory defendingTerritory,
                                                      ArrayList<Territory> ownedTerritoriesVisited) {
        if (neighboringOwnedTerritory == null || ownedTerritoriesVisited.contains(neighboringOwnedTerritory)) {
            return false;
        }

        // Mark this territory as visited before exploring its neighbors
        ownedTerritoriesVisited.add(neighboringOwnedTerritory);

        for (Territory territory : neighboringOwnedTerritory.getNeighboringTerritories()) {
            // Found the destination — path exists
            if (territory == defendingTerritory) {
                return true;
            }

            // Only recurse into territories owned by the same player as the destination
            // This ensures the path stays within player-owned territory the entire way
            if (territory.getPlayer() == defendingTerritory.getPlayer()) {
                if (searchNeighboringOwnedTerritories(territory, defendingTerritory, ownedTerritoriesVisited)) {
                    return true;
                }
            }
        }

        return false;
    }

    // End of code from ChatGPT
}