package game;

import map.Territory;
import map.World;
import player.Player;

import java.util.ArrayList;
import java.util.List;

/**
 * Coordinates core gameplay logic in Battle Nations.
 *
 * <p>This class acts as a central controller that connects the game world,
 * players, and various gameplay services. It delegates actions such as
 * attacking, reinforcing, and fortifying to their respective services,
 * ensuring that the GUI does not need to manage game rules directly.</p>
 *
 * <p>GameLogic also manages the current turn phase, controlling which
 * actions are allowed at a given time.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class GameLogic {
    /**
     * The game world containing all territories and regions.
     */
    private final World world;

    /**
     * The list of players participating in the game.
     */
    private final List<Player> players;

    /**
     * Service responsible for handling attack logic.
     */
    private final AttackService attackService;

    /**
     * Service responsible for handling reinforcement logic.
     */
    private final ReinforcementService reinforcementService;

    /**
     * Service responsible for handling fortification logic.
     */
    private final FortifyService fortifyService;

    /**
     * The current phase of the player's turn.
     */
    private TurnPhase currentPhase;

    private int currentPlayerIndex = 0;

    private Player winner = null;

    /**
     * Constructs a GameLogic instance with all required dependencies.
     *
     * <p>The provided player list is copied to prevent external modification
     * from affecting the internal game state.</p>
     *
     * @param world                the game world
     * @param players              the list of players
     * @param attackService        the service used for attack actions
     * @param reinforcementService the service used for reinforcement actions
     * @param fortifyService       the service used for fortification actions
     */
    public GameLogic(World world, List<Player> players, AttackService attackService, ReinforcementService reinforcementService, FortifyService fortifyService) {
        this.world = world;

        // Copy the player list to avoid unintended external modifications
        this.players = new ArrayList<>(players);

        this.attackService = attackService;
        this.reinforcementService = reinforcementService;
        this.fortifyService = fortifyService;

        // always starts in the reinforcement phase
        this.currentPhase = TurnPhase.REINFORCEMENT;
    }

    /**
     * Executes an attack between two territories.
     *
     * @param attackingTerritory the territory initiating the attack
     * @param defendingTerritory the territory being attacked
     * @return the result of the attack attempt
     */
    public ValidationResult attack(Territory attackingTerritory, Territory defendingTerritory) {
        return attackService.attack(attackingTerritory, defendingTerritory);
    }

    /**
     * Moves troops between two owned territories.
     *
     * @param territoryToTakeTroopsFrom the territory losing troops
     * @param territoryToAddTroopsTo    the territory gaining troops
     * @param troopsBeingMoved          the number of troops to move
     * @return the result of the fortify attempt
     */
    public ValidationResult fortify(Territory territoryToTakeTroopsFrom, Territory territoryToAddTroopsTo, int troopsBeingMoved) {
        return fortifyService.fortify(territoryToTakeTroopsFrom, territoryToAddTroopsTo, troopsBeingMoved);
    }

    /**
     * Adds reinforcement troops to a territory.
     *
     * @param player      the player placing troops
     * @param territory   the territory receiving troops
     * @param troopsToAdd the number of troops to add
     * @return the result of the reinforcement attempt
     */
    public ValidationResult reinforce(Player player, Territory territory, int troopsToAdd) {
        return reinforcementService.reinforce(player, territory, troopsToAdd);
    }

    /**
     * Calculates the number of reinforcements a player receives.
     *
     * @return the number of troops available to place
     */
    public void calculateReinforcement() {
        reinforcementService.calculateReinforcements(getCurrentPlayer(), world);
    }

    /**
     * Advances the game to the next turn phase.
     *
     * <p>The phase order cycles as follows:
     * REINFORCEMENT → ATTACK → FORTIFY → REINFORCEMENT.</p>
     */
    public void changePhase() {

        // Cycle through phases in a fixed order
        if (currentPhase == TurnPhase.REINFORCEMENT) {
            currentPhase = TurnPhase.ATTACK;
        } else if (currentPhase == TurnPhase.ATTACK) {
            currentPhase = TurnPhase.FORTIFY;
        } else {
            incrementPlayerIndex();
            currentPhase = TurnPhase.REINFORCEMENT;
        }
    }

    /**
     * Returns the current phase of the turn.
     *
     * @return the current turn phase
     */
    public TurnPhase getCurrentPhase() {
        return currentPhase;
    }

    /**
     * Returns the game world.
     *
     * @return the world instance
     */
    public World getWorld() {
        return world;
    }

    /**
     * Returns the list of players.
     *
     * @return the list of players in the game
     */
    public List<Player> getPlayers() {
        return players;
    }

    private void incrementPlayerIndex() {
        if (currentPlayerIndex == players.size() - 1) {
            currentPlayerIndex = 0;
        } else {
            currentPlayerIndex++;
        }
    }

    public Player getCurrentPlayer() {
        return players.get(currentPlayerIndex);
    }


    public boolean isTerritoryPlayerOwned(Territory territory) {
        return territory.getPlayer() != null &&
                territory.getPlayer().equals(getCurrentPlayer());
    }

    public boolean isGameOver() {
        if (world.isGameWon(players)) {
            winner = world.getWinningPlayer(players);
            return true;
        } else {
            return false;
        }
    }

    public Player getWinner() {
        return winner;
    }
}
