package game;

import map.Territory;
import map.World;
import player.Player;

import java.util.ArrayList;
import java.util.List;

/**
 * Coordinates core gameplay logic in Battle Nations.
 *
 * <p>This class acts as a central controller that connects the game world,
 * players, and various gameplay services. It delegates actions such as
 * attacking, reinforcing, and fortifying to their respective services,
 * ensuring that the GUI does not need to manage game rules directly.</p>
 *
 * <p>GameLogic also manages the current turn phase and current player index,
 * controlling which actions are allowed at a given time and whose turn it is.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 *
 */
public class GameLogic {

    /** The game world containing all territories and regions. */
    private final World world;

    /** The list of players participating in the game. */
    private final List<Player> players;

    /** Service responsible for handling attack logic. */
    private final AttackService attackService;

    /** Service responsible for handling reinforcement logic. */
    private final ReinforcementService reinforcementService;

    /** Service responsible for handling fortification logic. */
    private final FortifyService fortifyService;

    /** The current phase of the player's turn. */
    private TurnPhase currentPhase;

    /** Index of the current player in the players list. */
    private int currentPlayerIndex = 0;

    /** The player who has won the game, or null if the game is still in progress. */
    private Player winner = null;

    /**
     * Constructs a GameLogic instance with all required dependencies.
     *
     * <p>The provided player list is copied to prevent external modification
     * from affecting the internal game state. The game always starts in the
     * reinforcement phase.</p>
     *
     * @param world                the game world
     * @param players              the list of players
     * @param attackService        the service used for attack actions
     * @param reinforcementService the service used for reinforcement actions
     * @param fortifyService       the service used for fortification actions
     */
    public GameLogic(World world, List<Player> players, AttackService attackService, ReinforcementService reinforcementService, FortifyService fortifyService) {
        this.world = world;

        // Copy the player list to avoid unintended external modifications
        this.players = new ArrayList<>(players);

        this.attackService = attackService;
        this.reinforcementService = reinforcementService;
        this.fortifyService = fortifyService;

        // Always starts in the reinforcement phase
        this.currentPhase = TurnPhase.REINFORCEMENT;
    }

    /**
     * Executes an attack between two territories.
     *
     * <p>Delegates to {@link AttackService} — see that class for full validation rules.</p>
     *
     * @param attackingTerritory the territory initiating the attack
     * @param defendingTerritory the territory being attacked
     * @return the result of the attack attempt
     */
    public ValidationResult attack(Territory attackingTerritory, Territory defendingTerritory) {
        return attackService.attack(attackingTerritory, defendingTerritory);
    }

    /**
     * Moves troops between two owned territories.
     *
     * <p>Delegates to {@link FortifyService} — see that class for full validation rules.</p>
     *
     * @param territoryToTakeTroopsFrom the territory losing troops
     * @param territoryToAddTroopsTo    the territory gaining troops
     * @param troopsBeingMoved          the number of troops to move
     * @return the result of the fortify attempt
     */
    public ValidationResult fortify(Territory territoryToTakeTroopsFrom, Territory territoryToAddTroopsTo, int troopsBeingMoved) {
        return fortifyService.fortify(territoryToTakeTroopsFrom, territoryToAddTroopsTo, troopsBeingMoved);
    }

    /**
     * Adds reinforcement troops to a territory.
     *
     * <p>Delegates to {@link ReinforcementService} — see that class for full validation rules.</p>
     *
     * @param player      the player placing troops
     * @param territory   the territory receiving troops
     * @param troopsToAdd the number of troops to add
     * @return the result of the reinforcement attempt
     */
    public ValidationResult reinforce(Player player, Territory territory, int troopsToAdd) {
        return reinforcementService.reinforce(player, territory, troopsToAdd);
    }

    /**
     * Calculates and sets the number of reinforcement troops for the current player.
     *
     * <p>Delegates to {@link ReinforcementService}, which updates the current
     * player's available troops to place based on territory count and terrain bonuses.</p>
     */
    public void calculateReinforcement() {
        reinforcementService.calculateReinforcements(getCurrentPlayer(), world);
    }

    /**
     * Advances the game to the next turn phase.
     *
     * <p>The phase order cycles as follows:
     * REINFORCEMENT → ATTACK → FORTIFY → REINFORCEMENT.
     * When cycling out of FORTIFY, the current player index is also incremented.</p>
     */
    public void changePhase() {
        // Cycle through phases in a fixed order
        if (currentPhase == TurnPhase.REINFORCEMENT) {
            currentPhase = TurnPhase.ATTACK;
        } else if (currentPhase == TurnPhase.ATTACK) {
            currentPhase = TurnPhase.FORTIFY;
        } else {
            // End of turn — advance to the next player before resetting phase
            incrementPlayerIndex();
            currentPhase = TurnPhase.REINFORCEMENT;
        }
    }

    /**
     * Returns the current phase of the turn.
     *
     * @return the current turn phase
     */
    public TurnPhase getCurrentPhase() {
        return currentPhase;
    }

    /**
     * Returns the game world.
     *
     * @return the world instance
     */
    public World getWorld() {
        return world;
    }

    /**
     * Returns the list of players.
     *
     * @return the list of players in the game
     */
    public List<Player> getPlayers() {
        return players;
    }

    /**
     * Advances to the next player in the list, wrapping back to index 0
     * after the last player has taken their turn.
     */
    private void incrementPlayerIndex() {
        if (currentPlayerIndex == players.size() - 1) {
            // Wrap back to the first player after the last player's turn
            currentPlayerIndex = 0;
        } else {
            currentPlayerIndex++;
        }
    }

    /**
     * Returns the player whose turn it currently is.
     *
     * @return the current player
     */
    public Player getCurrentPlayer() {
        return players.get(currentPlayerIndex);
    }

    /**
     * Determines whether the given territory is owned by the current player.
     *
     * @param territory the territory to check
     * @return true if the territory is owned by the current player, false otherwise
     */
    public boolean isTerritoryPlayerOwned(Territory territory) {
        return territory.getPlayer() != null &&
                territory.getPlayer().equals(getCurrentPlayer());
    }

    /**
     * Checks whether the game has been won and sets the winner if so.
     *
     * <p>Delegates win condition checking to the world. If the game is won,
     * the winning player is stored internally and can be retrieved via
     * {@link #getWinner()}.</p>
     *
     * @return true if the game has been won, false otherwise
     */
    public boolean isGameOver() {
        if (world.isGameWon(players)) {
            // save the winner so it can be retrieved without re-evaluating the world
            winner = world.getWinningPlayer(players);
            return true;
        } else {
            return false;
        }
    }

    /**
     * Returns the player who has won the game.
     *
     * @return the winning player, or null if the game is still in progress
     */
    public Player getWinner() {
        return winner;
    }
}