package game;

import map.Territory;
import map.World;
import player.Player;

/**
 * Handles reinforcement logic in Battle Nations.
 *
 * <p>This service is responsible for calculating the number of troops
 * a player receives at the start of their turn and applying reinforcement
 * actions to territories owned by the player.</p>
 *
 * <p>Reinforcements are determined based on the number of territories
 * owned and any additional bonuses provided by terrain.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public class ReinforcementService {

    /** The divisor used to calculate base reinforcements from territory count. */
    private static final int TERRITORY_COUNT_DIVISOR = 3;

    /** The minimum number of reinforcements a player may receive. */
    private static final int MINIMUM_TROOPS_RETURNED = 3;

    /**
     * Constructs a ReinforcementService.
     */
    public ReinforcementService() {
    }

    /**
     * Calculates and sets the total number of reinforcements a player receives.
     *
     * <p>Base troops are calculated from territory count divided by the divisor,
     * floored at the minimum. Terrain bonuses from each owned territory are then
     * added on top. The result is applied directly to the player's troops to place.</p>
     *
     * @param player the player receiving reinforcements
     * @param world  the game world used to determine territory ownership
     */
    public void calculateReinforcements(Player player, World world) {
        int playerTerritoryCount = world.getTerritoryCountOwnedByPlayer(player);

        // Base troops = territory count / 3, floored at the minimum
        int baseTroops = playerTerritoryCount / TERRITORY_COUNT_DIVISOR;

        // Ensure player always receives at least the minimum reinforcement
        baseTroops = Math.max(baseTroops, MINIMUM_TROOPS_RETURNED);

        int terrainBonusTroops = 0;

        // Add bonus troops from each owned territory's terrain
        for (Territory territory : world.getTerritoriesOwnedByPlayer(player)) {
            terrainBonusTroops += territory.getTerrain().getTroopBonus();
        }

        player.setTroopsToPlace(baseTroops + terrainBonusTroops);
    }

    /**
     * Reinforces a territory owned by the player.
     *
     * <p>If the reinforcement move is valid, the specified number of troops
     * is removed from the player's available troops and added to the selected
     * territory.</p>
     *
     * @param player      the player placing reinforcement troops
     * @param territory   the territory receiving troops
     * @param troopsToAdd the number of troops to add to the territory
     * @return the result of the reinforcement attempt
     */
    public ValidationResult reinforce(Player player, Territory territory, int troopsToAdd) {
        ValidationResult result = validateReinforce(player, territory, troopsToAdd);

        if (!result.isValid()) {
            return result;
        }

        // Deduct placed troops from the player's available pool
        player.setTroopsToPlace(player.getTroopsToPlace() - troopsToAdd);

        // Add the troops to the target territory
        territory.setTroopAmount(territory.getTroopAmount() + troopsToAdd);

        return new ValidationResult(true, "Territory has been reinforced");
    }

    /**
     * Validates whether a reinforcement move is allowed.
     *
     * <p>A reinforcement move is valid only if the player and territory are
     * not null, the territory is owned by the player, at least one troop is
     * being added, and the player has enough troops available to place.</p>
     *
     * @param player      the player attempting to reinforce a territory
     * @param territory   the territory to reinforce
     * @param troopsToAdd the number of troops to add
     * @return the result of validating the reinforcement move
     */
    private ValidationResult validateReinforce(Player player, Territory territory, int troopsToAdd) {
        if (player == null) {
            return new ValidationResult(false, "Player cannot be null");
        } else if (territory == null) {
            return new ValidationResult(false, "Territory cannot be null");
        } else if (territory.getPlayer() == null || !territory.getPlayer().equals(player)) {
            return new ValidationResult(false, "Territory must be owned by " + player.getName());
        } else if (troopsToAdd <= 0) {
            return new ValidationResult(false, "Troops to add must be at least 1");
        } else if (player.getTroopsToPlace() < troopsToAdd) {
            // Player cannot place more troops than they currently have available
            return new ValidationResult(false, "Player doesn't have enough troops to place");
        }

        return new ValidationResult(true, "Valid Reinforcement Move");
    }
}