package game;

import map.Territory;
import player.Player;
import terrain.TerrainType;

import java.awt.*;

/**
 * Manual test suite for {@link AttackService} in Battle Nations.
 *
 * <p>Tests the {@code attack} method across a range of valid and invalid inputs,
 * as well as probabilistic outcome scenarios. Each test method is self-contained,
 * builds its own state, and returns true or false. The {@code main} method runs
 * all tests and reports whether the suite passed or failed overall.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public class TestAttackService {

    /**
     * Runs all tests in the suite and prints the overall result.
     *
     * <p>Each test method is called in sequence. If any one of them fails,
     * the suite is marked as failed. Results are printed to stdout on pass
     * and stderr on fail.</p>
     *
     * @param args command-line arguments (not used)
     */
    public static void main(String[] args) {
        // Tracks whether every test in this file passed.
        boolean passed = true;

        System.out.println("Testing Methods");

        // Run each test method and mark the suite as failed if any individual test fails.

        if (!testValidAttack()) passed = false;
        if (!testNullAttackingTerritory()) passed = false;
        if (!testNullDefendingTerritory()) passed = false;
        if (!testAttackWhenAttackingTerritoryHasNoPlayerSet()) passed = false;
        if (!testAttackWhenDefendingTerritoryHasNoPlayerSet()) passed = false;
        if (!testAttackWhenBothTerritoriesOwnedBySamePlayer()) passed = false;
        if (!testAttackWhenAttackingTerritoryOnlyHasOneTroop()) passed = false;
        if (!testAttackWhenTerritoriesAreNotNeighbors()) passed = false;
        if (!testAttackOutcomeRandomnessWithoutBonuses()) passed = false;

        // Print overall test results after all test methods have been executed.
        if (passed) {
            System.out.println("All Tests Passed");
        } else {
            System.err.println("At least one Test Failed");
        }
    }

    /**
     * Tests that a valid attack call succeeds.
     *
     * <p>Sets up two players each owning a neighboring territory with enough troops.
     * Runs 100 iterations, resetting troop counts and ownership each time to make
     * sure the result doesn't depend on leftover state from a prior iteration.</p>
     *
     * @return true if all 100 iterations return a valid result, false otherwise
     */
    private static boolean testValidAttack() {
        boolean passed = true;
        System.out.print("Testing valid attack: ");

        Player player1 = new Player("p1", Color.blue);
        Player player2 = new Player("p2", Color.red);

        Territory attackingTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory defendingTerritory = new Territory(player2, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // Make them neighbors so the attack is allowed
        attackingTerritory.addToTerritoryNeighbors(defendingTerritory);
        defendingTerritory.addToTerritoryNeighbors(attackingTerritory);

        AttackService attackService = new AttackService();

        for (int i = 0; i < 100; i++) {
            ValidationResult result = attackService.attack(attackingTerritory, defendingTerritory);
            if (!result.isValid()) {
                passed = false;
                System.err.println("During Iteration " + i + " attack result was false when it should have been true");
            }

            // Reset state between iterations so each call starts from the same conditions
            attackingTerritory.setPlayer(player1);
            attackingTerritory.setTroopAmount(20);
            defendingTerritory.setPlayer(player2);
            defendingTerritory.setTroopAmount(20);
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }

        return passed;
    }

    /**
     * Tests that passing null as the attacking territory is handled gracefully.
     *
     * <p>Passes null in place of the attacking territory across 100 iterations
     * and checks that the service returns an invalid result each time without
     * throwing an exception.</p>
     *
     * @return true if all 100 iterations return an invalid result, false otherwise
     */
    private static boolean testNullAttackingTerritory() {
        boolean passed = true;
        System.out.print("Testing attack with a null attacking territory: ");

        Player player1 = new Player("p1", Color.blue);

        Territory defendingTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        AttackService attackService = new AttackService();

        for (int i = 0; i < 100; i++) {
            // null attacking territory — service must not throw a NullPointerException
            ValidationResult result = attackService.attack(null, defendingTerritory);
            if (result.isValid()) {
                passed = false;
                System.err.println("During Iteration " + i + " attack result was true when it should have been false");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }

        return passed;
    }

    /**
     * Tests that passing null as the defending territory is handled gracefully.
     *
     * <p>Passes null in place of the defending territory across 100 iterations
     * and checks that the service returns an invalid result each time without
     * throwing an exception.</p>
     *
     * @return true if all 100 iterations return an invalid result, false otherwise
     */
    private static boolean testNullDefendingTerritory() {
        boolean passed = true;
        System.out.print("Testing attack with a null defending territory: ");

        Player player1 = new Player("p1", Color.blue);

        Territory attackingTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        AttackService attackService = new AttackService();

        for (int i = 0; i < 100; i++) {
            // null defending territory — service must not throw a NullPointerException
            ValidationResult result = attackService.attack(attackingTerritory, null);
            if (result.isValid()) {
                passed = false;
                System.err.println("During Iteration " + i + " attack result was true when it should have been false");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }

        return passed;
    }

    /**
     * Tests that an attack is rejected when the attacking territory has no player set.
     *
     * <p>Constructs the attacking territory using the unowned constructor so its
     * player is null. Runs 100 iterations confirming the result is always invalid.</p>
     *
     * @return true if all 100 iterations return an invalid result, false otherwise
     */
    private static boolean testAttackWhenAttackingTerritoryHasNoPlayerSet() {
        boolean passed = true;
        System.out.print("Testing attack when the attacking territory has no player set: ");

        Player player1 = new Player("p1", Color.blue);

        // Unowned constructor — attacking territory has no player assigned
        Territory attackingTerritory = new Territory(TerrainType.DESERT.getTerrain(), new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory defendingTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        attackingTerritory.addToTerritoryNeighbors(defendingTerritory);
        defendingTerritory.addToTerritoryNeighbors(attackingTerritory);

        AttackService attackService = new AttackService();

        for (int i = 0; i < 100; i++) {
            ValidationResult result = attackService.attack(attackingTerritory, defendingTerritory);
            if (result.isValid()) {
                passed = false;
                System.err.println("During Iteration " + i + " attack result was true when it should have been false");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }

        return passed;
    }

    /**
     * Tests that an attack is rejected when the defending territory has no player set.
     *
     * <p>Constructs the defending territory using the unowned constructor so its
     * player is null. Runs 100 iterations confirming the result is always invalid.</p>
     *
     * @return true if all 100 iterations return an invalid result, false otherwise
     */
    private static boolean testAttackWhenDefendingTerritoryHasNoPlayerSet() {
        boolean passed = true;
        System.out.print("Testing attack when the defending territory has no player set: ");

        Player player1 = new Player("p1", Color.blue);

        Territory attackingTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // Unowned constructor — defending territory has no player assigned
        Territory defendingTerritory = new Territory(TerrainType.DESERT.getTerrain(), new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        attackingTerritory.addToTerritoryNeighbors(defendingTerritory);
        defendingTerritory.addToTerritoryNeighbors(attackingTerritory);

        AttackService attackService = new AttackService();

        for (int i = 0; i < 100; i++) {
            ValidationResult result = attackService.attack(attackingTerritory, defendingTerritory);
            if (result.isValid()) {
                passed = false;
                System.err.println("During Iteration " + i + " attack result was true when it should have been false");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }

        return passed;
    }

    /**
     * Tests that a player can't attack a territory they already own.
     *
     * <p>Assigns both territories to the same player and runs 100 iterations
     * confirming the result is always invalid.</p>
     *
     * @return true if all 100 iterations return an invalid result, false otherwise
     */
    private static boolean testAttackWhenBothTerritoriesOwnedBySamePlayer() {
        boolean passed = true;
        System.out.print("Testing attack when both territories are owned by same player: ");

        Player player1 = new Player("p1", Color.blue);

        // Both territories assigned to player1 — friendly fire should always be rejected
        Territory attackingTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory defendingTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        attackingTerritory.addToTerritoryNeighbors(defendingTerritory);
        defendingTerritory.addToTerritoryNeighbors(attackingTerritory);

        AttackService attackService = new AttackService();

        for (int i = 0; i < 100; i++) {
            ValidationResult result = attackService.attack(attackingTerritory, defendingTerritory);
            if (result.isValid()) {
                passed = false;
                System.err.println("During Iteration " + i + " attack result was true when it should have been false");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }

        return passed;
    }

    /**
     * Tests that an attack is rejected when the attacking territory only has one troop.
     *
     * <p>Sets the attacking territory's troop count to 1, since at least one troop
     * must always remain behind. Runs 100 iterations confirming the result is always invalid.</p>
     *
     * @return true if all 100 iterations return an invalid result, false otherwise
     */
    private static boolean testAttackWhenAttackingTerritoryOnlyHasOneTroop() {
        boolean passed = true;
        System.out.print("Testing attack when attacking territory only has one troop: ");

        Player player1 = new Player("p1", Color.blue);
        Player player2 = new Player("p2", Color.red);

        Territory attackingTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 1, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory defendingTerritory = new Territory(player2, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        attackingTerritory.addToTerritoryNeighbors(defendingTerritory);
        defendingTerritory.addToTerritoryNeighbors(attackingTerritory);

        AttackService attackService = new AttackService();

        // Explicitly set to 1 to be safe — a territory with 1 troop cannot attack
        attackingTerritory.setTroopAmount(1);

        for (int i = 0; i < 100; i++) {
            ValidationResult result = attackService.attack(attackingTerritory, defendingTerritory);
            if (result.isValid()) {
                passed = false;
                System.err.println("During Iteration " + i + " attack result was true when it should have been false");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }

        return passed;
    }

    /**
     * Tests that an attack is rejected when the two territories are not neighbors.
     *
     * <p>Creates two territories without adding each other as neighbors. Runs
     * 100 iterations confirming the result is always invalid.</p>
     *
     * @return true if all 100 iterations return an invalid result, false otherwise
     */
    private static boolean testAttackWhenTerritoriesAreNotNeighbors() {
        boolean passed = true;
        System.out.print("Testing attack when territories are not neighbors: ");

        Player player1 = new Player("p1", Color.blue);
        Player player2 = new Player("p2", Color.red);

        Territory attackingTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory defendingTerritory = new Territory(player2, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // Neighbors are intentionally never added — attack across non-adjacent territories should always fail
        AttackService attackService = new AttackService();

        for (int i = 0; i < 100; i++) {
            ValidationResult result = attackService.attack(attackingTerritory, defendingTerritory);
            if (result.isValid()) {
                passed = false;
                System.err.println("During Iteration " + i + " attack result was true when it should have been false");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }

        return passed;
    }

    /**
     * Tests that attack outcomes are probabilistically reasonable across three troop scenarios.
     *
     * <p>Runs 10000 iterations for each scenario and checks that the attacker's win rate
     * falls within expected bounds. Due to the stopping condition giving the defender a
     * structural advantage, win rates are skewed lower than pure probability would suggest.
     * Bounds are set based on observed behavior of the combat system rather than theoretical odds.</p>
     *
     * @return true if all three scenarios produce win rates within their expected bounds, false otherwise
     */
    private static boolean testAttackOutcomeRandomnessWithoutBonuses() {
        boolean passed = true;
        System.out.print("Testing attack outcome randomness without bonuses: ");

        Player player1 = new Player("p1", Color.blue);
        Player player2 = new Player("p2", Color.red);

        Territory attackingTerritory = new Territory(player1, TerrainType.PLAIN.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory defendingTerritory = new Territory(player2, TerrainType.PLAIN.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        attackingTerritory.addToTerritoryNeighbors(defendingTerritory);
        defendingTerritory.addToTerritoryNeighbors(attackingTerritory);

        AttackService attackService = new AttackService();

        // ---- 50/50 scenario — equal troops, no bonuses ----
        int attacksWon = 0;
        int attacksLost = 0;

        for (int i = 0; i < 10000; i++) {
            ValidationResult result = attackService.attack(attackingTerritory, defendingTerritory);
            if (!result.isValid()) {
                passed = false;
                System.err.println("During Iteration " + i + " attack result was true when it should have been false");
            }
            if (result.message().equals("Attacker Wins")) {
                attacksWon++;
            } else {
                attacksLost++;
            }

            // Reset to the same troop counts used at the start of this scenario
            attackingTerritory.setPlayer(player1);
            attackingTerritory.setTroopAmount(20);
            defendingTerritory.setPlayer(player2);
            defendingTerritory.setTroopAmount(20);
        }

        double winRate = (double) attacksWon / (attacksWon + attacksLost);

        // Defender has a structural advantage due to the stopping condition, so attacker wins less than 50%
        if (winRate < 0.15 || winRate > 0.50) {
            passed = false;
            System.err.println("50/50 scenario win rate was " + winRate + ", expected between 0.15 and 0.50");
        }

        // ---- ~25% win rate scenario — attacker slightly disadvantaged ----
        int attacksWon25 = 0;
        int attacksLost25 = 0;

        attackingTerritory.setTroopAmount(17);
        defendingTerritory.setTroopAmount(20);
        attackingTerritory.setPlayer(player1);
        defendingTerritory.setPlayer(player2);

        for (int i = 0; i < 10000; i++) {
            ValidationResult result = attackService.attack(attackingTerritory, defendingTerritory);
            if (result.message().equals("Attacker Wins")) {
                attacksWon25++;
            } else {
                attacksLost25++;
            }

            // Reset must match the troop counts set before this loop
            attackingTerritory.setPlayer(player1);
            attackingTerritory.setTroopAmount(17);
            defendingTerritory.setPlayer(player2);
            defendingTerritory.setTroopAmount(20);
        }

        double winRate25 = (double) attacksWon25 / (attacksWon25 + attacksLost25);

        if (winRate25 < 0.05 || winRate25 > 0.35) {
            passed = false;
            System.err.println("25% scenario win rate was " + winRate25 + ", expected between 0.05 and 0.35");
        }

        // ---- ~75% win rate scenario — attacker clearly favored ----
        int attacksWon75 = 0;
        int attacksLost75 = 0;

        attackingTerritory.setTroopAmount(20);
        defendingTerritory.setTroopAmount(15);
        attackingTerritory.setPlayer(player1);
        defendingTerritory.setPlayer(player2);

        for (int i = 0; i < 10000; i++) {
            ValidationResult result = attackService.attack(attackingTerritory, defendingTerritory);
            if (result.message().equals("Attacker Wins")) {
                attacksWon75++;
            } else {
                attacksLost75++;
            }

            // Reset must match the troop counts set before this loop
            attackingTerritory.setPlayer(player1);
            attackingTerritory.setTroopAmount(20);
            defendingTerritory.setPlayer(player2);
            defendingTerritory.setTroopAmount(15);
        }

        double winRate75 = (double) attacksWon75 / (attacksWon75 + attacksLost75);

        if (winRate75 < 0.50 || winRate75 > 0.95) {
            passed = false;
            System.err.println("75% scenario win rate was " + winRate75 + ", expected between 0.50 and 0.95");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }

        return passed;
    }
}