package game;

import map.Region;
import map.Territory;
import map.TotalDominationWorld;
import player.Player;
import terrain.TerrainType;

import java.awt.*;
import java.util.ArrayList;

/**
 * Manual test suite for {@link ReinforcementService} in Battle Nations.
 *
 * <p>Tests both the {@code reinforce} and {@code calculateReinforcements} methods
 * across a range of valid and invalid inputs. Each test method is self-contained,
 * builds its own state, and returns true or false. The {@code main} method runs
 * all tests and reports whether the suite passed or failed overall.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 *
 * @author J.D. Reighard
 * @version 1.0
 * @since 2026-03-04
 * @see ReinforcementService
 */
public class TestReinforcementService {

    /**
     * Runs all tests in the suite and prints the overall result.
     *
     * <p>Each test method is called in sequence. If any one of them fails,
     * the suite is marked as failed. Results are printed to stdout on pass
     * and stderr on fail.</p>
     *
     * @param args command-line arguments (not used)
     */
    public static void main(String[] args) {
        // Tracks whether every test in this file passed.
        boolean passed = true;

        System.out.println("Testing Methods");

        // Run each test method and mark the suite as failed if any individual test fails.

        if (!testValidReinforcement()) passed = false;
        if (!testReinforcementWhenPlayerDoesNotOwnTerritory()) passed = false;
        if (!testReinforcementServiceWith0TroopsBeingPlaced()) passed = false;
        if (!testReinforceWithMoreTroopsThenPlayerHas()) passed = false;
        if (!testReinforceWithNullPlayer()) passed = false;
        if (!testReinforceWithNullTerritory()) passed = false;
        if (!testCalculateReinforcementBaseAmount()) passed = false;
        if (!testCalculateReinforcementWithNoTerritoryBonus()) passed = false;
        if (!testCalculateReinforcementWithTerritoryBonuses()) passed = false;

        // Print overall test results after all test methods have been executed.
        if (passed) {
            System.out.println("All Tests Passed");
        } else {
            System.err.println("At least one Test Failed");
        }
    }

    /**
     * Tests that a valid reinforcement call succeeds.
     *
     * <p>Sets up a player who owns a territory and has enough troops to place.
     * Runs 100 iterations, resetting troop counts each time to make sure the
     * result doesn't depend on leftover state from a prior iteration.</p>
     *
     * @return true if all 100 iterations return a valid result, false otherwise
     */
    private static boolean testValidReinforcement() {
        System.out.print("Testing valid reinforce: ");
        boolean passed = true;

        Player player = new Player("p1", Color.black);

        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        int troopsToPlace = 20;
        player.setTroopsToPlace(troopsToPlace);

        ReinforcementService reinforcementService = new ReinforcementService();

        for (int i = 0; i < 100; i++) {
            ValidationResult result = reinforcementService.reinforce(player, t1, troopsToPlace);
            if (!result.isValid()) {
                passed = false;
                System.out.println("During Iteration " + i + " reinforce returned false, on a valid reinforcement call");
            }

            // Reset state between iterations so each call starts from the same conditions
            player.setTroopsToPlace(troopsToPlace);
            t1.setTroopAmount(1);
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that a player can't reinforce a territory they don't own.
     *
     * <p>Creates two players and assigns the territory to the second one. Runs
     * 100 iterations confirming the result is always invalid. Also checks that
     * the territory's troop count never changes after a failed call.</p>
     *
     * @return true if all 100 iterations return an invalid result and the troop count stays unchanged, false otherwise
     */
    private static boolean testReinforcementWhenPlayerDoesNotOwnTerritory() {
        System.out.print("Testing reinforce when player doesn't own territory: ");
        boolean passed = true;

        Player player = new Player("p1", Color.black);
        Player otherPlayer = new Player("other", Color.blue);

        // Territory is owned by otherPlayer — reinforcement by player should always be rejected
        Territory t1 = new Territory(otherPlayer, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        int troopsToPlace = 20;
        player.setTroopsToPlace(troopsToPlace);

        ReinforcementService reinforcementService = new ReinforcementService();

        int originalTroopCount = t1.getTroopAmount();
        for (int i = 0; i < 100; i++) {
            ValidationResult result = reinforcementService.reinforce(player, t1, troopsToPlace);
            if (result.isValid()) {
                passed = false;
                System.err.println("During iteration " + i + " reinforce result returned true, when result should have been false");
            }

            // A failed reinforce should never mutate the territory's troop count
            if (t1.getTroopAmount() != originalTroopCount) {
                passed = false;
                System.err.println("During iteration " + i + " t1 troop amount was set to a new value after a failed iteration");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that trying to place 0 troops is rejected.
     *
     * <p>Passes 0 as the troop count to reinforce across 100 iterations.
     * Checks that the result is always invalid and that the territory's
     * troop count is never modified.</p>
     *
     * @return true if all 100 iterations return an invalid result and the troop count stays unchanged, false otherwise
     */
    private static boolean testReinforcementServiceWith0TroopsBeingPlaced() {
        System.out.print("Testing reinforce when player tries to place 0 troops: ");
        boolean passed = true;

        Player player = new Player("p1", Color.black);

        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        int troopsToPlace = 20;
        player.setTroopsToPlace(troopsToPlace);

        ReinforcementService reinforcementService = new ReinforcementService();

        int originalTroopCount = t1.getTroopAmount();
        for (int i = 0; i < 100; i++) {
            // Passing 0 — the service requires at least 1 troop to be placed
            ValidationResult result = reinforcementService.reinforce(player, t1, 0);
            if (result.isValid()) {
                passed = false;
                System.err.println("During iteration " + i + " reinforce result returned true, when result should have been false");
            }
            if (t1.getTroopAmount() != originalTroopCount) {
                passed = false;
                System.err.println("During iteration " + i + " t1 troop amount was set to a new value after a false reinforce result");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that a player can't place more troops than they have available.
     *
     * <p>Sets the player's available troops to 20 and tries to place 21 across
     * 100 iterations. Checks that every result is invalid and that the territory
     * is never modified.</p>
     *
     * @return true if all 100 iterations return an invalid result and the troop count stays unchanged, false otherwise
     */
    private static boolean testReinforceWithMoreTroopsThenPlayerHas() {
        System.out.print("Testing reinforce when player tries to place more troops than they have: ");
        boolean passed = true;

        Player player = new Player("p1", Color.black);

        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        int troopsToPlace = 20;
        player.setTroopsToPlace(troopsToPlace);

        ReinforcementService reinforcementService = new ReinforcementService();

        int originalTroopCount = t1.getTroopAmount();
        for (int i = 0; i < 100; i++) {
            // troopsToPlace + 1 intentionally exceeds the player's available troops
            ValidationResult result = reinforcementService.reinforce(player, t1, troopsToPlace + 1);
            if (result.isValid()) {
                passed = false;
                System.err.println("During iteration " + i + " reinforce result returned true, when result should have been false");
            }
            if (t1.getTroopAmount() != originalTroopCount) {
                passed = false;
                System.err.println("During iteration " + i + " t1 troop amount was set to a new value after a false reinforce result");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that passing null as the player is handled gracefully.
     *
     * <p>Passes null in place of a player across 100 iterations and checks that
     * the service returns an invalid result each time without throwing an exception.
     * Also verifies the territory's troop count is never changed.</p>
     *
     * @return true if all 100 iterations return an invalid result and the troop count stays unchanged, false otherwise
     */
    private static boolean testReinforceWithNullPlayer() {
        System.out.print("Testing reinforce when player passed in is null: ");
        boolean passed = true;

        Player player = new Player("p1", Color.black);

        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        int troopsToPlace = 20;
        player.setTroopsToPlace(troopsToPlace);

        ReinforcementService reinforcementService = new ReinforcementService();

        int originalTroopCount = t1.getTroopAmount();
        for (int i = 0; i < 100; i++) {
            // null player — service must not throw a NullPointerException
            ValidationResult result = reinforcementService.reinforce(null, t1, troopsToPlace + 1);
            if (result.isValid()) {
                passed = false;
                System.err.println("During iteration " + i + " reinforce result returned true, when result should have been false");
            }
            if (t1.getTroopAmount() != originalTroopCount) {
                passed = false;
                System.err.println("During iteration " + i + " t1 troop amount was set to a new value after a false reinforce result");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that passing null as the territory is handled gracefully.
     *
     * <p>Passes null in place of a territory across 100 iterations and checks
     * that the service returns an invalid result each time without throwing
     * an exception.</p>
     *
     * @return true if all 100 iterations return an invalid result, false otherwise
     */
    private static boolean testReinforceWithNullTerritory() {
        System.out.print("Testing reinforce when territory passed in is null: ");
        boolean passed = true;

        Player player = new Player("p1", Color.black);

        int troopsToPlace = 20;
        player.setTroopsToPlace(troopsToPlace);

        ReinforcementService reinforcementService = new ReinforcementService();

        for (int i = 0; i < 100; i++) {
            // null territory — service must not throw a NullPointerException
            ValidationResult result = reinforcementService.reinforce(player, null, troopsToPlace + 1);
            if (result.isValid()) {
                passed = false;
                System.err.println("During iteration " + i + " reinforce result returned true, when result should have been false");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that the minimum troop floor is enforced when a player owns very few territories.
     *
     * <p>A player with only 1 territory would calculate 0 base troops (1 / 3 = 0),
     * so the minimum floor of 3 should kick in. Checks that the player receives
     * exactly 3 troops after the calculation.</p>
     *
     * @return true if the player receives exactly 3 troops, false otherwise
     */
    private static boolean testCalculateReinforcementBaseAmount() {
        System.out.print("Testing calculateReinforcement base case: ");
        boolean passed = true;

        Player player = new Player("p1", Color.black);

        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        ArrayList<Territory> territories = new ArrayList<>();
        territories.add(t1);

        Region region = new Region(territories);

        ArrayList<Region> regions = new ArrayList<>();
        regions.add(region);

        TotalDominationWorld world = new TotalDominationWorld(regions);

        // 1 territory / 3 = 0, but the minimum floor is 3
        int expectedReturn = 3;

        ReinforcementService reinforcementService = new ReinforcementService();
        reinforcementService.calculateReinforcements(player, world);

        if (player.getTroopsToPlace() != expectedReturn) {
            passed = false;
            System.err.println("Calculate Reinforcements did not return the base amount value for a player");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that troop calculation is correct when no territories give a bonus.
     *
     * <p>Starts with 21 plain territories (no troop bonus) and checks the result
     * matches {@code territoryCount / 3}. Then adds 100 more one at a time,
     * rebuilding the world each iteration and verifying the formula holds throughout.</p>
     *
     * @return true if every calculation matches the expected formula, false otherwise
     */
    private static boolean testCalculateReinforcementWithNoTerritoryBonus() {
        final int territoryCountDivisor = 3;
        System.out.print("Testing calculateReinforcement when player owns no territories that give bonuses: ");
        boolean passed = true;

        Player player = new Player("p1", Color.black);

        ArrayList<Territory> territories = new ArrayList<>();

        // 21 plain territories — plain terrain has no troop bonus
        for (int i = 0; i < 21; i++) {
            Territory temp = new Territory(player, TerrainType.PLAIN.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
            territories.add(temp);
        }

        Region region = new Region(territories);

        ArrayList<Region> regions = new ArrayList<>();
        regions.add(region);

        TotalDominationWorld world = new TotalDominationWorld(regions);

        // 21 / 3 = 7, no terrain bonus — expected result is 7
        int expectedReturn = territories.size() / territoryCountDivisor;

        ReinforcementService reinforcementService = new ReinforcementService();
        reinforcementService.calculateReinforcements(player, world);

        if (player.getTroopsToPlace() != expectedReturn) {
            passed = false;
            System.err.println("Calculate Reinforcements did not return the proper value for a player with 21 territories");
        }

        // Add one territory per iteration and verify the formula holds at each new count
        for (int i = 0; i < 100; i++) {
            Territory temp = new Territory(player, TerrainType.PLAIN.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
            territories.add(temp);

            // Rebuild the world each iteration to reflect the updated territory list
            region = new Region(territories);
            regions = new ArrayList<>();
            regions.add(region);
            world = new TotalDominationWorld(regions);
            reinforcementService.calculateReinforcements(player, world);
            if (player.getTroopsToPlace() != territories.size() / territoryCountDivisor) {
                passed = false;
                System.err.println("Failed during looping iteration " + i);
                System.err.println("Calculate Reinforcements did not return the proper value for a player with " + territories.size() + " territories");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that terrain bonuses are correctly added on top of the base troop calculation.
     *
     * <p>Starts with 21 plain territories and tracks the cumulative terrain bonus manually.
     * Adds 100 more territories one at a time, rebuilding the world each iteration and
     * verifying the result matches {@code (territoryCount / 3) + terrainBonus} throughout.</p>
     *
     * @return true if every calculation matches the expected formula including terrain bonuses, false otherwise
     */
    private static boolean testCalculateReinforcementWithTerritoryBonuses() {
        final int territoryCountDivisor = 3;
        System.out.print("Testing calculateReinforcement when player owns territories that give bonuses: ");
        boolean passed = true;

        Player player = new Player("p1", Color.black);

        ArrayList<Territory> territories = new ArrayList<>();

        // Build an initial set of 21 plain territories
        for (int i = 0; i < 21; i++) {
            Territory temp = new Territory(player, TerrainType.PLAIN.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
            territories.add(temp);
        }

        Region region = new Region(territories);

        ArrayList<Region> regions = new ArrayList<>();
        regions.add(region);

        TotalDominationWorld world = new TotalDominationWorld(regions);

        // Sum the terrain bonus across all owned territories to get the initial expected bonus
        int terrainBonus = 0;
        for (Territory territory : world.getTerritoriesOwnedByPlayer(player)) {
            terrainBonus += territory.getTerrain().getTroopBonus();
        }

        int expectedReturn = territories.size() / territoryCountDivisor + terrainBonus;

        ReinforcementService reinforcementService = new ReinforcementService();
        reinforcementService.calculateReinforcements(player, world);

        if (player.getTroopsToPlace() != expectedReturn) {
            passed = false;
            System.err.println("Calculate Reinforcements did not return the proper value for a player with " + territories.size() + " that all have terrain Bonuses");
        }

        // Add one territory per iteration, accumulate its bonus, and verify the full formula each time
        for (int i = 0; i < 100; i++) {
            Territory temp = new Territory(player, TerrainType.PLAIN.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
            territories.add(temp);

            // Track the new territory's bonus in the running total
            terrainBonus += temp.getTerrain().getTroopBonus();

            // Rebuild the world to reflect the updated territory list
            region = new Region(territories);
            regions = new ArrayList<>();
            regions.add(region);
            world = new TotalDominationWorld(regions);
            reinforcementService.calculateReinforcements(player, world);
            if (player.getTroopsToPlace() != territories.size() / territoryCountDivisor + terrainBonus) {
                passed = false;
                System.err.println("Failed during looping iteration " + i);
                System.err.println("Calculate Reinforcements did not return the proper value for a player with " + territories.size() + " territories that all have terrain Bonuses");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }
}