package game;

import map.Territory;
import player.Player;
import terrain.TerrainType;

import java.awt.*;

/**
 * Runs manual test cases for the {@link FortifyService} class.
 *
 * <p>This test class verifies that fortification behaves correctly under a
 * variety of conditions, including valid moves, invalid ownership, moving
 * too many troops, moving zero troops, and checking whether fortification
 * paths through neighboring territories are valid.</p>
 *
 * <p>Each test method returns {@code true} if the test passes and
 * {@code false} if the test fails. The main method runs all tests and
 * reports the overall result to the console.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc and inline comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class TestFortifyService {

    /**
     * Runs all manual fortify service tests and prints the results.
     *
     * @param args command-line arguments, unused in this program
     */
    public static void main(String[] args) {
        // Tracks whether every test in this file passed.
        boolean passed = true;

        System.out.println("Testing Methods");

        // Run each test method and mark the file as failed if any one test fails.
        if (!testValidFortify()) passed = false;
        if (!testFortifyWithDifferentPlayer()) passed = false;
        if (!testFortifyMovingTooManyTroops()) passed = false;
        if (!testFortifyWithZeroTroopsMoved()) passed = false;
        if (!testFortifyThroughValidTerritoryConnection()) passed = false;
        if (!testFortifyThroughInValidTerritoryConnection()) passed = false;

        // Print overall test results after all test methods have been executed.
        if (passed) {
            System.out.println("All Tests Passed");
        } else {
            System.err.println("At least one Test Failed");
        }
    }

    /**
     * Tests valid fortification between two connected territories owned by the same player.
     *
     * <p>This test verifies that {@link FortifyService#fortify(Territory, Territory, int)}
     * allows troop movement when both territories are owned by the same player,
     * are directly connected, and the troop amount is valid.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testValidFortify() {
        System.out.print("Testing valid fortify: ");
        boolean passed = true;

        FortifyService fortifyService = new FortifyService();
        Player player = new Player("p1", Color.BLUE);

        // Create two connected territories
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // Make them neighbors so fortify is allowed
        t1.addToTerritoryNeighbors(t2);
        t2.addToTerritoryNeighbors(t1);

        int t1TroopAmount = 100;
        t1.setTroopAmount(t1TroopAmount);
        t2.setTroopAmount(1);

        // Test multiple troop movement values
        for (int i = 1; i < 100; i++) {
            ValidationResult result = fortifyService.fortify(t1, t2, i);
            if (!result.isValid()) {
                passed = false;
                System.err.println("During Looping iteration " + i + " Fortify result returned false, when it should have been true");
            }
            // Reset state after each iteration
            t1.setTroopAmount(t1TroopAmount);
            t2.setTroopAmount(1);
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests fortification between territories owned by different players.
     *
     * <p>This test verifies that {@link FortifyService#fortify(Territory, Territory, int)}
     * correctly rejects troop movement when the territories are owned by different players.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testFortifyWithDifferentPlayer() {
        boolean passed = true;
        System.out.print("Testing fortify with territories owned by different players: ");
        FortifyService fortifyService = new FortifyService();

        // Create two different players
        Player player = new Player("p1", Color.BLUE);
        Player player2 = new Player("p2", Color.GREEN);

        // Create two different players
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player2, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // Make them neighbors (connection exists, but ownership should still block)
        t1.addToTerritoryNeighbors(t2);
        t2.addToTerritoryNeighbors(t1);

        // Set troop amounts
        int t1TroopAmount = 100;
        t1.setTroopAmount(t1TroopAmount);
        t2.setTroopAmount(1);

        // Loop through multiple troop values
        for (int i = 1; i < 100; i++) {
            ValidationResult result = fortifyService.fortify(t1, t2, i);

            // Should always fail because ownership is different
            if (result.isValid()) {
                passed = false;
                System.err.println("During Looping iteration " + i + " Fortify result returned true, when it should have been false");
            }

            // Reset state after each iteration
            t1.setTroopAmount(t1TroopAmount);
            t2.setTroopAmount(1);
        }

        // Print result
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests fortification when too many troops are moved.
     *
     * <p>This test verifies that {@link FortifyService#fortify(Territory, Territory, int)}
     * rejects moves where the source territory would be left with zero or negative troops.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testFortifyMovingTooManyTroops() {
        boolean passed = true;
        System.out.print("Testing fortify with too many troops being moved: ");
        FortifyService fortifyService = new FortifyService();
        Player player = new Player("p1", Color.BLUE);

        // Create connected territories owned by same player
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // Make them neighbors
        t1.addToTerritoryNeighbors(t2);
        t2.addToTerritoryNeighbors(t1);

        int t1TroopAmount = 100;
        t1.setTroopAmount(t1TroopAmount);
        t2.setTroopAmount(1);

        // Try invalid troop amounts
        for (int i = 100; i < 200; i++) {
            ValidationResult result = fortifyService.fortify(t1, t2, i);

            // Should fail because you must leave at least 1 troop behind
            if (result.isValid()) {
                passed = false;
                System.err.println("During Looping iteration " + i + " Fortify result returned true, when it should have been false");
            }

            // Reset state
            t1.setTroopAmount(t1TroopAmount);
            t2.setTroopAmount(1);
        }

        // print results
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests fortification when zero troops are moved.
     *
     * <p>This test verifies that {@link FortifyService#fortify(Territory, Territory, int)}
     * rejects attempts to move zero troops.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testFortifyWithZeroTroopsMoved() {
        boolean passed = true;
        System.out.print("Testing fortify with 0 troops being moved: ");

        FortifyService fortifyService = new FortifyService();
        Player player = new Player("p1", Color.BLUE);

        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // Make them neighbors
        t1.addToTerritoryNeighbors(t2);
        t2.addToTerritoryNeighbors(t1);

        int t1TroopAmount = 100;
        t1.setTroopAmount(t1TroopAmount);
        t2.setTroopAmount(1);

        // Always attempt to move 0 troops
        for (int i = 1; i < 100; i++) {
            ValidationResult result = fortifyService.fortify(t1, t2, 0);

            // Should always fail
            if (result.isValid()) {
                passed = false;
                System.err.println("During Looping iteration " + i + " Fortify result returned true, when it should have been false");
            }

            // Reset state
            t1.setTroopAmount(t1TroopAmount);
            t2.setTroopAmount(1);
        }

        // print results
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests fortification through a valid chain of connected territories.
     *
     * <p>This test verifies that {@link FortifyService#fortify(Territory, Territory, int)}
     * allows movement through multiple connected territories owned by the same player.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testFortifyThroughValidTerritoryConnection() {
        boolean passed = true;
        System.out.print("Testing fortify between a chain of player owned territories: ");

        FortifyService fortifyService = new FortifyService();
        Player player = new Player("p1", Color.BLUE);

        // Create chain of territories owned by same player
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        Territory t4 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // Build connection chain
        t1.addToTerritoryNeighbors(t2);
        t2.addToTerritoryNeighbors(t1);
        t2.addToTerritoryNeighbors(t3);
        t3.addToTerritoryNeighbors(t2);
        t3.addToTerritoryNeighbors(t4);
        t4.addToTerritoryNeighbors(t3);

        int t1TroopAmount = 100;
        t1.setTroopAmount(t1TroopAmount);
        t2.setTroopAmount(1);

        // Attempt fortify across chain
        for (int i = 1; i < 100; i++) {
            ValidationResult result = fortifyService.fortify(t1, t4, i);

            // Should succeed due to valid path
            if (!result.isValid()) {
                passed = false;
                System.err.println("During Looping iteration " + i + " Fortify result returned false, when it should have been true");
            }

            // Reset state
            t1.setTroopAmount(t1TroopAmount);
            t2.setTroopAmount(1);
        }

        // print results
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests fortification through an invalid chain containing an enemy territory.
     *
     * <p>This test verifies that {@link FortifyService#fortify(Territory, Territory, int)}
     * rejects movement when the path includes a territory owned by another player.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testFortifyThroughInValidTerritoryConnection() {
        boolean passed = true;
        System.out.print("Testing fortify between a chain of different player owned territories: ");

        FortifyService fortifyService = new FortifyService();
        Player player = new Player("p1", Color.BLUE);
        Player player2 = new Player("p2", Color.BLUE);

        // Create chain with different player territory in the middle
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player2, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t4 = new Territory(player, TerrainType.DESERT.getTerrain(), 20, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // Build chain
        t1.addToTerritoryNeighbors(t2);
        t2.addToTerritoryNeighbors(t1);
        t2.addToTerritoryNeighbors(t3);
        t3.addToTerritoryNeighbors(t2);
        t3.addToTerritoryNeighbors(t4);
        t4.addToTerritoryNeighbors(t3);

        int t1TroopAmount = 100;
        t1.setTroopAmount(t1TroopAmount);
        t2.setTroopAmount(1);

        for (int i = 1; i < 100; i++) {
            ValidationResult result = fortifyService.fortify(t1, t4, i);

            // Should fail because path includes enemy territory
            if (result.isValid()) {
                passed = false;
                System.err.println("During Looping iteration " + i + " Fortify result returned true, when it should have been false");
            }

            // Reset state
            t1.setTroopAmount(t1TroopAmount);
            t2.setTroopAmount(1);
        }

        // print results
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }
}
