package game;

import map.*;
import player.Player;
import terrain.TerrainType;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Manual test suite for {@link GameLogic} in Battle Nations.
 *
 * <p>Tests core gameplay logic that lives in {@code GameLogic} directly,
 * separate from the individual service classes. Each test method is self-contained,
 * builds its own state via {@code generateGameLogic()}, and returns true or false.
 * The {@code main} method runs all tests and reports whether the suite passed or
 * failed overall.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 *
 */
public class TestGameLogic {

    /**
     * Runs all tests in the suite and prints the overall result.
     *
     * <p>Each test method is called in sequence. If any one of them fails,
     * the suite is marked as failed. Results are printed to stdout on pass
     * and stderr on fail.</p>
     *
     * @param args command-line arguments (not used)
     */
    public static void main(String[] args) {
        // Tracks whether every test in this file passed.
        boolean passed = true;

        System.out.println("Testing Methods");

        // Run each test method and mark the suite as failed if any individual test fails.

        if (!testChangePhaseMethod()) passed = false;
        if (!testIsGameOver()) passed = false;
        if (!testIsTerritoryPlayerOwned()) passed = false;

        // Print overall test results after all test methods have been executed.
        if (passed) {
            System.out.println("All Tests Passed");
        } else {
            System.err.println("At least one Test Failed");
        }
    }

    /**
     * Tests that the turn phase cycles correctly through all three phases.
     *
     * <p>Verifies the game starts in {@code REINFORCEMENT} and that each call to
     * {@code changePhase} transitions to the correct next phase. Runs 1000 iterations
     * to confirm the cycle holds consistently over many turns.</p>
     *
     * @return true if the phase always transitions correctly, false otherwise
     */
    private static boolean testChangePhaseMethod() {
        boolean passed = true;
        System.out.print("Testing Change Phase Method: ");

        GameLogic gameLogic = generateGameLogic();

        // Game should always start in the reinforcement phase
        if (gameLogic.getCurrentPhase() != TurnPhase.REINFORCEMENT) {
            passed = false;
            System.err.println("Initial turn phase was not set to reinforcement of initialization");
        }

        for (int i = 0; i < 1000; i++) {
            TurnPhase phaseBeforeChange = gameLogic.getCurrentPhase();
            gameLogic.changePhase();

            // Verify each transition follows the correct order
            if (phaseBeforeChange == TurnPhase.REINFORCEMENT) {
                if (gameLogic.getCurrentPhase() != TurnPhase.ATTACK) {
                    passed = false;
                    System.err.println("During iteration " + i + " changePhase failed to update from Reinforcement to Attack");
                }
            } else if (phaseBeforeChange == TurnPhase.ATTACK) {
                if (gameLogic.getCurrentPhase() != TurnPhase.FORTIFY) {
                    passed = false;
                    System.err.println("During iteration " + i + " changePhase failed to update from Attack to Fortify");
                }
            } else {
                if (gameLogic.getCurrentPhase() != TurnPhase.REINFORCEMENT) {
                    passed = false;
                    System.err.println("During iteration " + i + " changePhase failed to update from Fortify to Reinforcement");
                }
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that {@code isTerritoryPlayerOwned} correctly identifies ownership.
     *
     * <p>Checks that the method returns true for a territory owned by the current
     * player, and false for a territory owned by a different player.</p>
     *
     * @return true if both ownership checks return the correct result, false otherwise
     */
    private static boolean testIsTerritoryPlayerOwned() {
        boolean passed = true;
        System.out.print("Testing is Territory Player Owned: ");

        GameLogic gameLogic = generateGameLogic();

        // Get the current player and a territory they own
        Player currentPlayer = gameLogic.getCurrentPlayer();
        List<Territory> currentPlayerTerritories = gameLogic.getWorld().getTerritoriesOwnedByPlayer(currentPlayer);
        Territory ownedTerritory = currentPlayerTerritories.get(0);

        // Should return true — territory belongs to the current player
        if (!gameLogic.isTerritoryPlayerOwned(ownedTerritory)) {
            passed = false;
            System.err.println("isTerritoryPlayerOwned returned false for a territory the current player owns");
        }

        // Find a territory owned by a different player
        List<Territory> territories = gameLogic.getWorld().getAllTerritories();
        Territory enemyTerritory = null;
        for (Territory territory : territories) {
            if (!territory.getPlayer().equals(currentPlayer)) {
                enemyTerritory = territory;
                break;
            }
        }

        // Should return false — territory belongs to a different player
        if (gameLogic.isTerritoryPlayerOwned(enemyTerritory)) {
            passed = false;
            System.err.println("isTerritoryPlayerOwned returned true for a territory the current player does not own");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that {@code isGameOver} correctly detects win and non-win states.
     *
     * <p>First confirms the game is not over when territories are spread across
     * multiple players. Then transfers all territories to the current player and
     * verifies the game is correctly flagged as over.</p>
     *
     * @return true if both the non-win and win states are detected correctly, false otherwise
     */
    private static boolean testIsGameOver() {
        boolean passed = true;
        System.out.print("Testing isGameOver method: ");

        GameLogic gameLogic = generateGameLogic();

        // Game should not be over — territories are spread across all 6 players
        if (gameLogic.isGameOver()) {
            passed = false;
            System.err.println("Game was set as over while a total Domination world had multiple players owning territories");
        }

        // Winner should be null before anyone has won
        if (gameLogic.getWinner() != null) {
            passed = false;
            System.err.println("Winner was not null when the game has not yet been won");
        }

        // Transfer all territories to the current player to trigger a win
        for (Territory territory : gameLogic.getWorld().getAllTerritories()) {
            territory.setPlayer(gameLogic.getCurrentPlayer());
        }

        // Game should now be over — one player controls everything
        if (!gameLogic.isGameOver()) {
            passed = false;
            System.err.println("Game was not set as over, when a player owned all territories in a total domination");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Builds a standard {@link GameLogic} instance for use across all tests.
     *
     * <p>Creates 6 players and 6 regions, with each region containing 3 territories
     * all owned by the corresponding player. Returns a fully initialized
     * {@code GameLogic} backed by a {@link TotalDominationWorld}.</p>
     *
     * @return a fully constructed GameLogic instance ready for testing
     */
    private static GameLogic generateGameLogic() {
        ArrayList<Player> players = new ArrayList<>();
        Player player1 = new Player("p1", Color.BLUE);
        Player player2 = new Player("p2", Color.BLACK);
        Player player3 = new Player("p3", Color.RED);
        Player player4 = new Player("p4", Color.GREEN);
        Player player5 = new Player("p5", Color.ORANGE);
        Player player6 = new Player("p6", Color.MAGENTA);

        players.add(player1);
        players.add(player2);
        players.add(player3);
        players.add(player4);
        players.add(player5);
        players.add(player6);

        ArrayList<Region> regions = new ArrayList<>();

        // Create 6 regions, one per player
        for (int i = 0; i < 6; i++) {
            ArrayList<Territory> territories = new ArrayList<>();

            // Add 3 territories to each region, all owned by the corresponding player
            for (int j = 0; j < 3; j++) {
                Territory t1 = new Territory(players.get(i), TerrainType.DESERT.getTerrain(), 20,
                        new int[]{1, 2, 3, 4, 5, 6},
                        new int[]{1, 2, 3, 4, 5, 6}, false);
                territories.add(t1);
            }

            Region region = new Region(territories);
            regions.add(region);
        }

        TotalDominationWorld world = new TotalDominationWorld(regions);
        return new GameLogic(world, players, new AttackService(), new ReinforcementService(), new FortifyService());
    }
}