package game;

/**
 * Represents the phases of a player's turn in Battle Nations.
 *
 * <p>Each turn is divided into three phases: reinforcement, attack,
 * and fortify. The current phase determines which actions the player
 * is allowed to perform.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public enum TurnPhase {

    /**
     * Phase where players place reinforcement troops.
     */
    REINFORCEMENT,

    /**
     * Phase where players may attack enemy territories.
     */
    ATTACK,

    /**
     * Phase where players may move troops between owned territories.
     */
    FORTIFY
}
