package game;

/**
 * Represents the result of validating a game action.
 *
 * <p>This record stores whether an action is valid and provides a message
 * describing the outcome. It is used by game services to communicate
 * validation results and feedback to the caller.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public record ValidationResult(boolean isValid, String message) {

}