package startGUI;

import javax.swing.*;
import java.awt.*;

/**
 * A custom JPanel that displays a background image.
 *
 * <p>This panel is designed to scale a specified image to fill the entire panel.
 * It can be used to create visually appealing backgrounds for GUI screens such as
 * menus, settings pages, or maps.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author Max Montowski
 */
public class ImagePanel extends JPanel {

    /**
     * The image to be drawn as the background of this panel.
     */
    private final Image backgroundImage;

    /**
     * Constructs an ImagePanel with the specified image file path.
     *
     * @param path the file path to the image to display
     */
    public ImagePanel(String path) {
        backgroundImage = new ImageIcon(path).getImage();
    }

    /**
     * Paints the component by drawing the background image scaled to fit the panel size.
     *
     * @param g the Graphics context used for painting
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    }

}
