package startGUI;

import javax.swing.*;
import java.awt.*;

/**
 * Serves as the map selection page for the battle nations GUI.
 *
 * <p>
 * This class allows the user to choose between available maps by selecting
 * from image-based radio buttons. Once a map is selected, the user can proceed
 * to the player setup page. The selected map is stored in the setup data.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class MapChoicePage {

    /** The main panel displaying map options and controls. */
    private final JPanel mapChoicePanel;

    /** The parent JFrame that holds and displays the panel. */
    private JFrame parent;

    /** Stores the file path of the selected map. */
    private String mapLocation;

    /** Controller used for navigation and data sharing. */
    private StartController startController;

    /** Boolean used for checking if instruction pop up message should be shown. */
    private boolean stillShow;

    /** Groups map selection buttons to enforce a single selection. */
    private final ButtonGroup mapChoices;

    /** Radio button representing the first map option. */
    private final JRadioButton map1bt;

    /** Radio button representing the second map option. */
    private final JRadioButton map2bt;

    /** Button used to proceed to the next page after a map is selected. */
    private final JButton continueBt;

    /**
     * Constructs the MapChoicePage and initializes all UI components, including layout,
     * buttons, images, and event listeners.
     */
    public MapChoicePage() {
        // Creates the background panel with an image.
        mapChoicePanel = new ImagePanel("src/gameImages/OptionScreen.png");

        // Gets screen dimensions and configures layout.
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        mapChoicePanel.setLayout(null);
        mapChoicePanel.setBounds(0, 0, screen.width, screen.height);

        // Allows the message box to appear giving the user instructions.
        stillShow = true;

        // Creates and adds the screen title.
        JLabel title = createTitle(screen);
        mapChoicePanel.add(title);

        // Button to go back a page.
        JButton backBt = new JButton("Back");
        backBt.setBounds((int) screen.getWidth() / 2 - 210, (int) screen.getHeight() / 6 * 5, 200, 80);
        backBt.addActionListener(e -> {
            startController.makeSound();
            parent.remove(mapChoicePanel);
            startController.displayStartMenuPage();
        });
        mapChoicePanel.add(backBt);

        // Button to proceed after selecting a map.
        continueBt = new JButton("Continue");
        continueBt.setBounds((int) screen.getWidth() / 2 + 10, (int) screen.getHeight() / 6 * 5, 200, 80);

        // Sets it to false so cannot continue without selecting map.
        continueBt.setEnabled(false);

        // Proceeds only if a map has been selected.
        continueBt.addActionListener(e -> {
            startController.makeSound();
            startController.getGameSetUpData().setMap(mapLocation);
            startController.getDisplay().remove(mapChoicePanel);
            startController.displayPlayerPage();
        });

        // Adds the continue button to the panel.
        mapChoicePanel.add(continueBt);

        // Groups map selection buttons so only one can be selected.
        mapChoices = new ButtonGroup();

        // Loads and scales the first map image.
        ImageIcon map1 = new ImageIcon("src/gameImages/FunnyLandMapImage.jpg");
        Image map1Image = map1.getImage();
        Image rescaledImageMap1 = map1Image.getScaledInstance((int) screen.getWidth() / 4, (int) screen.getHeight() / 4, Image.SCALE_SMOOTH);

        // Creates a radio button with the map image.
        map1bt = new JRadioButton(new ImageIcon(rescaledImageMap1));
        map1bt.setBounds((int) screen.getWidth() / 8, (int) screen.getHeight() / 2, (int) screen.getWidth() / 4, (int) screen.getHeight() / 4);
        map1bt.setContentAreaFilled(false);
        map1bt.setBorderPainted(true);

        // Loads and scales the second map image.
        ImageIcon map2 = new ImageIcon("src/gameImages/GlenmouthMapImage.jpg");
        Image map2Image = map2.getImage();
        Image rescaledImageMap2 = map2Image.getScaledInstance((int) screen.getWidth() / 4, (int) screen.getHeight() / 4, Image.SCALE_SMOOTH);

        // Creates a radio button with the second map image.
        map2bt = new JRadioButton(new ImageIcon(rescaledImageMap2));
        map2bt.setBounds((int) screen.getWidth() / 8 * 5, (int) (screen.getHeight() / 2), (int) screen.getWidth() / 4, (int) screen.getHeight() / 4);
        map2bt.setContentAreaFilled(false);
        map2bt.setBorderPainted(true);

        // Adds buttons to the group and panel.
        mapChoices.add(map1bt);
        mapChoicePanel.add(map1bt);
        mapChoices.add(map2bt);
        mapChoicePanel.add(map2bt);

        // Handles selection of map 1.
        map1bt.addActionListener(e -> {
            startController.makeSound();
            map1bt.setBorder(BorderFactory.createLineBorder(Color.GREEN, 10));
            map2bt.setBorder(null);
            continueBt.setEnabled(true);
            mapLocation = "src/mapTextFiles/funny_land";
        });

        // Handles selection of map 2.
        map2bt.addActionListener(e -> {
            startController.makeSound();
            map2bt.setBorder(BorderFactory.createLineBorder(Color.GREEN, 10));
            map1bt.setBorder(null);
            continueBt.setEnabled(true);
            mapLocation = "src/mapTextFiles/glenmouth_map";
        });

        // Button that shuts program down when pressed.
        JButton closeButton = new JButton("X");
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setBounds(screen.width - 52, 2, 50, 50);
        closeButton.addActionListener(e -> {
            startController.makeSound();
            System.exit(0);
        });
        mapChoicePanel.add(closeButton);

        // Button that minimizes program when pressed.
        JButton minimizeButton = new JButton("-");
        minimizeButton.setFont(new Font("Arial", Font.BOLD, 14));
        minimizeButton.setBounds(screen.width - 104, 2, 50, 50);
        minimizeButton.addActionListener(e -> {
            startController.makeSound();
            parent.setState(Frame.ICONIFIED);
        });
        mapChoicePanel.add(minimizeButton);

    }

    /**
     * Creates and configures the title label for the map selection page.
     *
     * <p>
     * The label text is dynamically resized to ensure it fits within the screen width.
     * The font size is reduced iteratively until the rendered text width is within
     * an acceptable range based on the provided screen dimensions.
     * </p>
     *
     * @param screen the screen dimensions used to calculate size and positioning
     * @return a configured {@link JLabel} representing the page title
     */
    private static JLabel createTitle(Dimension screen) {
        // Creates the label.
        JLabel title = new JLabel("MAP SELECTION");
        title.setForeground(Color.WHITE);
        title.setOpaque(true);
        title.setBackground(Color.BLACK);

        // Creates several variables used for resizing the text font.
        boolean tooBig = true;
        int fontSize = 100;
        int textBuffer = screen.width / 4;
        Dimension titleSize = null;

        // Continues shrinking the font size until it fits within the text box with a buffer.
        while (tooBig) {
            title.setFont(new Font("Arial", Font.BOLD, fontSize));
            titleSize = title.getPreferredSize();

            // Checks to see if it's too big, if it is, shrinks the font by 1, otherwise it stops the while loop.
            if (titleSize.width > screen.width - textBuffer) {
                fontSize--;
            } else {
                tooBig = false;
            }
        }

        // Sets the bounds of the title before returning it.
        title.setBounds(screen.width / 2 - titleSize.width / 2 - 5, screen.height / 10, titleSize.width + 10, titleSize.height);
        return title;
    }

    /**
     * Adds the map choice panel to the main JFrame display.
     *
     * <p>
     * This method also optionally displays an instructional popup explaining
     * how to select a map. If the user selects "Don't show again",
     * the popup will not be shown in future calls.
     * </p>
     *
     * @param startController the controller managing GUI navigation.
     */
    public void addMapChoicePage(StartController startController) {
        // Adds the map choice panel to the main JFrame and repaints it.
        this.startController = startController;
        this.parent = startController.getDisplay();
        parent.add(mapChoicePanel);
        parent.repaint();

        // Checks to see if the instruction box should be displayed.
        if (stillShow) {
            JCheckBox checkBox = new JCheckBox("Don't show again this session");
            Object[] message = {"Please click on a map to select it to be the map used for your game.\n" +
                    "If you wish to change it simply click on the new map of your choice.", checkBox};

            JOptionPane.showMessageDialog(parent, message, "Map Choice", JOptionPane.INFORMATION_MESSAGE);
            startController.makeSound();
            if (checkBox.isSelected()) {
                stillShow = false;
            }
        }
    }

    /**
     * Resets the map selection UI to its default state.
     *
     * <p>
     * This includes:
     * <ul>
     *   <li>Clearing any selected map</li>
     *   <li>Removing selection borders</li>
     *   <li>Disabling the continue button</li>
     * </ul>
     * <p>
     * This method is called if a game has been completed and the players return to the start menu.
     * </p>
     */
    public void reset() {
        mapChoices.clearSelection();
        map1bt.setBorder(null);
        map2bt.setBorder(null);
        continueBt.setEnabled(false);
    }
}
