package startGUI;

import javax.swing.*;
import java.awt.*;

/**
 * Serves as the map selection page for the battle nations GUI.
 *
 * <p>
 * This class allows the user to choose between available maps by selecting
 * from image-based radio buttons. Once a map is selected, the user can proceed
 * to the player setup page. The selected map is stored in the setup data.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class MapChoicePage {

    /**
     * The main panel displaying map options and controls.
     */
    private final JPanel mapChoicePanel;

    /**
     * The parent JFrame that holds and displays the panel.
     */
    private JFrame parent;

    /**
     * Stores the file path of the selected map.
     */
    private String mapLocation;

    /**
     * Controller used for navigation and data sharing.
     */
    private StartController startController;

    /**
     * Constructs the MapChoicePage and initializes UI components.
     */
    public MapChoicePage() {
        // Creates the background panel with an image.
        mapChoicePanel = new ImagePanel("src/gameImages/OptionScreen.png");

        // Gets screen dimensions and configures layout.
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        mapChoicePanel.setLayout(null);
        mapChoicePanel.setBounds(0, 0, screen.width, screen.height);

        // Button to proceed after selecting a map.
        JButton continueBt = new JButton("Continue");
        continueBt.setBounds((int) screen.getWidth() / 2 - 100, (int) screen.getHeight() / 6 * 5, 200, 80);

        // Sets it to false so cannot continue without selecting map.
        continueBt.setEnabled(false);

        // Proceeds only if a map has been selected.
        continueBt.addActionListener(e -> {
            startController.getGameSetUpData().setMap(mapLocation);
            startController.getDisplay().remove(mapChoicePanel);
            startController.displayGameSetupPage();
        });

        // Adds the continue button to the panel.
        mapChoicePanel.add(continueBt);

        // Groups map selection buttons so only one can be selected.
        ButtonGroup mapChoices = new ButtonGroup();

        // Loads and scales the first map image.
        ImageIcon map1 = new ImageIcon("src/gameImages/FunnyLandMapImage.jpg");
        Image map1Image = map1.getImage();
        Image rescaledImageMap1 = map1Image.getScaledInstance((int) screen.getWidth() / 4, (int) screen.getHeight() / 4, Image.SCALE_SMOOTH);

        // Creates a radio button with the map image.
        JRadioButton map1bt = new JRadioButton(new ImageIcon(rescaledImageMap1));
        map1bt.setBounds((int) screen.getWidth() / 8, (int) screen.getHeight() / 2, (int) screen.getWidth() / 4, (int) screen.getHeight() / 4);
        map1bt.setContentAreaFilled(false);
        map1bt.setBorderPainted(true);

        // Loads and scales the second map image.
        ImageIcon map2 = new ImageIcon("src/gameImages/GlenmouthMapImage.jpg");
        Image map2Image = map2.getImage();
        Image rescaledImageMap2 = map2Image.getScaledInstance((int) screen.getWidth() / 4, (int) screen.getHeight() / 4, Image.SCALE_SMOOTH);

        // Creates a radio button with the second map image.
        JRadioButton map2bt = new JRadioButton(new ImageIcon(rescaledImageMap2));
        map2bt.setBounds((int) screen.getWidth() / 8 * 5, (int) (screen.getHeight() / 2), (int) screen.getWidth() / 4, (int) screen.getHeight() / 4);
        map2bt.setContentAreaFilled(false);
        map2bt.setBorderPainted(true);

        // Adds buttons to the group and panel.
        mapChoices.add(map1bt);
        mapChoicePanel.add(map1bt);
        mapChoices.add(map2bt);
        mapChoicePanel.add(map2bt);

        // Handles selection of map 1.
        map1bt.addActionListener(e -> {
            map1bt.setBorder(BorderFactory.createLineBorder(Color.GREEN, 10));
            map2bt.setBorder(null);
            continueBt.setEnabled(true);
            mapLocation = "src/mapTextFiles/funny_land";
        });

        // Handles selection of map 2.
        map2bt.addActionListener(e -> {
            map2bt.setBorder(BorderFactory.createLineBorder(Color.GREEN, 10));
            map1bt.setBorder(null);
            continueBt.setEnabled(true);
            mapLocation = "src/mapTextFiles/glenmouth_map";
        });

        JButton closeButton = new JButton("X");
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setBounds(screen.width - 52, 2, 50, 50);
        closeButton.addActionListener(e -> System.exit(0));
        mapChoicePanel.add(closeButton);

        JButton minimizeButton = new JButton("-");
        minimizeButton.setFont(new Font("Arial", Font.BOLD, 14));
        minimizeButton.setBounds(screen.width - 104, 2, 50, 50);
        minimizeButton.addActionListener(e -> parent.setState(Frame.ICONIFIED));
        mapChoicePanel.add(minimizeButton);

    }

    /**
     * Adds the map choice panel to the main JFrame display.
     *
     * @param startController the controller managing GUI navigation.
     */
    public void addMapChoicePage(StartController startController) {
        this.startController = startController;
        this.parent = startController.getDisplay();
        parent.add(mapChoicePanel);
        parent.repaint();
    }
}
