package startGUI; //rename packages

import map.MapLoaderService;
import map.Territory;

import javax.swing.*;
import java.awt.*;

/**
 * Represents the main map display in Battle Nations.
 *
 * <p>This class handles loading a map from a file, generating territories
 * as hexagonal tiles, and displaying them within a GUI. Each territory
 * corresponds to a specific terrain type such as mountain, desert, or city.</p>
 *
 * <p>Territories are positioned and scaled dynamically to fit the screen
 * while maintaining a hexagonal grid layout.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author Max Montowski
 */
public class MapDisplay {

    /**
     * Width of the display, based on screen size.
     */
    private final int displayWidth;

    /**
     * Height of the display, based on screen size.
     */
    private final int displayHeight;

    /**
     * Panel that renders the map and its territories.
     */
    private final MapPanel mapDisplay;

    /**
     * The screen dimensions.
     */
    private Dimension screen;

    /**
     * 2D array of territories representing the map grid.
     */
    private Territory[][] territories;

    /**
     * Controller used to manage GUI interactions.
     */
    private StartController startController;

    /**
     * Parent JFrame that contains the map display.
     */
    private JFrame parent;

    MapLoaderService loader;

    /**
     * Constructs a MapDisplay object, initializes the screen size,
     * loads the map file, and creates the territory grid.
     */
    public MapDisplay() {
        screen = Toolkit.getDefaultToolkit().getScreenSize();
        displayWidth = screen.width;
        displayHeight = screen.height;
        loader = new MapLoaderService();
        territories = loader.loadTerritories("src/mapTextFiles/funny_land", screen);
        // Initialize the panel that displays the map
        mapDisplay = new MapPanel(territories);
        mapDisplay.setLayout(null);
        mapDisplay.setBounds(0, 0, displayWidth, displayHeight);
        mapDisplay.repaint();
    }

    /**
     * Adds the map display panel to the parent JFrame controlled by StartController.
     *
     * @param startController the controller managing the GUI
     */
    public void addMapDisplay(StartController startController) {
        this.startController = startController;
        this.parent = startController.getDisplay();
        parent.add(mapDisplay);
        parent.repaint();
    }
}