package startGUI; //rename packages

import map.TerrainType;
import map.Territory;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 * Represents the main map display in Battle Nations.
 *
 * <p>This class handles loading a map from a file, generating territories
 * as hexagonal tiles, and displaying them within a GUI. Each territory
 * corresponds to a specific terrain type such as mountain, desert, or city.</p>
 *
 * <p>Territories are positioned and scaled dynamically to fit the screen
 * while maintaining a hexagonal grid layout.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author Max Montowski
 */
public class MapDisplay {

    /**
     * Width of the display, based on screen size.
     */
    private final int displayWidth;

    /**
     * Height of the display, based on screen size.
     */
    private final int displayHeight;

    /**
     * Panel that renders the map and its territories.
     */
    private final MapPanel mapDisplay;

    /**
     * The screen dimensions.
     */
    private Dimension screen;

    /**
     * 2D array of territories representing the map grid.
     */
    private Territory[][] territories;

    /**
     * Controller used to manage GUI interactions.
     */
    private StartController startController;

    /**
     * Parent JFrame that contains the map display.
     */
    private JFrame parent;

    /**
     * Constructs a MapDisplay object, initializes the screen size,
     * loads the map file, and creates the territory grid.
     */
    public MapDisplay() {
        screen = Toolkit.getDefaultToolkit().getScreenSize();
        displayWidth = screen.width;
        displayHeight = screen.height;

        // Load map from file and generate territories
        makeTerritories("src/mapTextFiles/Map1");

        // Initialize the panel that displays the map
        mapDisplay = new MapPanel(territories);
        mapDisplay.setLayout(null);
        mapDisplay.setBounds(0, 0, displayWidth, displayHeight);
        mapDisplay.repaint();
    }

    /**
     * Reads a map file and generates territories as a hexagonal grid.
     *
     * <p>The map file should contain the number of rows and columns followed
     * by terrain type identifiers ('M' for mountain, 'D' for desert, 'C' for city)
     * for each hex tile.</p>
     *
     * @param fileName the path to the map file
     */
    public void makeTerritories(String fileName) {
        File mapFile = new File(fileName);
        int numberRows;
        int numberColumns;
        String[][] terrainTypes;
        Scanner fileReader = null;

        try {
            fileReader = new Scanner(mapFile);
            numberRows = fileReader.nextInt();
            numberColumns = fileReader.nextInt();
            terrainTypes = new String[numberRows][numberColumns];

            // Read terrain types from file
            for (int i = 0; i < numberRows; i++) {
                int alternator = (i % 2 != 0) ? 1 : 0;
                for (int j = 0; j < numberColumns - alternator; j++) {
                    terrainTypes[i][j] = fileReader.next();
                }
            }
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }

        // Calculate hex size based on screen dimensions
        double angleRadians = Math.toRadians(60);
        double cosValue = Math.cos(angleRadians);
        double sinValue = Math.sin(angleRadians);
        double length1 = (screen.getWidth() / (2 * numberColumns)) / (cosValue + 1);
        double length2 = (screen.getHeight() / (sinValue * (numberRows + 1)));
        double length = Math.min(length1, length2);

        // Starting coordinates for hex grid
        double xLocation = 0;
        double yLocation = sinValue * length;

        territories = new Territory[numberRows][numberColumns];
        double[][] coordinates = new double[6][2];

        // Generate hexagonal territories
        for (int i = 0; i < numberRows; i++) {
            int alternator = (i % 2 != 0) ? 1 : 0;
            xLocation = (alternator == 0) ? 0 : cosValue * length + length;

            for (int j = 0; j < numberColumns - alternator; j++) {
                // Compute hexagon vertices
                coordinates[0][0] = xLocation;
                coordinates[1][0] = cosValue * length + xLocation;
                coordinates[2][0] = coordinates[1][0] + length;
                coordinates[3][0] = cosValue * length + coordinates[2][0];
                coordinates[4][0] = coordinates[2][0];
                coordinates[5][0] = coordinates[1][0];

                coordinates[0][1] = yLocation;
                coordinates[1][1] = yLocation - sinValue * length;
                coordinates[2][1] = coordinates[1][1];
                coordinates[3][1] = coordinates[0][1];
                coordinates[4][1] = yLocation + sinValue * length;
                coordinates[5][1] = coordinates[4][1];

                int[] xPoints = new int[6];
                int[] yPoints = new int[6];
                for (int k = 0; k < 6; k++) {
                    xPoints[k] = (int) Math.round(coordinates[k][0]);
                    yPoints[k] = (int) Math.round(coordinates[k][1]);
                }

                // Assign terrain type to hex
                switch (terrainTypes[i][j]) {
                    case "M":
                        territories[i][j] = new Territory(TerrainType.MOUNTAIN.getTerrain(), xPoints, yPoints);
                        break;
                    case "D":
                        territories[i][j] = new Territory(TerrainType.DESERT.getTerrain(), xPoints, yPoints);
                        break;
                    case "C":
                        territories[i][j] = new Territory(TerrainType.CITY.getTerrain(), xPoints, yPoints);
                        break;
                    case "W":
                        territories[i][j] = new Territory(TerrainType.WATER.getTerrain(), xPoints, yPoints);
                        break;
                }

                // Move to next hex horizontally
                xLocation += cosValue * length * 2 + length * 2;
            }

            // Move to next hex row
            yLocation += sinValue * length;
        }
    }

    /**
     * Adds the map display panel to the parent JFrame controlled by StartController.
     *
     * @param startController the controller managing the GUI
     */
    public void addMapDisplay(StartController startController) {
        this.startController = startController;
        this.parent = startController.getDisplay();
        parent.add(mapDisplay);
        parent.repaint();
    }
}