package startGUI;

import player.Player;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 * Serves as the player setup page for the battle nations GUI.
 *
 * <p>
 * This class allows users to create players by entering a name and selecting a color.
 * Players are displayed in a list, and the user can proceed once at least two valid
 * players have been added. Validation ensures unique names, unique colors, and a
 * maximum of six players.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class PlayerPage {

    /** Background panel that holds all UI components. */
    private final ImagePanel playerCreationPanel;

    /** Text field for entering the player's name. */
    private final JTextField playerName;

    /** Dropdown menu for selecting a player's color. */
    private final JComboBox<String> playerColor;

    /** Button used to proceed to the next step (start game setup). */
    private final JButton continueBt;

    /** Model storing player display strings for the list. */
    private final DefaultListModel<String> playerListModel;

    /** Internal list storing Player objects. */
    private final ArrayList<Player> players;

    /** Parent JFrame that displays the panel. */
    private JFrame parent;

    /** Controller used for navigation and data sharing. */
    private StartController startController;

    /** List component displaying all created players. */
    private final JList<String> playerList;

    /** Button used to remove the currently selected player from the list. */
    private final JButton removePlayer;

    /**
     * Determines whether the instruction popup should be shown.
     * Set to false if the user selects "Don't show again".
     */
    private boolean stillShow;

    /**
     * Constructs the PlayerPage and initializes all GUI components used for player creation.
     *
     * <p>
     * This includes setting up the background panel, input fields, buttons, player list,
     * and all event listeners required for adding, removing, and managing players.
     * </p>
     */
    public PlayerPage() {
        // Initializes the player list.
        players = new ArrayList<>();

        // Creates the background panel with an image.
        playerCreationPanel = new ImagePanel("src/gameImages/OptionScreen.png");

        // Gets screen size and configures panel layout.
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        playerCreationPanel.setLayout(null);
        playerCreationPanel.setBounds(0, 0, screen.width, screen.height);

        // Allows the message box to appear giving the user instructions.
        stillShow = true;

        // Creates and positions the page title.
        JLabel title = createTitle(screen);
        playerCreationPanel.add(title);

        // Text field for entering player names.
        playerName = new JTextField();
        int formattingBuffer = 5;
        playerName.setBounds(screen.width / 2 - screen.width / 8 - formattingBuffer, screen.height * 3 / 10, screen.width / 8, 30);
        playerCreationPanel.add(playerName);

        // Label for entering player names.
        JLabel nameLabel = new JLabel("Player Name:");
        nameLabel.setOpaque(true);
        nameLabel.setBackground(Color.BLACK);
        nameLabel.setForeground(Color.WHITE);
        nameLabel.setFont(new Font("Arial", Font.BOLD, 18));
        Dimension nameLabelSize = nameLabel.getPreferredSize();
        nameLabel.setBounds(screen.width / 2 - screen.width / 8 - 2 * formattingBuffer - nameLabelSize.width, screen.height * 3 / 10, nameLabelSize.width, 30);
        playerCreationPanel.add(nameLabel);

        // Label for entering player colors.
        JLabel colorLabel = new JLabel("Player Color:");
        colorLabel.setOpaque(true);
        colorLabel.setBackground(Color.BLACK);
        colorLabel.setForeground(Color.WHITE);
        colorLabel.setFont(new Font("Arial", Font.BOLD, 18));
        Dimension colorLabelSize = colorLabel.getPreferredSize();
        colorLabel.setBounds(screen.width / 2 + formattingBuffer, screen.height * 3 / 10, colorLabelSize.width, 30);
        playerCreationPanel.add(colorLabel);

        // Dropdown list of available player colors.
        String[] colorList = {"None", "Red", "Cyan", "Green", "Yellow", "Magenta", "Orange"};
        playerColor = new JComboBox<>(colorList);
        playerColor.setSelectedIndex(0);
        playerColor.setBounds(screen.width / 2 + 2 * formattingBuffer + colorLabelSize.width, screen.height * 3 / 10, screen.width / 8, 30);
        playerCreationPanel.add(playerColor);

        // Button to add a player using the provided name and color.
        JButton addPlayer = new JButton("Add");
        addPlayer.setFont(new Font("Arial", Font.BOLD, 18));
        addPlayer.setBounds(screen.width / 2 - screen.width / 8, screen.height * 4 / 10, screen.width / 8, 40);
        addPlayer.addActionListener(e -> {
            startController.makeSound();
            addPlayer();
        });
        playerCreationPanel.add(addPlayer);

        // Button to remove a player based on the selected list index.
        removePlayer = new JButton("Remove");
        removePlayer.setFont(new Font("Arial", Font.BOLD, 18));
        removePlayer.setBounds(screen.width / 2 + formattingBuffer, screen.height * 4 / 10, screen.width / 8, 40);
        removePlayer.addActionListener(e -> {
            startController.makeSound();
            removePlayer();
        });
        removePlayer.setEnabled(false);
        playerCreationPanel.add(removePlayer);

        // Model and list for displaying added players.
        playerListModel = new DefaultListModel<>();

        // List that holds all player objects
        playerList = new JList<>(playerListModel);
        playerList.addListSelectionListener(e -> {
            if (playerList.getSelectedIndex() >= 0) {
                startController.makeSound();
                removePlayer.setEnabled(true);
            }
        });

        // Scroll pane to contain the player list.
        JScrollPane scroll = new JScrollPane(playerList);
        scroll.setBounds(screen.width / 2 - screen.width / 8, screen.height * 9 / 20 + formattingBuffer, screen.width / 4, screen.height * 9 / 12 - screen.height * 9 / 20 - formattingBuffer);
        playerCreationPanel.add(scroll);

        // Button to go back a page
        JButton backBt = new JButton("Back");
        backBt.setBounds(screen.width / 2 - screen.width / 8 - formattingBuffer, screen.height * 5 / 6, screen.width / 8, 80);
        backBt.addActionListener(e -> {
            startController.makeSound();
            parent.remove(playerCreationPanel);
            startController.displayMapChoicePage();
        });
        playerCreationPanel.add(backBt);

        // Button to proceed to the next setup step.
        continueBt = new JButton("Continue");
        continueBt.setBounds(screen.width / 2 + formattingBuffer, screen.height * 5 / 6, screen.width / 8, 80);

        // Initially disabled until at least two players are added.
        continueBt.setEnabled(false);

        // Stores players and transitions to the next page.
        continueBt.addActionListener(e -> {
            startController.makeSound();
            startController.getGameSetUpData().setPlayers(players);
            parent.remove(playerCreationPanel);
            startController.displaySetUpOptionsPage();
        });
        playerCreationPanel.add(continueBt);

        // Button that shuts program down when pressed.
        JButton closeButton = new JButton("X");
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setBounds(screen.width - 52, 2, 50, 50);
        closeButton.addActionListener(e -> {
            startController.makeSound();
            System.exit(0);
        });
        playerCreationPanel.add(closeButton);

        // Button that minimizes program when pressed.
        JButton minimizeButton = new JButton("-");
        minimizeButton.setFont(new Font("Arial", Font.BOLD, 14));
        minimizeButton.setBounds(screen.width - 104, 2, 50, 50);
        minimizeButton.addActionListener(e -> {
            startController.makeSound();
            parent.setState(Frame.ICONIFIED);
        });
        playerCreationPanel.add(minimizeButton);
    }

    /**
     * Creates and configures the title label for the player page.
     *
     * <p>
     * The label text is dynamically resized to ensure it fits within the screen width.
     * The font size is reduced iteratively until the rendered text width is within
     * an acceptable range based on the provided screen dimensions.
     * </p>
     *
     * @param screen the screen dimensions used to calculate size and positioning
     * @return a configured {@link JLabel} representing the page title
     */
    private static JLabel createTitle(Dimension screen) {
        // Creates the label.
        JLabel title = new JLabel("PLAYER CREATION");
        title.setForeground(Color.WHITE);
        title.setOpaque(true);
        title.setBackground(Color.BLACK);

        // Creates several variables used for resizing the text font.
        boolean tooBig = true;
        int fontSize = 100;
        int textBuffer = screen.width / 2;
        Dimension titleSize = null;

        // Continues shrinking the font size until it fits within the text box with a buffer.
        while (tooBig) {
            title.setFont(new Font("Arial", Font.BOLD, fontSize));
            titleSize = title.getPreferredSize();

            // Checks to see if it's too big, if it is, shrinks the font by 1, otherwise it stops the while loop.
            if (titleSize.width > screen.width - textBuffer) {
                fontSize--;
            } else {
                tooBig = false;
            }
        }

        // Sets the bounds of the title before returning it.
        title.setBounds(screen.width / 2 - titleSize.width / 2 - 5, screen.height / 10, titleSize.width + 10, titleSize.height);
        return title;
    }

    /**
     * Adds the player setup panel to the main JFrame.
     *
     * <p>
     * This method also optionally displays an instructional popup explaining
     * how to create a player. If the user selects "Don't show again",
     * the popup will not be shown in future calls.
     * </p>
     *
     * @param startController the controller managing GUI navigation.
     */
    public void addPlayerPage(StartController startController) {
        // Adds the setup options panel to the main JFrame and repaints it.
        this.startController = startController;
        this.parent = startController.getDisplay();
        parent.add(playerCreationPanel);
        parent.repaint();

        // Checks to see if the instruction box should be displayed.
        if (stillShow) {
            JCheckBox checkBox = new JCheckBox("Don't show again this session");
            Object[] message = {"Welcome to the Player Creation Page.\n" +
                    "To create a player, enter a name shorter than 20 characters into the text box,\n" +
                    "select a color from the drop down list, and then click add, to add player.\n" +
                    "To remove a player, simply click on their name in the list, and then click remove.", checkBox};

            JOptionPane.showMessageDialog(parent, message, "Player Creation", JOptionPane.INFORMATION_MESSAGE);

            startController.makeSound();
            if (checkBox.isSelected()) {
                stillShow = false;
            }
        }
    }

    /**
     * Handles adding a player after validating input fields.
     */
    private void addPlayer() {
        // Gets the information from the player creation fields
        String name = playerName.getText().trim();
        String color = (String) playerColor.getSelectedItem();
        Color playersColor = null;
        String errorMessage = "";

        // Checks to see which color was selected
        switch (color) {
            case "Red":
                playersColor = Color.RED;
                break;
            case "Cyan":
                playersColor = Color.CYAN;
                break;
            case "Green":
                playersColor = Color.GREEN;
                break;
            case "Yellow":
                playersColor = Color.YELLOW;
                break;
            case "Magenta":
                playersColor = Color.MAGENTA;
                break;
            case "Orange":
                playersColor = new Color(215, 86, 36);
                break;
            default:
                errorMessage += "Please select a player color.\n";
        }

        // Limits total players to 6.
        if (players.size() >= 6) {
            JOptionPane.showMessageDialog(parent, "Max 6 players.");
            return;
        }

        // Validates that the name is not empty.
        if (name.isEmpty()) {
            errorMessage += "Please enter a player name. \n";
        }

        // Ensures no duplicate player names.
        for (Player p : players) {
            if (p.getName().equalsIgnoreCase(name)) {
                errorMessage += "The name: " + name + " is already in use.\n";
            }
        }

        // Ensures the name is shorter than 20 characters.
        if (name.length() > 20) {
            errorMessage += "Name is " + name.length() + " characters long, \nnames must be shorter than 20 characters.";
        }

        // Only shows the error message if there was something wrong with the information given.
        if (!errorMessage.isEmpty()) {
            JOptionPane.showMessageDialog(parent, errorMessage);
            return;
        }

        // Adds the new player and updates the display list.
        players.add(new Player(name, playersColor, color));
        playerListModel.addElement("Player: " + name + " | Color: " + color);
        playerColor.removeItem(color);

        // Clears Color selection back to None.
        playerColor.setSelectedIndex(0);

        // Clears the input field.
        playerName.setText("");

        // Enables continue button if at least two players exist.
        if (players.size() >= 2) {
            continueBt.setEnabled(true);
        }
    }

    /**
     * Removes the selected player from the player list.
     *
     * <p>
     * This method updates both the internal player array and the display list.
     * It also restores the removed player's color back into the dropdown menu.
     * </p>
     */
    private void removePlayer() {
        int playerLocation = playerList.getSelectedIndex();
        Player playerToRemove = players.remove(playerLocation);
        playerListModel.remove(playerLocation);
        playerColor.addItem(playerToRemove.getColorName());
        removePlayer.setEnabled(false);

        if (players.size() < 2) {
            continueBt.setEnabled(false);
        }
    }

    /**
     * Resets the player creation page back to its default state.
     *
     * <p>
     * This clears all player data, resets the input fields, restores the color
     * dropdown, and disables the continue and remove buttons.
     * </p>
     */
    public void reset() {
        playerName.setText("");
        String[] colorList = {"None", "Red", "Cyan", "Green", "Yellow", "Magenta", "Orange"};
        playerColor.removeAllItems();
        for (String s : colorList) {
            playerColor.addItem(s);
        }
        continueBt.setEnabled(false);
        removePlayer.setEnabled(false);
        players.clear();
        playerListModel.clear();
    }
}