package startGUI;

import player.Player;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 * Serves as the player setup page for the battle nations GUI.
 *
 * <p>
 * This class allows users to create players by entering a name and selecting a color.
 * Players are displayed in a list, and the user can proceed once at least two valid
 * players have been added. Validation ensures unique names, unique colors, and a
 * maximum of six players.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class PlayerPage {

    /**
     * Background panel that holds all UI components.
     */
    private final ImagePanel gameSetupPanel;

    /**
     * Text field for entering the player's name.
     */
    private final JTextField playerName;

    /**
     * Dropdown menu for selecting a player's color.
     */
    private final JComboBox<String> playerColor;

    /**
     * Button used to proceed to the next step (start game setup).
     */
    private final JButton startGame;

    /**
     * Model storing player display strings for the list.
     */
    private final DefaultListModel<String> playerListModel;

    /**
     * Internal list storing Player objects.
     */
    private final ArrayList<Player> players;

    /**
     * Parent JFrame that displays the panel.
     */
    private JFrame parent;

    /**
     * Controller used for navigation and data sharing.
     */
    private StartController startController;

    private JList<String> playerList;

    private final JButton removePlayer;

    /**
     * Constructs the PlayerPage and initializes all GUI components.
     */
    public PlayerPage() {
        // Initializes the player list.
        players = new ArrayList<>();

        // Creates the background panel with an image.
        gameSetupPanel = new ImagePanel("src/gameImages/OptionScreen.png");

        // Gets screen size and configures panel layout.
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        gameSetupPanel.setLayout(null);
        gameSetupPanel.setBounds(0, 0, screen.width, screen.height);

        // Creates and positions the page title.
        JLabel title = new JLabel("PLAYER CREATION");
        boolean toBig = true;
        int fontSize = 100;
        int textBuffer = screen.width / 2;
        Dimension titleSize = null;
        while (toBig) {
            System.out.println("ran at least once");
            title.setFont(new Font("Arial", Font.BOLD, fontSize));
            title.setForeground(Color.WHITE);
            title.setOpaque(true);
            title.setBackground(Color.BLACK);
            titleSize = title.getPreferredSize();
            if (titleSize.width > screen.width - textBuffer) {
                fontSize--;
            }
            else {
                toBig = false;
            }
        }
        title.setBounds(screen.width / 2 - titleSize.width / 2 - 5, screen.height / 10, titleSize.width + 10, titleSize.height);
        gameSetupPanel.add(title);

        // Text field for entering player names.
        playerName = new JTextField();
        int formattingBuffer = 5;
        playerName.setBounds(screen.width / 2 - screen.width / 8 - formattingBuffer, screen.height * 3 / 10, screen.width / 8, 30);
        gameSetupPanel.add(playerName);

        // Label for entering player names.
        JLabel nameLabel = new JLabel("Player Name:");
        nameLabel.setOpaque(true);
        nameLabel.setBackground(Color.BLACK);
        nameLabel.setForeground(Color.WHITE);
        nameLabel.setFont(new Font("Arial", Font.BOLD, 18));
        Dimension nameLabelSize = nameLabel.getPreferredSize();
        nameLabel.setBounds(screen.width / 2 - screen.width / 8 - 2 * formattingBuffer - nameLabelSize.width, screen.height * 3 / 10, nameLabelSize.width, 30);
        gameSetupPanel.add(nameLabel);

        // Label for entering player names.
        JLabel colorLabel = new JLabel("Player Color:");
        colorLabel.setOpaque(true);
        colorLabel.setBackground(Color.BLACK);
        colorLabel.setForeground(Color.WHITE);
        colorLabel.setFont(new Font("Arial", Font.BOLD, 18));
        Dimension colorLabelSize = colorLabel.getPreferredSize();
        colorLabel.setBounds(screen.width / 2 + formattingBuffer, screen.height * 3 / 10, colorLabelSize.width, 30);
        gameSetupPanel.add(colorLabel);

        // Dropdown list of available player colors.
        String[] colorList = {"None", "Red", "Cyan", "Green", "Yellow", "Magenta", "Orange"};
        playerColor = new JComboBox<>(colorList);
        playerColor.setSelectedIndex(0);
        playerColor.setBounds(screen.width / 2 + 2 * formattingBuffer + colorLabelSize.width, screen.height * 3 / 10, screen.width / 8, 30);
        gameSetupPanel.add(playerColor);

        // Button to add a player using the provided name and color.
        JButton addPlayer = new JButton("Add Player");
        addPlayer.setFont(new Font("Arial", Font.BOLD, 18));
        addPlayer.setBounds(screen.width / 2 - screen.width / 8, screen.height * 4 / 10, screen.width / 8, 40);
        addPlayer.addActionListener(e -> addPlayer());
        gameSetupPanel.add(addPlayer);

        // Button to add a player using the provided name and color.
        removePlayer = new JButton("Remove Player");
        removePlayer.setFont(new Font("Arial", Font.BOLD, 18));
        removePlayer.setBounds(screen.width / 2 + formattingBuffer, screen.height * 4 / 10, screen.width / 8, 40);
        removePlayer.addActionListener(e -> removePlayer());
        removePlayer.setEnabled(false);
        gameSetupPanel.add(removePlayer);

        // Model and list for displaying added players.
        playerListModel = new DefaultListModel<>();

        // List that holds all player objects
        playerList = new JList<>(playerListModel);
        playerList.addListSelectionListener(e -> removePlayer.setEnabled(true));

        // Scroll pane to contain the player list.
        JScrollPane scroll = new JScrollPane(playerList);
        scroll.setBounds(screen.width / 2 - screen.width / 8, screen.height * 9 /20, screen.width / 4, screen.height * 9 / 12 - screen.height * 9 / 20);
        gameSetupPanel.add(scroll);

        // Button to go back a page
        JButton backBt = new JButton("Back");
        backBt.setBounds( screen.width / 2 - screen.width / 8 - formattingBuffer, screen.height * 5 / 6, screen.width / 8, 80);
        backBt.addActionListener(e -> {
            parent.remove(gameSetupPanel);
            startController.displayMapChoicePage();
        });
        gameSetupPanel.add(backBt);

        // Button to proceed to the next setup step.
        startGame = new JButton("Continue");
        startGame.setBounds(screen.width / 2 + formattingBuffer,  screen.height * 5 / 6, screen.width / 8, 80);

        // Initially disabled until at least two players are added.
        startGame.setEnabled(false);

        // Stores players and transitions to the next page.
        startGame.addActionListener(e -> {
            startController.getGameSetUpData().setPlayers(players);
            parent.remove(gameSetupPanel);
            startController.displaySetUpOptionsPage();
        });
        gameSetupPanel.add(startGame);

        JButton closeButton = new JButton("X");
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setBounds(screen.width - 52, 2, 50, 50);
        closeButton.addActionListener(e -> System.exit(0));
        gameSetupPanel.add(closeButton);

        JButton minimizeButton = new JButton("-");
        minimizeButton.setFont(new Font("Arial", Font.BOLD, 14));
        minimizeButton.setBounds(screen.width - 104, 2, 50, 50);
        minimizeButton.addActionListener(e -> parent.setState(Frame.ICONIFIED));
        gameSetupPanel.add(minimizeButton);
    }

    /**
     * Adds the player setup panel to the main JFrame.
     *
     * @param startController the controller managing GUI navigation.
     */
    public void addPlayerPage(StartController startController) {
        this.startController = startController;
        this.parent = startController.getDisplay();
        parent.add(gameSetupPanel);
        parent.repaint();
    }

    /**
     * Handles adding a player after validating input fields.
     */
    private void addPlayer() {
        String name = playerName.getText().trim();
        String color = (String) playerColor.getSelectedItem();
        Color playersColor;

        switch (color) {
            case "Red":
                playersColor = Color.RED;
                break;
            case "Cyan":
                playersColor = Color.CYAN;
                break;
            case "Green":
                playersColor = Color.GREEN;
                break;
            case "Yellow":
                playersColor = Color.YELLOW;
                break;
            case "Magenta":
                playersColor = Color.MAGENTA;
                break;
            case "Orange":
                playersColor = new Color(215, 86, 36);
                break;
            default:
                JOptionPane.showMessageDialog(parent, "Select a player color.");
                return;
        }

        // Validates that the name is not empty.
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(parent, "Enter a player name.");
            return;
        }

        // Limits total players to 6.
        if (players.size() >= 6) {
            JOptionPane.showMessageDialog(parent, "Max 6 players.");
            return;
        }

        // Ensures no duplicate player names.
        for (Player p : players) {
            if (p.getName().equalsIgnoreCase(name)) {
                JOptionPane.showMessageDialog(parent, "Name already used.");
                return;
            }
        }

        if (playerName.getText().length() > 20) {
            JOptionPane.showMessageDialog(parent, "Name is " + playerName.getText().length() + " characters long, \nnames must be shorter than 20 characters.");
            return;
        }

        // Adds the new player and updates the display list.
        players.add(new Player(name, playersColor, color));
        playerListModel.addElement("Player: " + name + " | Color: " + color);
        playerColor.removeItem(color);

        // Clears Color selection back to None.
        playerColor.setSelectedIndex(0);

        // Clears the input field.
        playerName.setText("");

        // Enables continue button if at least two players exist.
        if (players.size() >= 2) {
            startGame.setEnabled(true);
        }
    }

    private void removePlayer() {
        int playerLocation = playerList.getSelectedIndex();
        Player playerToRemove = players.remove(playerLocation);

        playerListModel.remove(playerLocation);
        playerColor.addItem(playerToRemove.getColorName());
        removePlayer.setEnabled(false);

        if (players.size() < 2) {
            startGame.setEnabled(false);
        }
    }

    public void reset() {
        playerName.setText("");
        String[] colorList = {"None", "Red", "Cyan", "Green", "Yellow", "Magenta", "Orange"};
        playerColor.removeAllItems();
        for (String s: colorList) {
            playerColor.addItem(s);
        }
        startGame.setEnabled(false);
        removePlayer.setEnabled(false);
        players.clear();
        playerListModel.clear();
    }
}