package startGUI;

import javax.swing.*;
import java.awt.*;

/**
 * Represents the Settings Page in the Battle Nations GUI.
 *
 * <p>This class creates a panel with options to toggle sound and music,
 * along with a button to return to the start menu. The panel uses a
 * background image and manually positions all components based on
 * screen dimensions.</p>
 *
 * <p>
 * User settings are applied immediately when changed and are passed
 * back to the main controller to affect global audio behavior across
 * the application.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author Max Montowski
 */
public class SettingsPage {

    /** Background panel displaying the settings image. */
    private final ImagePanel settingsPanel;

    /** Checkbox for enabling/disabling sound effects. */
    private final JCheckBox sound;

    /** Checkbox for enabling/disabling music. */
    private final JCheckBox musicBt;

    /** Parent JFrame that contains this settings page. */
    private JFrame parent;

    /** Controller for managing GUI interactions. */
    private StartController startController;

    /**
     * Constructs the SettingsPage and initializes all components.
     */
    public SettingsPage() {
        // Initialize background panel with image
        settingsPanel = new ImagePanel("src/gameImages/SettingsImage.png");

        // Get screen dimensions
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        settingsPanel.setLayout(null);
        settingsPanel.setBounds(0, 0, screen.width, screen.height);

        // Initialize sound checkbox which controls whether buttons make sound.
        sound = new JCheckBox("Sound Affects", true);
        sound.setBounds(screen.width / 2 - screen.width / 12, screen.height / 2, screen.width / 6, 40);
        sound.addActionListener(e -> {
            startController.setSound(sound.isSelected());

            if (sound.isSelected()) {
                startController.makeSound();
            }

        });
        settingsPanel.add(sound);

        // Initialize music checkbox which controls whether music plays.
        musicBt = new JCheckBox("Music", true);
        musicBt.setBounds(screen.width / 2 - screen.width / 12, screen.height / 2 + 80, screen.width / 6, 40);
        settingsPanel.add(musicBt);
        musicBt.addActionListener(e -> {
            startController.makeSound();
            if (musicBt.isSelected()) {
                startController.getMusic().enableMusic();
            } else {
                startController.getMusic().disableMusic();
            }
        });

        // Initialize back button
        JButton back = new JButton("Back To Start");
        back.setBounds(screen.width / 2 - 100, 2 * screen.height / 3, 200, 50);
        back.addActionListener(e -> {
            // Remove settings page and return to start menu
            startController.makeSound();
            parent.remove(settingsPanel);
            startController.displayStartMenuPage();
        });
        settingsPanel.add(back);

        // Button that shuts program down when pressed.
        JButton closeButton = new JButton("X");
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setBounds(screen.width - 52, 2, 50, 50);
        closeButton.addActionListener(e -> {
            startController.makeSound();
            System.exit(0);
        });
        settingsPanel.add(closeButton);

        // Button that minimizes program when pressed.
        JButton minimizeButton = new JButton("-");
        minimizeButton.setFont(new Font("Arial", Font.BOLD, 14));
        minimizeButton.setBounds(screen.width - 104, 2, 50, 50);
        minimizeButton.addActionListener(e -> {
            startController.makeSound();
            parent.setState(Frame.ICONIFIED);
        });
        settingsPanel.add(minimizeButton);
    }

    /**
     * Adds the settings page to the specified StartController's display.
     *
     * @param startController the controller managing GUI interactions
     */
    public void addSettingsPage(StartController startController) {
        this.parent = startController.getDisplay();
        this.startController = startController;
        sound.setSelected(startController.isSoundEnabled());
        musicBt.setSelected(startController.getMusic().isMusicEnabled());
        parent.add(settingsPanel);
        parent.repaint();
    }
}