package startGUI;

import javax.swing.*;
import java.awt.*;

/**
 * Represents the Settings Page in the Battle Nations GUI.
 *
 * <p>This class creates a panel with options to toggle sound and music,
 * along with a button to return to the start menu. The panel uses a
 * background image and manually positions all components based on
 * screen dimensions.</p>
 *
 * <p>
 * User settings are applied immediately when changed and are passed
 * back to the main controller to affect global audio behavior across
 * the application.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author Max Montowski
 */
public class SettingsPage {

    /** Background panel displaying the settings image. */
    private final ImagePanel settingsPanel;

    /** Slider for controlling volume of music. */
    private final JSlider musicSlider;

    /** Slider for controlling volume of sound. */
    private final JSlider buttonSlider;

    /** Parent JFrame that contains this settings page. */
    private JFrame parent;

    /** Controller for managing GUI interactions. */
    private StartController startController;

    /**
     * Constructs the SettingsPage and initializes all components.
     */
    public SettingsPage() {
        // Initialize background panel with image
        settingsPanel = new ImagePanel("src/gameImages/SettingsImage.png");

        // Get screen dimensions
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        settingsPanel.setLayout(null);
        settingsPanel.setBounds(0, 0, screen.width, screen.height);

        // Creates a buffer for spacing.
        int formattingBuffer = 10;

        // Creates a label for the button volume slider.
        JLabel musicLabel = new JLabel("Music Volume:");
        musicLabel.setOpaque(true);
        musicLabel.setBackground(Color.BLACK);
        musicLabel.setForeground(Color.WHITE);
        musicLabel.setFont(new Font("Arial", Font.BOLD, 18));
        Dimension musicLabelSize = musicLabel.getPreferredSize();
        musicLabel.setBounds(screen.width / 2 - musicLabelSize.width - formattingBuffer, screen.height * 2 / 5, musicLabelSize.width + formattingBuffer, 40);
        settingsPanel.add(musicLabel);

        // Initializes music slider which controls the sound at which music plays.
        musicSlider = new JSlider(JSlider.HORIZONTAL, 0, 10, 10);
        musicSlider.setMajorTickSpacing(1);
        musicSlider.setPaintTicks(true);
        musicSlider.setBounds(screen.width / 2 + formattingBuffer, screen.height * 2 / 5, screen.width / 6, 40);
        settingsPanel.add(musicSlider);
        musicSlider.addChangeListener(e -> {
            startController.getMusic().setVolume(musicSlider.getValue());
            startController.makeSound();
        });

        // Creates a label for the button volume slider.
        JLabel buttonLabel = new JLabel("Button Volume:");
        buttonLabel.setOpaque(true);
        buttonLabel.setBackground(Color.BLACK);
        buttonLabel.setForeground(Color.WHITE);
        buttonLabel.setFont(new Font("Arial", Font.BOLD, 18));
        Dimension buttonLabelSize = buttonLabel.getPreferredSize();
        buttonLabel.setBounds(screen.width / 2 - buttonLabelSize.width - formattingBuffer, screen.height / 2, buttonLabelSize.width + formattingBuffer, 40);
        settingsPanel.add(buttonLabel);

        // Initializes button sound slider which controls how loud button clicks sound.
        buttonSlider = new JSlider(JSlider.HORIZONTAL, 0, 10, 10);
        buttonSlider.setMajorTickSpacing(1);
        buttonSlider.setPaintTicks(true);
        buttonSlider.setBounds(screen.width / 2 + formattingBuffer, screen.height / 2, screen.width / 6, 40);
        settingsPanel.add(buttonSlider);
        buttonSlider.addChangeListener(e -> {
            startController.setButtonSoundVolume(buttonSlider.getValue());
            startController.makeSound();
        });

        // Initialize back button
        JButton back = new JButton("Back To Start");
        back.setBounds(screen.width / 2 - 100, 2 * screen.height / 3, 200, 50);
        back.addActionListener(e -> {
            // Remove settings page and return to start menu
            startController.makeSound();
            parent.remove(settingsPanel);
            startController.displayStartMenuPage();
        });
        settingsPanel.add(back);

        // Button that shuts program down when pressed.
        JButton closeButton = new JButton("X");
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setBounds(screen.width - 52, 2, 50, 50);
        closeButton.addActionListener(e -> {
            startController.makeSound();
            System.exit(0);
        });
        settingsPanel.add(closeButton);

        // Button that minimizes program when pressed.
        JButton minimizeButton = new JButton("-");
        minimizeButton.setFont(new Font("Arial", Font.BOLD, 14));
        minimizeButton.setBounds(screen.width - 104, 2, 50, 50);
        minimizeButton.addActionListener(e -> {
            startController.makeSound();
            parent.setState(Frame.ICONIFIED);
        });
        settingsPanel.add(minimizeButton);
    }

    /**
     * Adds the settings page to the specified StartController's display.
     *
     * @param startController the controller managing GUI interactions
     */
    public void addSettingsPage(StartController startController) {
        this.parent = startController.getDisplay();
        this.startController = startController;
        buttonSlider.setValue((int) startController.getButtonSoundVolume());
        musicSlider.setValue((int) startController.getMusic().getVolume());
        parent.add(settingsPanel);
        parent.repaint();
    }
}