package startGUI;

import javax.swing.*;
import java.awt.*;

/**
 * Serves as the set options page for the battle nations GUI.
 *
 * <p>
 * This class creates a full screen panel with a background image and two groups of toggle buttons.
 * One group controls whether territories are assigned randomly or manually, and the other controls
 * whether troop placement is random or manual. A continue button allows progression once selections
 * are made.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class SetUpOptionsPage {

    /**
     * The controller that allows for navigation between panels.
     */
    private StartController startController;

    /**
     * The image panel that will hold the background image and buttons.
     */
    private final ImagePanel setUpOptionsPanel;

    /**
     * Boolean that keeps track of if the territory option has been selected yet.
     */
    boolean territoriesSelected = false;

    /**
     * Boolean that keeps track of if the troop option has been selected yet.
     */
    boolean troopsSelected = false;

    /**
     * Constructs a SetUp options page and initializes all buttons and layout.
     */
    public SetUpOptionsPage() {
        // Creates the background image panel.
        setUpOptionsPanel = new ImagePanel("src/gameImages/OptionScreen.png");

        // Gets the screen dimensions of the host device.
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();

        // Sets layout to null for manual positioning and sizes the panel.
        setUpOptionsPanel.setLayout(null);
        setUpOptionsPanel.setBounds(0, 0, screen.width, screen.height);

        // Button that allows the user to proceed once both options are selected.
        JButton continueBt = new JButton("Continue");
        continueBt.setBounds((int) screen.getWidth() / 2 - 100, (int) screen.getHeight() / 6 * 5, 200, 80);

        // Sets the continue button to disabled until both options are selected.
        continueBt.setEnabled(false);

        // Adds the continue button to the panel.
        setUpOptionsPanel.add(continueBt);

        // Groups the territory selection buttons so only one can be selected.
        ButtonGroup territoryButtons = new ButtonGroup();

        //Button for random territory selection.
        JRadioButton randomTerritories = new JRadioButton("Random Territory Selection");
        randomTerritories.setBounds((int) screen.getWidth() / 3 - 125, (int) screen.getHeight() / 5 * 2, 250, 40);

        // Button for manual territory selection.
        JRadioButton manuelTerritories = new JRadioButton("Manuel Territory Selection");
        manuelTerritories.setBounds((int) screen.getWidth() / 3 - 125, (int) screen.getHeight() / 5 * 3, 250, 40);

        // Adds buttons to the group and panel.
        territoryButtons.add(randomTerritories);
        territoryButtons.add(manuelTerritories);
        setUpOptionsPanel.add(randomTerritories);
        setUpOptionsPanel.add(manuelTerritories);

        // Sets game setup data based on selected territory option.
        randomTerritories.addActionListener(e -> {
            startController.getGameSetUpData().setRandomTerritories(true);
            territoriesSelected = true;
            if (troopsSelected) {
                continueBt.setEnabled(true);
            }
        });
        manuelTerritories.addActionListener(e -> {
            startController.getGameSetUpData().setRandomTerritories(false);
            territoriesSelected = true;
            if (troopsSelected) {
                continueBt.setEnabled(true);
            }
        });

        //Groups the troop placement buttons so only one can be selected.
        ButtonGroup troopButtons = new ButtonGroup();

        // Buttons for random troop placement.
        JRadioButton randomTroops = new JRadioButton("Random Troop Placement");
        randomTroops.setBounds((int) screen.getWidth() / 3 * 2 - 125, (int) screen.getHeight() / 5 * 2, 250, 40);

        // Buttons for manual troop placement.
        JRadioButton manualTroops = new JRadioButton("Manuel Troop Placement");
        manualTroops.setBounds((int) screen.getWidth() / 3 * 2 - 125, (int) screen.getHeight() / 5 * 3, 250, 40);

        // Adds buttons to the group and panel.
        troopButtons.add(randomTroops);
        troopButtons.add(manualTroops);
        setUpOptionsPanel.add(randomTroops);
        setUpOptionsPanel.add(manualTroops);

        // Sets game setup data based on selected troop placement option.
        randomTroops.addActionListener(e -> {
            startController.getGameSetUpData().setRandomTroopPlacement(true);
            troopsSelected = true;
            if (territoriesSelected) {
                continueBt.setEnabled(true);
            }

        });
        manualTroops.addActionListener(e -> {
            startController.getGameSetUpData().setRandomTroopPlacement(false);
            troopsSelected = true;
            if (territoriesSelected) {
                continueBt.setEnabled(true);
            }
        });

        // Only proceeds if both a territory and troop option are selected.
        continueBt.addActionListener(e -> {
            startController.getDisplay().remove(setUpOptionsPanel);
            startController.changeToSetUpController();
        });
    }

    /**
     * Adds the setup options panel to the main JFrame display.
     *
     * @param startController the controller managing GUI navigation.
     */
    public void addSetUpOptionsPage(StartController startController) {
        this.startController = startController;
        JFrame parent = startController.getDisplay();
        parent.add(setUpOptionsPanel);
        parent.repaint();
    }

}
