package startGUI;

import javax.swing.*;
import java.awt.*;

/**
 * Serves as the set options page for the battle nations GUI.
 *
 * <p>
 * This class creates a full screen panel with a background image and two groups of toggle buttons.
 * One group controls whether territories are assigned randomly or manually, and the other controls
 * whether troop placement is random or manual. A continue button allows progression once selections
 * are made.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class SetUpOptionsPage {

    /**
     * The controller that allows for navigation between panels.
     */
    private StartController startController;

    /**
     * The image panel that will hold the background image and buttons.
     */
    private final ImagePanel setUpOptionsPanel;

    /**
     * Boolean that keeps track of if the territory option has been selected yet.
     */
    private boolean territoriesSelected = false;

    /**
     * Boolean that keeps track of if the troop option has been selected yet.
     */
    private boolean troopsSelected = false;

    private boolean dominationSelected = false;

    private JFrame parent;

    /**
     * Constructs a SetUp options page and initializes all buttons and layout.
     */
    public SetUpOptionsPage() {
        // Creates the background image panel.
        setUpOptionsPanel = new ImagePanel("src/gameImages/OptionScreen.png");

        // Gets the screen dimensions of the host device.
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();

        // Sets layout to null for manual positioning and sizes the panel.
        setUpOptionsPanel.setLayout(null);
        setUpOptionsPanel.setBounds(0, 0, screen.width, screen.height);

        // Creates and positions the page title.
        JLabel title = new JLabel("GAME SET UP");
        boolean toBig = true;
        int fontSize = 100;
        int textBuffer = screen.width / 2;
        Dimension titleSize = null;
        while (toBig) {
            title.setFont(new Font("Arial", Font.BOLD, fontSize));
            title.setForeground(Color.WHITE);
            title.setOpaque(true);
            title.setBackground(Color.BLACK);
            titleSize = title.getPreferredSize();
            if (titleSize.width > screen.width - textBuffer) {
                fontSize--;
            }
            else {
                toBig = false;
            }
        }
        title.setBounds(screen.width / 2 - titleSize.width / 2 - 5, screen.height / 10, titleSize.width + 10, titleSize.height);
        setUpOptionsPanel.add(title);

        int formattingBuffer = 10;

        // Button to go back a page
        JButton backBt = new JButton("Back");
        backBt.setBounds( screen.width / 2 - screen.width / 8 - formattingBuffer, screen.height * 5 / 6, screen.width / 8, 80);        backBt.addActionListener(e -> {
            parent.remove(setUpOptionsPanel);
            startController.displayPlayerPage();
        });
        setUpOptionsPanel.add(backBt);

        // Button that allows the user to proceed once both options are selected.
        JButton continueBt = new JButton("Continue");
        continueBt.setBounds(screen.width / 2 + formattingBuffer,  screen.height * 5 / 6, screen.width / 8, 80);

        // Sets the continue button to disabled until both options are selected.
        continueBt.setEnabled(false);

        // Adds the continue button to the panel.
        setUpOptionsPanel.add(continueBt);

        // Groups the territory selection buttons so only one can be selected.
        ButtonGroup territoryButtons = new ButtonGroup();

        //Button for random territory selection.
        JRadioButton randomTerritories = new JRadioButton("Random Territory Selection");
        randomTerritories.setBounds(screen.width / 2 - screen.width * 3 / 12 - formattingBuffer, screen.height * 2 / 5, screen.width / 6, 40);

        // Button for manual territory selection.
        JRadioButton manuelTerritories = new JRadioButton("Manuel Territory Selection");
        manuelTerritories.setBounds(screen.width / 2 - screen.width * 3 / 12 - formattingBuffer, screen.height * 3 / 5, screen.width / 6, 40);

        // Adds buttons to the group and panel.
        territoryButtons.add(randomTerritories);
        territoryButtons.add(manuelTerritories);
        setUpOptionsPanel.add(randomTerritories);
        setUpOptionsPanel.add(manuelTerritories);

        // Sets game setup data based on selected territory option.
        randomTerritories.addActionListener(e -> {
            startController.getGameSetUpData().setRandomTerritories(true);
            territoriesSelected = true;
            if (troopsSelected && dominationSelected) {
                continueBt.setEnabled(true);
            }
        });
        manuelTerritories.addActionListener(e -> {
            startController.getGameSetUpData().setRandomTerritories(false);
            territoriesSelected = true;
            if (troopsSelected && dominationSelected) {
                continueBt.setEnabled(true);
            }
        });

        //Groups the troop placement buttons so only one can be selected.
        ButtonGroup troopButtons = new ButtonGroup();

        // Buttons for random troop placement.
        JRadioButton randomTroops = new JRadioButton("Random Troop Placement");
        randomTroops.setBounds(screen.width / 2 - screen.width / 12, screen.height  * 2 / 5, screen.width / 6, 40);

        // Buttons for manual troop placement.
        JRadioButton manualTroops = new JRadioButton("Manuel Troop Placement");
        manualTroops.setBounds(screen.width / 2 - screen.width / 12, screen.height * 3 / 5, screen.width / 6, 40);

        // Adds buttons to the group and panel.
        troopButtons.add(randomTroops);
        troopButtons.add(manualTroops);
        setUpOptionsPanel.add(randomTroops);
        setUpOptionsPanel.add(manualTroops);


        //Groups the troop placement buttons so only one can be selected.
        ButtonGroup gameModeButtons = new ButtonGroup();

        // Buttons for random troop placement.
        JRadioButton totalDomination = new JRadioButton("Total Domination");
        totalDomination.setBounds(screen.width / 2 + screen.width / 12 + formattingBuffer, screen.height * 2 / 5, screen.width / 6, 40);

        // Buttons for manual troop placement.
        JRadioButton capitalDomination = new JRadioButton("Capital Domination");
        capitalDomination.setBounds(screen.width / 2 + screen.width / 12 + formattingBuffer, screen.height * 3/ 5, screen.width / 6, 40);

        // Adds buttons to the group and panel.
        gameModeButtons.add(totalDomination);
        gameModeButtons.add(capitalDomination);
        setUpOptionsPanel.add(totalDomination);
        setUpOptionsPanel.add(capitalDomination);

        // Sets game setup data based on selected troop placement option.
        randomTroops.addActionListener(e -> {
            startController.getGameSetUpData().setRandomTroopPlacement(true);
            troopsSelected = true;
            if (territoriesSelected && dominationSelected) {
                continueBt.setEnabled(true);
            }

        });
        manualTroops.addActionListener(e -> {
            startController.getGameSetUpData().setRandomTroopPlacement(false);
            troopsSelected = true;
            if (territoriesSelected && dominationSelected) {
                continueBt.setEnabled(true);
            }
        });

        totalDomination.addActionListener(e -> {
            startController.getGameSetUpData().setGameMode("totalDomination");
            dominationSelected = true;
            if(territoriesSelected && troopsSelected) {
                continueBt.setEnabled(true);
            }
        });

        capitalDomination.addActionListener(e -> {
            startController.getGameSetUpData().setGameMode("capitalDomination");
            dominationSelected = true;
            if(territoriesSelected && troopsSelected) {
                continueBt.setEnabled(true);
            }
        });

        // Only proceeds if both a territory and troop option are selected.
        continueBt.addActionListener(e -> {
            startController.getDisplay().remove(setUpOptionsPanel);
            startController.changeToSetUpController();
        });

        JButton closeButton = new JButton("X");
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setBounds(screen.width - 52, 2, 50, 50);
        closeButton.addActionListener(e -> System.exit(0));
        setUpOptionsPanel.add(closeButton);

        JButton minimizeButton = new JButton("-");
        minimizeButton.setFont(new Font("Arial", Font.BOLD, 14));
        minimizeButton.setBounds(screen.width - 104, 2, 50, 50);
        minimizeButton.addActionListener(e -> parent.setState(Frame.ICONIFIED));
        setUpOptionsPanel.add(minimizeButton);
    }

    /**
     * Adds the setup options panel to the main JFrame display.
     *
     * @param startController the controller managing GUI navigation.
     */
    public void addSetUpOptionsPage(StartController startController) {
        this.startController = startController;
        parent = startController.getDisplay();
        parent.add(setUpOptionsPanel);
        parent.repaint();
    }

}
