package startGUI;

import player.Player;

import java.util.List;

/**
 * Stores all setup data required before starting a game in Battle Nations.
 *
 * <p>
 * This class holds information such as the selected map, list of players,
 * and configuration options for territory assignment and troop placement.
 * It acts as a shared data container between setup screens and controllers.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in cunjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class SetUpData {

    /**
     * The name or identifier of the selected map.
     */
    private String map;

    /**
     * The list of players participating in the game.
     */
    private List<Player> players;

    /**
     * Determines if territories are assigned randomly.
     */
    private boolean randomTerritories;

    /**
     * Determines if troop placement is randomized.
     */
    private boolean randomTroopPlacement;

    /**
     * Constructs an empty SetUpData object.
     */
    public SetUpData() {
    }

    /**
     * Gets the selected map.
     *
     * @return the map name or identifier.
     */
    public String getMap() {
        return map;
    }

    /**
     * Sets the selected map.
     *
     * @param map the map name or identifier.
     */
    public void setMap(String map) {
        this.map = map;
    }

    /**
     * Checks if troop placement is random.
     *
     * @return true if troop placement is random, false otherwise.
     */
    public boolean isRandomTroopPlacement() {
        return randomTroopPlacement;
    }

    /**
     * Sets whether troop placement is random.
     *
     * @param randomTroopPlacement true for random placement, false for manual.
     */
    public void setRandomTroopPlacement(boolean randomTroopPlacement) {
        this.randomTroopPlacement = randomTroopPlacement;
    }

    /**
     * Checks if territories are assigned randomly.
     *
     * @return true if territories are random, false otherwise.
     */
    public boolean isRandomTerritories() {
        return randomTerritories;
    }

    /**
     * Sets whether territories are assigned randomly.
     *
     * @param randomTerritories true for random assignment, false for manual.
     */
    public void setRandomTerritories(boolean randomTerritories) {
        this.randomTerritories = randomTerritories;
    }

    /**
     * Gets the list of players.
     *
     * @return the list of players in the game.
     */
    public List<Player> getPlayers() {
        return players;
    }

    /**
     * Sets the list of players.
     *
     * @param players the players participating in the game.
     */
    public void setPlayers(List<Player> players) {
        this.players = players;
    }
}
