package startGUI;

import javax.swing.*;

/**
 * Controls the main GUI flow of Battle Nations.
 *
 * <p>This class manages switching between different pages, including the
 * start menu, settings page, and map display. It initializes a full-screen
 * JFrame and handles displaying each page by delegating to the respective
 * page classes.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author Max Montowski
 */
public class StartController {

    /**
     * The main JFrame used to display all GUI pages.
     */
    private final JFrame display;

    /**
     * The start menu page.
     */
    private final StartMenuPage start;

    /**
     * The settings page.
     */
    private final SettingsPage settings;

    /**
     *  The Map Choice Page.
     */
    private final MapChoicePage mapChoice;



    /**
     * The game setup page.
     */
    private final GameSetupPage gameSetupPage;

    private SetUpData gameSetUpData = new SetUpData();

    /**
     * Constructs a StartController, initializes all pages, and displays the start menu.
     */
    public StartController() {
        display = new JFrame();
        display.setExtendedState(JFrame.MAXIMIZED_BOTH);
        display.setUndecorated(true);

        // Initialize pages
        start = new StartMenuPage();
        settings = new SettingsPage();
        mapChoice = new MapChoicePage();
        gameSetupPage = new GameSetupPage();

        // Show the start menu by default
        displayStartMenuPage();
    }

    /**
     * Displays the start menu page on the main display.
     */
    public void displayStartMenuPage() {
        start.addStartMenuPage(this);
    }

    /**
     * Displays the settings page on the main display.
     */
    public void displaySettingsPage() {
        settings.addSettingsPage(this);
    }


    public void displayGameSetupPage() {
        gameSetupPage.addGameSetupPage(this);
    }

    public void displayMapChoicePage() {mapChoice.addMapChoicePage(this);}

    /**
     * Returns the main JFrame used for the GUI.
     *
     * @return the main display JFrame
     */
    public JFrame getDisplay() {
        return display;
    }

    /**
     * Returns the start menu page instance.
     *
     * @return the StartMenuPage instance
     */
    public StartMenuPage getStart() {
        return start;
    }

    /**
     * Returns the settings page instance.
     *
     * @return the SettingsPage instance
     */
    public SettingsPage getSettings() {
        return settings;
    }

    public SetUpData getGameSetUpData() {
        return gameSetUpData;
    }

    /**
     * Entry point for the application.
     *
     * @param args command-line arguments (not used)
     */
    public static void main(String[] args) {
        new StartController();
    }
}
