package startGUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Represents the Start Menu page of the Battle Nations GUI.
 *
 * <p>This class creates a full-screen panel with a background image and three main buttons:
 * "Start Game" to go to the map display, "Settings" to open the settings page, and "Quit"
 * to exit the application.</p>
 *
 * <p>The panel uses absolute positioning for all components, based on screen size.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author J.D. Reighard
 * @version 1.0
 * @since 2026-03-12
 */
public class StartMenuPage {

    /**
     * The main panel displaying the start menu background and buttons.
     */
    private final ImagePanel startMenuPanel;

    /**
     * Parent JFrame that contains this start menu panel.
     */
    private JFrame parent;

    /**
     * Controller for managing GUI navigation.
     */
    private StartController startController;

    /**
     * Constructs the StartMenuPage and initializes all buttons and the background image.
     */
    public StartMenuPage() {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        startMenuPanel = new ImagePanel("src/gameImages/BattleNationsHomeScreen.png");
        startMenuPanel.setLayout(null);
        startMenuPanel.setBounds(0, 0, screen.width, screen.height);

        // Start Game button
        JButton startGame = new JButton("Start Game");
        startGame.setBounds(screen.width / 2 - 100, screen.height / 3, 200, 50);
        startGame.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                parent.remove(startMenuPanel);
                startController.displayMapDisplay();
            }
        });
        startMenuPanel.add(startGame);

        // Settings button
        JButton settings = new JButton("Settings");
        settings.setBounds(screen.width / 2 - 100, screen.height / 2, 200, 50);
        settings.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                parent.remove(startMenuPanel);
                startController.displaySettingsPage();
            }
        });
        startMenuPanel.add(settings);

        // Quit button
        JButton quit = new JButton("Quit");
        quit.setBounds(screen.width / 2 - 100, 2 * screen.height / 3, 200, 50);
        quit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        startMenuPanel.add(quit);
    }

    /**
     * Adds the start menu panel to the specified StartController's display.
     *
     * @param startController the controller managing GUI navigation
     */
    public void addStartMenuPage(StartController startController) {
        this.startController = startController;
        this.parent = startController.getDisplay();
        parent.add(startMenuPanel);
        parent.repaint();
    }
}