package map;

import player.Player;

import java.util.ArrayList;
import java.util.List;

/**
 * Abstract base class for all game world implementations in Battle Nations.
 *
 * <p>Provides shared implementations of the {@link World} interface for
 * querying territories, regions, and player ownership. Concrete subclasses
 * are responsible for implementing the win condition logic specific to
 * their game mode.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public abstract class AbstractWorld implements World {

    /**
     * The list of regions that make up this world.
     */
    protected final List<Region> regions;

    /**
     * Constructs an AbstractWorld with a predefined list of regions.
     *
     * @param regions the regions that make up the world
     */
    public AbstractWorld(List<Region> regions) {
        // Defensive copy — prevents external mutation of the world's region list
        this.regions = new ArrayList<>(regions);
    }

    /**
     * Constructs an empty AbstractWorld with no regions.
     */
    public AbstractWorld() {
        this.regions = new ArrayList<>();
    }

    /**
     * Returns all regions in the world.
     *
     * @return the list of all regions
     */
    public List<Region> getRegions() {
        return this.regions;
    }

    /**
     * Returns every territory across all regions in the world.
     *
     * @return the list of all territories
     */
    public List<Territory> getAllTerritories() {
        List<Territory> territories = new ArrayList<>();

        for (Region region : regions) {
            territories.addAll(region.getTerritories());
        }

        return territories;
    }

    /**
     * Returns the total number of territories in the world.
     *
     * @return the territory count
     */
    public int getTerritoryCount() {
        return getAllTerritories().size();
    }

    /**
     * Returns all territories currently owned by the given player.
     *
     * @param player the player to check ownership for
     * @return the list of territories owned by the player
     */
    public List<Territory> getTerritoriesOwnedByPlayer(Player player) {
        List<Territory> allTerritories = getAllTerritories();
        List<Territory> playerTerritories = new ArrayList<>();

        for (Territory territory : allTerritories) {
            if (player.equals(territory.getPlayer())) {
                playerTerritories.add(territory);
            }
        }

        return playerTerritories;
    }

    /**
     * Returns the number of territories currently owned by the given player.
     *
     * @param player the player to check ownership for
     * @return the number of territories owned by the player
     */
    public int getTerritoryCountOwnedByPlayer(Player player) {
        return getTerritoriesOwnedByPlayer(player).size();
    }

    /**
     * Returns all regions fully controlled by the given player.
     *
     * <p>A region is only included if it has been conquered and its
     * controlling player matches the given player.</p>
     *
     * @param player the player to check control for
     * @return the list of regions controlled by the player
     */
    public List<Region> getRegionsControlledByPlayer(Player player) {
        List<Region> playerOwnedRegions = new ArrayList<>();

        for (Region region : regions) {
            // Only conquered regions can be attributed to a player
            if (region.isRegionConquered()) {
                if (isRegionControlledByPlayer(region, player)) {
                    playerOwnedRegions.add(region);
                }
            }
        }

        return playerOwnedRegions;
    }

    /**
     * Returns the number of regions fully controlled by the given player.
     *
     * @param player the player to check control for
     * @return the number of regions controlled by the player
     */
    public int getRegionCountControlledByPlayer(Player player) {
        return getRegionsControlledByPlayer(player).size();
    }

    /**
     * Determines whether the given region is fully controlled by the given player.
     *
     * @param region the region to check
     * @param player the player to check control for
     * @return true if the player controls the region, false otherwise
     */
    public boolean isRegionControlledByPlayer(Region region, Player player) {
        Player controllingPlayer = region.getPlayerConqueredRegion();

        // Region must have a controlling player and it must match the given player
        return (controllingPlayer != null && controllingPlayer.equals(player));
    }

    /**
     * Determines whether the win condition for this world has been met.
     *
     * <p>Implemented by subclasses to define game-mode-specific win conditions.</p>
     *
     * @param players the list of players in the game
     * @return true if the game has been won, false otherwise
     */
    public abstract boolean isGameWon(List<Player> players);

    /**
     * Returns the player who has met the win condition, or null if no one has won yet.
     *
     * <p>Implemented by subclasses to define game-mode-specific win conditions.</p>
     *
     * @param players the list of players in the game
     * @return the winning player, or null if the game is still in progress
     */
    public abstract Player getWinningPlayer(List<Player> players);
}