package map;

import player.Player;

import java.util.ArrayList;
import java.util.List;

/**
 * A game world where the win condition is capturing all capital territories.
 *
 * <p>In Capital Domination, each region has one designated capital territory.
 * A player wins by owning every capital territory across all regions. This mode
 * encourages players to prioritize capital territories over total map control.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public class CapitalDominationWorld extends AbstractWorld {

    /** The total number of capital territories in the world, set on construction to avoid recomputing each turn. */
    private int territoryCapitals;

    /**
     * Constructs a CapitalDominationWorld with a predefined list of regions.
     *
     * @param regions the regions that make up the world
     */
    public CapitalDominationWorld(ArrayList<Region> regions) {
        super(regions);

        // Set the capital count once on construction
        setTerritoryCapitals();
    }

    /**
     * Determines whether any player has won by owning all capital territories.
     *
     * @param players the list of players in the game
     * @return true if a player owns all capital territories, false otherwise
     */
    @Override
    public boolean isGameWon(List<Player> players) {
        int totalCapitals = getCapitalTerritoriesCount();

        for (Player player : players) {
            // Win condition — player owns every capital territory on the map
            if (getCapitalTerritoriesCountOwnedByPlayer(player) == totalCapitals) {
                return true;
            }
        }

        return false;
    }

    /**
     * Returns the number of capital territories currently owned by the given player.
     *
     * @param player the player to check
     * @return the number of capital territories owned by the player
     */
    private int getCapitalTerritoriesCountOwnedByPlayer(Player player) {
        int temp = 0;

        for (Region region : regions) {
            if (region.getCapitalTerritory().getPlayer().equals(player)) {
                temp++;
            }
        }

        return temp;
    }

    /**
     * Returns the total number of capital territories across all regions.
     *
     * @return the total capital territory count
     */
    private int getCapitalTerritoriesCount() {
        int temp = 0;

        for (Region region : regions) {
            if (region.getCapitalTerritory() != null) {
                temp++;
            }
        }

        return temp;
    }

    /**
     * Caches the total capital territory count into {@code territoryCapitals}.
     *
     * <p>Called once during construction so the count doesn't need to be
     * recomputed every time the win condition is checked.</p>
     */
    private void setTerritoryCapitals() {
        this.territoryCapitals = getCapitalTerritoriesCount();
    }

    /**
     * Returns the player who owns all capital territories, or null if no one has won yet.
     *
     * @param players the list of players in the game
     * @return the winning player, or null if the game is still in progress
     */
    public Player getWinningPlayer(List<Player> players) {
        for (Player player : players) {
            if (getCapitalTerritoriesCountOwnedByPlayer(player) == territoryCapitals) {
                return player;
            }
        }

        return null;
    }
}