package map;

/**
 * Represents city terrain in Battle Nations.
 *
 * <p>City terrain provides an attack bonus and grants additional troops
 * when controlled. Cities are intended to represent strategic locations
 * that encourage players to fight for control of populated areas.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author J.D. Reighard
 * @version 1.0
 * @since 2026-03-04
 */
public class CityTerrain extends Terrain {
    /**
     * Attack bonus percentage provided by city terrain.
     */
    private static final double ATTACK_BONUS_PERCENTAGE = .12;
    /**
     * Defense bonus percentage provided by city terrain.
     */
    private static final double DEFENSE_BONUS_PERCENTAGE = 0;
    /**
     * Additional troops granted by city terrain.
     */
    private static final int TROOP_BONUS = 1;
    /**
     * Image file used to represent city terrain on the map.
     */
    private static final String ICON_FILENAME = "src/gameImages/CityTerrain.png";

    /**
     * Constructs a CityTerrain object with predefined terrain bonuses.
     */
    public CityTerrain() {
        super(ATTACK_BONUS_PERCENTAGE, DEFENSE_BONUS_PERCENTAGE, ICON_FILENAME, TROOP_BONUS);
    }
}
