package map;

/**
 * Represents desert terrain in Battle Nations.
 *
 * <p>Desert terrain provides a higher attack bonus but does not grant
 * additional troops or defensive bonuses. This terrain type encourages
 * aggressive play and offensive strategies.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author J.D. Reighard
 * @version 1.0
 * @since 2026-03-04
 */

public class DesertTerrain extends Terrain {
    /**
     * Attack bonus percentage provided by desert terrain.
     */
    private static final double ATTACK_BONUS_PERCENTAGE = .15;
    /**
     * Defense bonus percentage provided by desert terrain.
     */
    private static final double DEFENSE_BONUS_PERCENTAGE = 0;
    /**
     * Additional troops granted by desert terrain.
     */
    private static final int TROOP_BONUS = 0;
    /**
     * Image file used to represent desert terrain on the map.
     */
    private static final String ICON_FILENAME = "PlaceHolder";

    public DesertTerrain() {
        super(ATTACK_BONUS_PERCENTAGE, DEFENSE_BONUS_PERCENTAGE, ICON_FILENAME, TROOP_BONUS);
    }
}
