package map;

import player.Player;

import java.util.ArrayList;
import java.util.List;

/**
 * A simple dummy implementation of the World used for testing purposes.
 *
 * <p>This class extends {@link AbstractWorld} and provides a minimal
 * implementation of required abstract methods. It is intended to be used
 * in unit tests or during development when a fully functional world
 * implementation is not necessary.</p>
 *
 * <p>The {@code isGameWon} method is overridden to always return false,
 * allowing controlled testing of game logic without triggering win conditions.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */

public class DummyWorld extends AbstractWorld {

    /**
     * Determines whether the game has been won.
     *
     * <p>This dummy implementation always returns {@code false} and does not
     * evaluate any actual game conditions.</p>
     *
     * @param players the list of players in the game
     * @return always {@code false}
     */

    public DummyWorld(ArrayList<Region> regions) {
        super(regions);
    }
    @Override
    public boolean isGameWon(List<Player> players) {
        return false;
    }
}
