package map;

import player.Player;

import java.util.ArrayList;
import java.util.List;

/**
 * A simple dummy implementation of {@link World} used for testing purposes.
 *
 * <p>This class extends {@link AbstractWorld} and provides a minimal
 * implementation of the required abstract methods. It is intended to be used
 * in unit tests or during development when a fully functional world
 * implementation is not necessary.</p>
 *
 * <p>{@code isGameWon} always returns false and {@code getWinningPlayer}
 * always returns null, allowing controlled testing of game logic without
 * triggering win conditions.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public class DummyWorld extends AbstractWorld {

    /**
     * Constructs a DummyWorld with a predefined list of regions.
     *
     * @param regions the regions that make up the world
     */
    public DummyWorld(ArrayList<Region> regions) {
        super(regions);
    }

    /**
     * Always returns false — win conditions are not evaluated in this dummy implementation.
     *
     * @param players the list of players in the game
     * @return false always
     */
    @Override
    public boolean isGameWon(List<Player> players) {
        return false;
    }

    /**
     * Always returns null — no winner is ever determined in this dummy implementation.
     *
     * @param players the list of players in the game
     * @return null always
     */
    public Player getWinningPlayer(List<Player> players) {
        return null;
    }
}