package map;

import terrain.WaterRouteTerrain;

import java.util.List;

/**
 * Assigns neighboring territories to each territory in the game map.
 *
 * <p>This service iterates over a 2D hexagonal grid of territories and
 * establishes neighbor relationships between adjacent tiles.
 * It handles the offset nature of hexagonal grids where odd rows are shifted,
 * resulting in different neighbor indexing depending on row parity.</p>
 *
 * <p>After direct neighbors are assigned, water route territories are processed
 * to connect non-adjacent territories that are linked through navigable sea paths.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public class GenerateNeighborService {

    /**
     * Assigns neighbors to all territories in the given 2D grid.
     *
     * <p>Each territory can have up to 6 neighbors in the hexagonal grid:
     * directly above, directly below, top left, top right, bottom left, and bottom right.
     * Neighbor indexing differs between even and odd rows due to the hex grid offset.
     * After all direct neighbors are assigned, water route connections are also applied.</p>
     *
     * @param territories the 2D array of territories representing the map grid
     */
    public void generateNeighbors(Territory[][] territories) {
        for (int i = 0; i < territories.length; i++) {
            int alternator = (i % 2 != 0) ? 1 : 0;
            // Row length changes depending on if territories have been shifted to fit
            // even rows = territories[i].length
            // odd rows = territories[i].length - 1
            int rowLength = territories[i].length;

            for (int j = 0; j < rowLength; j++) {
                Territory current = territories[i][j];

                if (current == null) {
                    continue;
                }

                // Get directly above neighbor (if exists)
                if (i - 2 >= 0) {
                    int upperVerticalRowLength = territories[i - 2].length;

                    if (j < upperVerticalRowLength) {
                        addTerritoryNeighbor(current, territories[i - 2][j]);
                    }
                }

                // Get directly below neighbor (if exists)
                if (i + 2 < territories.length) {
                    int lowerVerticalRowLength = territories[i + 2].length;

                    if (j < lowerVerticalRowLength) {
                        addTerritoryNeighbor(current, territories[i + 2][j]);
                    }
                }

                // Get any upper neighbors
                if (i - 1 >= 0) {
                    int upperRowLength = territories[i - 1].length;

                    // Current row is an even row
                    if (alternator == 0) {
                        if (j - 1 >= 0 && j - 1 < upperRowLength) {
                            // Add top left territory
                            addTerritoryNeighbor(current, territories[i - 1][j - 1]);
                        }

                        if (j < upperRowLength) {
                            // Add top right territory
                            addTerritoryNeighbor(current, territories[i - 1][j]);
                        }
                    } else {
                        // Current row is an odd row
                        if (j < upperRowLength) {
                            addTerritoryNeighbor(current, territories[i - 1][j]);
                        }

                        if (j + 1 < upperRowLength) {
                            addTerritoryNeighbor(current, territories[i - 1][j + 1]);
                        }
                    }
                }

                // Get any lower neighbors
                if (i + 1 < territories.length) {
                    int lowerRowLength = territories[i + 1].length;

                    // The current row is an even row
                    if (alternator == 0) {
                        if (j - 1 >= 0 && j - 1 < lowerRowLength) {
                            // Shift j over one to grab the true left neighbor
                            addTerritoryNeighbor(current, territories[i + 1][j - 1]);
                        }

                        if (j < lowerRowLength) {
                            // Use j to grab the true right neighbor, no shift needed
                            addTerritoryNeighbor(current, territories[i + 1][j]);
                        }
                    } else {
                        // The current row is odd
                        if (j < lowerRowLength) {
                            addTerritoryNeighbor(current, territories[i + 1][j]);
                        }

                        if (j + 1 < lowerRowLength) {
                            // Shift j over right 1 to grab the right neighbor
                            addTerritoryNeighbor(current, territories[i + 1][j + 1]);
                        }
                    }
                }
            }
        }
        addingWaterRouteNeighbors(territories);
    }

    /**
     * Attempts to add a neighbor relationship between two territories.
     *
     * <p>If either territory is null or they are already neighbors, no change is made.
     * Returns true if at least one new neighbor relationship was established.</p>
     *
     * @param current  the territory to add a neighbor to
     * @param neighbor the territory to be added as a neighbor
     * @return true if a new neighbor was added, false otherwise
     */
    private boolean addTerritoryNeighbor(Territory current, Territory neighbor) {
        if (neighbor == null || current == null) {
            return false;
        }

        boolean returnValue = false;

        // Add neighbor to current if not already present
        if (!current.hasNeighbor(neighbor)) {
            current.addToTerritoryNeighbors(neighbor);
            returnValue = true;
        }

        // Add current to neighbor if not already present
        if (!neighbor.hasNeighbor(current)) {
            neighbor.addToTerritoryNeighbors(current);
            returnValue = true;
        }
        return returnValue;
    }

    /**
     * Iterates over the territory grid and applies water route neighbor expansion
     * to every non-null territory.
     *
     * @param territories the 2D array of territories representing the map grid
     */
    private void addingWaterRouteNeighbors(Territory[][] territories) {
        for (int i = 0; i < territories.length; i++) {
            int alternator = (i % 2 != 0) ? 1 : 0;
            // Row length changes depending on if territories have been shifted to fit
            // even rows = territories[i].length
            // odd rows = territories[i].length - 1
            int rowLength = territories[i].length;

            for (int j = 0; j < rowLength; j++) {
                Territory current = territories[i][j];

                if (current == null) {
                    continue;
                }

                moreWaterRoutes(current);
            }
        }
    }

    /**
     * Expands the neighbor list of a territory by connecting it through any
     * adjacent water route territories.
     *
     * <p>If a neighbor of the current territory is a water route, all of that
     * water route's neighbors are also added as neighbors of the current territory.
     * This process repeats until no new neighbors can be added.</p>
     *
     * @param current the territory whose neighbors are being expanded via water routes
     */
    private void moreWaterRoutes(Territory current) {
        List<Territory> neighbors = current.getNeighboringTerritories();
        boolean newNeighbors = false;
        outer:
        while (!newNeighbors) {
            newNeighbors = true;
            for (Territory n : neighbors) {
                // Check if this neighbor is a water route
                if (n.getTerrain() instanceof WaterRouteTerrain) {
                    List<Territory> waterRoutesNeighbors = n.getNeighboringTerritories();
                    for (Territory wrn : waterRoutesNeighbors) {
                        // If a new neighbor was added, restart the search to catch any newly reachable routes
                        if (addTerritoryNeighbor(current, wrn)) {
                            newNeighbors = false;
                            continue outer;
                        }
                    }
                }
            }
        }
    }
}