package map;

import setUpGUI.SetUpController;
import startGUI.SetUpData;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 * Represents the main map display in Battle Nations.
 *
 * <p>This class handles loading a map from a file, generating territories
 * as hexagonal tiles, and displaying them within a GUI. Each territory
 * corresponds to a specific terrain type such as mountain, desert, or city.</p>
 *
 * <p>Territories are positioned and scaled dynamically to fit the screen
 * while maintaining a hexagonal grid layout.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 */
public class MapDisplay {

    /** Width of the display, based on screen size. */
    private final int displayWidth;

    /** Height of the display, based on screen size. */
    private final int displayHeight;

    /** Panel that renders the map and its territories. */
    private final MapPanel mapDisplay;

    /** The screen dimensions. */
    private final Dimension screen;

    /** 2D array of territories representing the map grid. */
    private final Territory[][] territories;

    /** Parent JFrame that contains the map display. */
    private final JFrame parent;

    /** Service used to load map data from external files. */
    private final MapLoaderService loader;

    /** Container object holding loaded territories and regions. */
    private final MapLoaderData mapData;

    /** List of regions associated with the loaded map. */
    private final List<Region> regions;

    /**
     * Constructs a MapDisplay object, initializes the screen size,
     * loads the map file, and creates the territory grid.
     */
    public MapDisplay(SetUpData setUpData, SetUpController setUpController) {
        screen = Toolkit.getDefaultToolkit().getScreenSize();
        parent = setUpController.getDisplay();
        displayWidth = screen.width;
        displayHeight = (int) (screen.height * 0.8);
        loader = new MapLoaderService();

        // Loads map data from the selected map file.
        mapData = loader.loadTerritories(setUpData.getMap(), screen);
        territories = mapData.territories();
        regions = mapData.regions();

        // Initialize the panel that displays the map
        mapDisplay = new MapPanel(territories, setUpController);
        mapDisplay.setLayout(null);
        mapDisplay.setBounds(0, 0, displayWidth, displayHeight);

        // Button that returns program to start when pressed.
        JButton closeButton = new JButton("X");
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setBounds(screen.width - 52, 2, 50, 50);
        closeButton.addActionListener(e -> {
            setUpController.reset();
        });
        mapDisplay.add(closeButton);

        // Button that minimizes program when pressed.
        JButton minimizeButton = new JButton("-");
        minimizeButton.setFont(new Font("Arial", Font.BOLD, 14));
        minimizeButton.setBounds(screen.width - 104, 2, 50, 50);
        minimizeButton.addActionListener(e -> {
            setUpController.minimize();
        });
        mapDisplay.add(minimizeButton);

        mapDisplay.repaint();
    }

    /**
     * Adds the map display panel to the specified parent JFrame.
     *
     * @param parent the JFrame to which the map display will be added
     */
    public void addMapDisplay(JFrame parent) {
        parent.add(mapDisplay);
        parent.repaint();
    }

    /**
     * Removes the map display panel from the specified parent frame.
     *
     * @param parent the frame from which the map display will be removed
     */
    public void removeMapDisplay(Frame parent) {
        parent.remove(mapDisplay);
        parent.repaint();
    }

    /**
     * Retrieves the 2D array of territories representing the map.
     *
     * @return the territory grid
     */
    public Territory[][] getTerritories() {
        return territories;
    }

    /**
     * Retrieves the list of regions associated with the map.
     *
     * @return a list of {@link Region} objects
     */
    public List<Region> getRegions() {
        return regions;
    }

    /**
     * Retrieves the panel used to render the map.
     *
     * @return the {@link MapPanel} displaying the map
     */
    public MapPanel getMapDisplay() {
        return mapDisplay;
    }
}