package map; //rename packages

import setUpGUI.SetUpController;
import startGUI.SetUpData;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 * Represents the main map display in Battle Nations.
 *
 * <p>This class handles loading a map from a file, generating territories
 * as hexagonal tiles, and displaying them within a GUI. Each territory
 * corresponds to a specific terrain type such as mountain, desert, or city.</p>
 *
 * <p>Territories are positioned and scaled dynamically to fit the screen
 * while maintaining a hexagonal grid layout.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author Max Montowski
 */
public class MapDisplay {

    /**
     * Width of the display, based on screen size.
     */
    private final int displayWidth;

    /**
     * Height of the display, based on screen size.
     */
    private final int displayHeight;

    /**
     * Panel that renders the map and its territories.
     */
    private final MapPanel mapDisplay;

    /**
     * The screen dimensions.
     */
    private Dimension screen;

    /**
     * 2D array of territories representing the map grid.
     */
    private Territory[][] territories;

    /**
     * Parent JFrame that contains the map display.
     */
    private JFrame parent;

    private MapLoaderService loader;

    private MapLoaderData mapData;

    private List<Region> regions;


    /**
     * Constructs a MapDisplay object, initializes the screen size,
     * loads the map file, and creates the territory grid.
     */
    public MapDisplay(SetUpData setUpData, SetUpController setUpController) {
        screen = Toolkit.getDefaultToolkit().getScreenSize();
        displayWidth = screen.width;
        displayHeight = (int) (screen.height * 0.8);
        loader = new MapLoaderService();
        //startController.getGameSetUpData().getMap()

        mapData = loader.loadTerritories(setUpData.getMap(), screen);
        territories = mapData.territories();
        regions = mapData.regions();

        // Initialize the panel that displays the map
        mapDisplay = new MapPanel(territories, setUpController);
        mapDisplay.setLayout(null);
        mapDisplay.setBounds(0, 0, displayWidth, displayHeight);
        //mapDisplay.setBackground(Color.BLUE);
        mapDisplay.repaint();
    }

    /**
     * Adds the map display panel to the parent JFrame controlled by StartController.
     *
     *
     */
    public void addMapDisplay(JFrame parent) {
        parent.add(mapDisplay);
        parent.repaint();
    }

    public Territory[][] getTerritories() {
        return territories;
    }

    public List<Region> getRegions() {
        return regions;
    }

    public MapPanel getMapDisplay() {
        return mapDisplay;
    }
}