package map;

import java.util.List;

/**
 * Holds the data produced by {@link MapLoaderService} after loading a map file.
 *
 * <p>Contains the doubly indexed array of territories and the list of regions
 * that were parsed and constructed from the map text file. This data is passed
 * back to the caller and used for both gameplay logic and rendering.</p>
 *
 * <p>This class was converted from a standard class to a record after reviewing
 * scoping issues and noticing an IDE suggestion to convert. Records are ideal
 * here since {@code MapLoaderData} is purely a data carrier with no mutable
 * state or behavior.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Oracle Java Documentation –
 *   <a href="https://docs.oracle.com/en/java/javase/17/language/records.html">Records (Java SE 17)</a>
 *   Referenced to understand record class structure and when to use them.</li>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public record MapLoaderData(Territory[][] territories, List<Region> regions) {
}