package map;

import gameGUI.GameController;
import setUpGUI.SetUpController;
import terrain.WaterRouteTerrain;
import terrain.WaterTerrain;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * A custom JPanel that renders a 2D grid of territories on the map.
 *
 * <p>This panel is responsible for drawing all Territory objects provided
 * to it in a hexagonal map layout. It iterates through the 2D array of
 * territories and invokes each territory's drawing logic.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 */
public class MapPanel extends JPanel {

    /** 2D array of Territory objects to display on the map. */
    private final Territory[][] territories;

    /** Controller responsible for handling game-phase interactions. */
    private GameController gameController;

    /** Tracks which controller is currently active ("Set Up" or "Game"). */
    private String activeController;

    /**
     * Constructs a MapPanel with the specified grid of territories.
     *
     * @param territories     a 2D array of {@link Territory} objects to render
     * @param setUpController controller responsible for handling setup-phase clicks
     */
    public MapPanel(Territory[][] territories, SetUpController setUpController) {
        this.territories = territories;
        this.activeController = "Set Up";

        // Adds a mouse listener to handle clicks on the map.
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (activeController.equals("Set Up")) {
                    setUpController.dealWithClick(e.getPoint());
                } else {
                    gameController.getTerritoryClicked(e.getPoint());
                }
                repaint();


            }
        });
    }

    /**
     * Switches the panel to use the game controller for handling user interaction.
     *
     * @param gameController the controller responsible for handling game-phase input
     */
    public void switchToGameController(GameController gameController) {
        this.gameController = gameController;
        this.activeController = "Game";
    }


    /**
     * Paints the component by drawing all territories in the grid.
     *
     * <p>If the territories array is null, nothing is drawn. Otherwise,
     * each non-null Territory object in the array is drawn by calling
     * its {@code Draw(Graphics)} method.</p>
     *
     * @param g the Graphics context used for painting
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (territories == null) return;
        // First pass — draw all territories.
        for (Territory[] row : territories) {
            for (Territory territory : row) {
                if (territory != null) {
                    territory.Draw(g);
                }
            }
        }

        // Second pass — draw water borders on top so nothing covers them.
        for (Territory[] row : territories) {
            for (Territory territory : row) {
                if (territory != null && (territory.getTerrain() instanceof WaterTerrain || territory.getTerrain() instanceof WaterRouteTerrain)) {
                    g.setColor(Color.BLUE.brighter());
                    g.drawPolygon(territory.getXPoints(), territory.getYPoints(), territory.getNPoints());
                }
            }
        }
    }
}