package map;

import gameGUI.GameController;
import setUpGUI.SetUpController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * A custom JPanel that renders a 2D grid of territories on the map.
 *
 * <p>This panel is responsible for drawing all Territory objects provided
 * to it in a hexagonal map layout. It iterates through the 2D array of
 * territories and invokes each territory's drawing logic.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 *
 * @author Max Montowski
 */
public class MapPanel extends JPanel {

    /** 2D array of Territory objects to display on the map. */
    private final Territory[][] territories;

    /** The game controller used to handle clicks during gameplay. */
    private GameController gameController;

    /** Tracks which controller is currently active — either "Set Up" or "Game". */
    private String activeController;

    /**
     * Constructs a MapPanel with the specified grid of territories.
     *
     * <p>Registers a mouse listener that routes click events to either the
     * setup controller or the game controller depending on the active phase.</p>
     *
     * @param territories     a 2D array of Territory objects to render
     * @param setUpController the controller used during the setup phase
     */
    public MapPanel(Territory[][] territories, SetUpController setUpController) {
        this.territories = territories;
        this.activeController = "Set Up";

        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                // Route the click to whichever controller is currently active
                if (activeController.equals("Set Up")) {
                    setUpController.dealWithClick(e.getPoint());
                } else {
                    gameController.getTerritoryClicked(e.getPoint());
                }
                repaint();
            }
        });
    }

    /**
     * Switches the active controller from setup to gameplay.
     *
     * <p>Called once setup is complete. All subsequent clicks will be
     * routed to the game controller instead of the setup controller.</p>
     *
     * @param gameController the game controller to handle clicks during gameplay
     */
    public void switchToGameController(GameController gameController) {
        this.gameController = gameController;
        this.activeController = "Game";
    }

    /**
     * Paints the component by drawing all territories in the grid.
     *
     * <p>If the territories array is null, nothing is drawn. Otherwise,
     * each non-null Territory object in the array is drawn by calling
     * its {@code Draw(Graphics)} method.</p>
     *
     * @param g the Graphics context used for painting
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (territories == null) return;

        for (Territory[] row : territories) {
            for (Territory territory : row) {
                if (territory != null) {
                    territory.Draw(g);
                }
            }
        }
    }
}