package map;

import setUpGUI.SetUpController;
import startGUI.StartController;
import terrain.WaterRouteTerrain;
import terrain.WaterTerrain;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 * Serves as the rendering panel for regions and water-based territories in the Battle Nations GUI.
 *
 * <p>
 * This panel is responsible for visually displaying all regions and selected terrain types
 * (specifically water and water routes) on the screen. It also provides basic window controls
 * such as closing and minimizing the application.
 * </p>
 *
 * <p>
 * The panel uses a null layout for manual positioning and overrides {@link #paintComponent(Graphics)}
 * to render regions and territories dynamically.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class RegionPanel extends JPanel {

    /** List of regions to be rendered on the panel. */
    private final List<Region> regions;

    /** 2D array of territories representing the game map. */
    private final Territory[][] territories;

    /**
     * Constructs a RegionPanel and initializes rendering data and UI controls.
     *
     * <p>
     * This includes storing the provided territories and regions, setting up the panel layout,
     * and adding control buttons for closing and minimizing the application window.
     * </p>
     *
     * @param territories     the 2D array of territories to be displayed
     * @param regions         the list of regions to be rendered
     * @param setUpController controller used to handle reset and minimize actions
     */
    public RegionPanel(Territory[][] territories, List<Region> regions, SetUpController setUpController) {
        this.territories = territories;
        this.regions = regions;

        //Sets layout to null and gets screen size.
        this.setLayout(null);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();

        // Button that returns program to start when pressed.
        JButton closeButton = new JButton("X");
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setBounds(screen.width - 52, 2, 50, 50);
        closeButton.addActionListener(e -> {
            setUpController.reset();
        });
        this.add(closeButton);

        // Button that minimizes program when pressed.
        JButton minimizeButton = new JButton("-");
        minimizeButton.setFont(new Font("Arial", Font.BOLD, 14));
        minimizeButton.setBounds(screen.width - 104, 2, 50, 50);
        minimizeButton.addActionListener(e -> {
            setUpController.minimize();
        });
        this.add(minimizeButton);
    }

    /**
     * Paints all regions and selected terrain types onto the panel.
     *
     * <p>
     * This method is called automatically whenever the panel needs to be redrawn.
     * It first renders all regions, then overlays water and water route territories
     * to ensure they appear above other elements.
     * </p>
     *
     * @param g the {@link Graphics} object used for drawing
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Draw all regions and their territories first
        for (Region region : regions) {
            region.draw(g);
        }

        // First pass — fill all water and water route territories
        for (Territory[] row : territories) {
            for (Territory t : row) {
                if (t != null && (t.getTerrain() instanceof WaterTerrain || t.getTerrain() instanceof WaterRouteTerrain)) {
                    t.Draw(g);
                }
            }
        }

        // Second pass — redraw water borders on top so they are never covered
        for (Territory[] row : territories) {
            for (Territory t : row) {
                if (t != null && (t.getTerrain() instanceof WaterTerrain || t.getTerrain() instanceof WaterRouteTerrain)) {
                    g.setColor(Color.BLUE.brighter());
                    g.drawPolygon(t.getXPoints(), t.getYPoints(), t.getNPoints());
                }
            }
        }
    }
}
