package map;

import player.Player;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a region in Battle Nations.
 *
 * <p>A region is a collection of {@link Territory} objects. Regions are used
 * to group territories together and determine control bonuses or strategic
 * advantages during gameplay.</p>
 *
 * <p>A region is considered conquered when all territories within the region
 * are owned by the same player.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author J.D. Reighard
 * @version 1.0
 * @since 2026-03-04
 */
public class Region {
    /**
     * The list of territories that belong to this region.
     */
    private final List<Territory> territories;

    /**
     * The regions color.
     */
    private Color color;

    /**
     * Constructs a region with a predefined list of territories.
     *
     * @param territories the territories that make up the region
     */
    public Region(List<Territory> territories) {
        this.territories = new ArrayList<>(territories);
        ensureSingleCapitalTerritory();
    }

    public Region() {
        this.territories = new ArrayList<>();
    }

    private void ensureSingleCapitalTerritory() {
        int capitalCount = 0;
        for (Territory territory : territories) {
            if (territory.isCapital()) {
                capitalCount++;
            }
        }
        if (capitalCount > 1) { //changed this from != too >
            throw new IllegalStateException("Region should always have 1 and only 1 capital territory");
        }
    }

    /**
     * Determines whether the region has been conquered by a single player.
     *
     * <p>A region is conquered when all territories are owned by the same player.</p>
     *
     * @return true if all territories in the region are owned by the same player,
     * false otherwise
     */
    public boolean isRegionConquered() {
        if (territories.isEmpty()) {
            return false;
        }
        Player firstPlayer = territories.get(0).getPlayer();
        if (firstPlayer == null) {
            return false;
        }

        for (int i = 1; i < territories.size(); i++) {
            if (!firstPlayer.equals(territories.get(i).getPlayer())) {
                return false;
            }
        }

        return true;
    }

    public Player getPlayerConqueredRegion() {
        if (isRegionConquered()) {
            return territories.get(0).getPlayer();
        }
        return null;
    }

    /**
     * Adds a territory to the region.
     *
     * @param territory the territory to add
     */
    public void addTerritory(Territory territory) {
        territories.add(territory);
        ensureSingleCapitalTerritory();
    }

    /**
     * Removes a territory from the region.
     *
     * @param territory the territory to remove
     */
    public void removeTerritory(Territory territory) {
        territories.remove(territory);
    }

    /**
     * Clears a regions territories.
     */
    public void clearRegion() {
        this.territories.clear();
    }

    /**
     * Returns the number of territories in the region.
     *
     * @return the size of the region
     */
    public int getSize() {
        return territories.size();
    }

    /**
     * Returns the list of territories belonging to this region.
     *
     * @return the territories in the region
     */
    public List<Territory> getTerritories() {
        return territories;
    }

    public Territory getCapitalTerritory() {
        for (Territory territory : territories) {
            if (territory.isCapital()) {
                return territory;
            }
        }
        return null;
    }

    /**
     * Checks whether the specified territory belongs to the region.
     *
     * @param territory the territory to check
     * @return true if the region contains the territory, false otherwise
     */
    public boolean hasTerritory(Territory territory) {
        return territories.contains(territory);
    }

    /**
     * Sets the color of the region to the specified color
     *
     * @param color the color the region will assign to its color variable
     */
    public void setColor(Color color) {
        this.color = color;
    }

    /**
     * Draws the regions ont the game map.
     *
     * @param g the graphics context used for rendering
     */
    public void draw(Graphics g) {
        g.setColor(color);
        for (Territory t : territories) {
            int[] xpoints = t.getXPoints();
            int[] ypoints = t.getYPoints();
            int npoints = t.getNPoints();

            g.drawPolygon(xpoints, ypoints, npoints);
            g.setColor(color.brighter());

            g.fillPolygon(xpoints, ypoints, npoints);
            ImageIcon watermarkIcon = new ImageIcon(t.getTerrain().getImageFile());
            Image watermark = watermarkIcon.getImage();
            int xLeft = xpoints[1];
            int xRight = xpoints[2];
            int yTop = ypoints[2];
            int yBottom = ypoints[5];
            g.drawImage(watermark, xLeft, yTop, xRight - xLeft, yBottom - yTop, g.getColor(), null);

        }
    }
}

