package map;

import setUpGUI.SetUpController;
import terrain.WaterRouteTerrain;
import terrain.WaterTerrain;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 * A custom JPanel that renders all regions and water territories on the map.
 *
 * <p>This panel draws each region using its assigned color and terrain images,
 * then draws water and water route territories on top to ensure they are always
 * rendered above region fills.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 *
 * @author Max Montowski
 */
public class RegionPanel extends JPanel {

    /** The list of regions to draw on this panel. */
    private final List<Region> regions;

    /** The 2D territory grid used to identify water territories for rendering. */
    private final Territory[][] territories;

    /**
     * Constructs a RegionPanel with the given territory grid and region list.
     *
     * <p>Adds close and minimize buttons to the panel for window management.</p>
     *
     * @param territories     the 2D array of territories on the map
     * @param regions         the list of regions to render
     * @param setUpController the controller used to handle reset and minimize actions
     */
    public RegionPanel(Territory[][] territories, List<Region> regions, SetUpController setUpController) {
        this.territories = territories;
        this.regions = regions;

        this.setLayout(null);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();

        // Button that returns program to start when pressed
        JButton closeButton = new JButton("X");
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setBounds(screen.width - 52, 2, 50, 50);
        closeButton.addActionListener(e -> {
            setUpController.reset();
        });
        this.add(closeButton);

        // Button that minimizes program when pressed
        JButton minimizeButton = new JButton("-");
        minimizeButton.setFont(new Font("Arial", Font.BOLD, 14));
        minimizeButton.setBounds(screen.width - 104, 2, 50, 50);
        minimizeButton.addActionListener(e -> {
            setUpController.minimize();
        });
        this.add(minimizeButton);
    }

    /**
     * Paints the panel by drawing all regions followed by all water territories.
     *
     * <p>Regions are drawn first so that water and water route territories
     * are always rendered on top, preventing them from being obscured
     * by region fills.</p>
     *
     * @param g the graphics context used for rendering
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Draw all regions and their territories first
        for (Region region : regions) {
            region.draw(g);
        }

        // Draw water and water route territories on top so they are never obscured by region colors
        for (Territory[] row : territories) {
            for (Territory t : row) {
                if (t != null && (t.getTerrain() instanceof WaterTerrain || t.getTerrain() instanceof WaterRouteTerrain)) {
                    t.Draw(g);
                }
            }
        }
    }
}