package map;

import player.Player;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a region in Battle Nations.
 *
 * <p>A region is a collection of {@link Territory} objects. Regions are used
 * to group territories together and determine control bonuses or strategic
 * advantages during gameplay.</p>
 *
 * <p>A region is considered conquered when all territories within the region
 * are owned by the same player.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class Region {

    /** The list of territories that belong to this region. */
    private final List<Territory> territories;

    /** The display color assigned to this region. */
    private Color color;

    /**
     * Constructs a region with a predefined list of territories.
     *
     * @param territories the territories that make up the region
     */
    public Region(List<Territory> territories) {
        this.territories = new ArrayList<>(territories);
        ensureSingleCapitalTerritory();
    }

    /**
     * Constructs an empty region with no territories.
     */
    public Region() {
        this(new ArrayList<>());
    }

    /**
     * Validates that the region contains at most one capital territory.
     *
     * <p>Throws an {@link IllegalStateException} if more than one capital
     * territory is found in the region.</p>
     */
    private void ensureSingleCapitalTerritory() {
        int capitalCount = 0;
        for (Territory territory : territories) {
            if (territory.isCapital()) {
                capitalCount++;
            }
        }
        // A region may have zero or one capital — more than one is invalid
        if (capitalCount > 1) {
            throw new IllegalStateException("Region should always have 1 and only 1 capital territory");
        }
    }

    /**
     * Determines whether the region has been conquered by a single player.
     *
     * <p>A region is conquered when all territories are owned by the same player.</p>
     *
     * @return true if all territories in the region are owned by the same player,
     * false otherwise
     */
    public boolean isRegionConquered() {
        if (territories.isEmpty()) {
            return false;
        }

        Player firstPlayer = territories.get(0).getPlayer();

        // If the first territory has no owner the region cannot be conquered
        if (firstPlayer == null) {
            return false;
        }

        for (int i = 1; i < territories.size(); i++) {
            // If any territory belongs to a different player the region is not conquered
            if (!firstPlayer.equals(territories.get(i).getPlayer())) {
                return false;
            }
        }

        return true;
    }

    /**
     * Returns the player who has conquered this region, or null if it is not conquered.
     *
     * @return the conquering player, or null if the region is not fully owned
     */
    public Player getPlayerConqueredRegion() {
        if (isRegionConquered()) {
            return territories.get(0).getPlayer();
        }
        return null;
    }

    /**
     * Adds a territory to the region.
     *
     * @param territory the territory to add
     */
    public void addTerritory(Territory territory) {
        territories.add(territory);
        ensureSingleCapitalTerritory();
    }

    /**
     * Removes a territory from the region.
     *
     * @param territory the territory to remove
     */
    public void removeTerritory(Territory territory) {
        territories.remove(territory);
    }

    /**
     * Clears all territories from the region.
     */
    public void clearRegion() {
        this.territories.clear();
    }

    /**
     * Returns the number of territories in the region.
     *
     * @return the size of the region
     */
    public int getSize() {
        return territories.size();
    }

    /**
     * Returns the list of territories belonging to this region.
     *
     * @return the territories in the region
     */
    public List<Territory> getTerritories() {
        return territories;
    }

    /**
     * Returns the capital territory of this region, or null if none exists.
     *
     * @return the capital territory, or null if the region has no capital
     */
    public Territory getCapitalTerritory() {
        for (Territory territory : territories) {
            if (territory.isCapital()) {
                return territory;
            }
        }
        return null;
    }

    /**
     * Checks whether the specified territory belongs to the region.
     *
     * @param territory the territory to check
     * @return true if the region contains the territory, false otherwise
     */
    public boolean hasTerritory(Territory territory) {
        return territories.contains(territory);
    }

    /**
     * Sets the display color of this region.
     *
     * @param color the color to assign to this region
     */
    public void setColor(Color color) {
        this.color = color;
    }

    /**
     * Draws all territories in this region onto the game map.
     *
     * <p>Each territory is filled with the region color, outlined with a darker
     * shade, and overlaid with its terrain image. Capital territories also have
     * a star drawn on top.</p>
     *
     * @param g the graphics context used for rendering
     */
    public void draw(Graphics g) {
        // First pass — fill all territories
        for (Territory t : territories) {
            int[] xpoints = t.getXPoints();
            int[] ypoints = t.getYPoints();
            int npoints = t.getNPoints();

            g.setColor(color.darker());
            g.fillPolygon(xpoints, ypoints, npoints);

            // Draw terrain image
            ImageIcon watermarkIcon = new ImageIcon(t.getTerrain().getImageFile());
            Image watermark = watermarkIcon.getImage();
            int xLeft = xpoints[1];
            int xRight = xpoints[2];
            int yTop = ypoints[2];
            int yBottom = ypoints[5];
            g.drawImage(watermark, xLeft, yTop, xRight - xLeft, yBottom - yTop, g.getColor(), null);

            if (t.isCapital()) {
                t.drawCapitalStar(g);
            }
        }

        // Second pass — draw all borders on top so they are never covered by a fill
        for (Territory t : territories) {
            int[] xpoints = t.getXPoints();
            int[] ypoints = t.getYPoints();
            int npoints = t.getNPoints();

            g.setColor(color.brighter());
            g.drawPolygon(xpoints, ypoints, npoints);
        }
    }

    /**
     * Returns the display name of this region's color.
     *
     * <p>Maps known Color values to their string names. Returns "Unknown"
     * if the color does not match any recognized value.</p>
     *
     * @return the name of the region's color
     */
    public String getColorName() {
        if (color == null) return "Unknown";
        if (color.equals(Color.RED)) return "Red";
        if (color.equals(Color.CYAN)) return "Cyan";
        if (color.equals(Color.GREEN)) return "Green";
        if (color.equals(Color.YELLOW)) return "Yellow";
        if (color.equals(Color.MAGENTA)) return "Magenta";
        if (color.equals(new Color(215, 86, 36))) return "Orange";
        if (color.equals(new Color(100, 0, 255))) return "Purple";
        if (color.equals(Color.GRAY)) return "Gray";
        if (color.equals(new Color(0, 100, 0))) return "Dark Green";
        return "Unknown";
    }
}