package map;

import player.Player;

import java.awt.*;

/**
 * Represents a territory in Battle Nations.
 *
 * <p>A territory is a polygon on the game map that belongs to a {@link Region}.
 * Each territory may be owned by a {@link Player}, contains a {@link Terrain}
 * type, and stores the number of troops currently stationed there.</p>
 *
 * <p>The polygon coordinates define the visual shape of the territory when
 * rendered on the game board.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author J.D. Reighard
 * @version 1.0
 * @since 2026-03-04
 */
public class Territory extends Polygon implements Comparable<Territory> {
    /**
     * The player that currently owns this territory.
     */
    private Player player;
    /**
     * The terrain type associated with this territory.
     */
    private final Terrain terrain;
    /**
     * The number of troops stationed in the territory.
     */
    private int troopAmount;
    /**
     * Indicates whether the territory currently belongs to a player.
     */
    private boolean isPlayerOwned;


    /**
     * Constructs a territory owned by a player.
     *
     * @param player      the player that owns the territory
     * @param terrain     the terrain type of the territory
     * @param troopAmount the number of troops stationed in the territory
     * @param xCoords     the x-coordinates defining the polygon shape
     * @param yCoords     the y-coordinates defining the polygon shape
     */
    public Territory(Player player, Terrain terrain, int troopAmount, int[] xCoords, int[] yCoords) {
        this.player = player;
        this.terrain = terrain;
        this.troopAmount = troopAmount;
        super.xpoints = xCoords;
        super.ypoints = yCoords;
        this.isPlayerOwned = true;
    }

    /**
     * Constructs an unowned territory with a terrain type (Going to be used for water hexagons).
     *
     * @param terrain the terrain type of the territory
     * @param xCoords the x-coordinates defining the polygon shape
     * @param yCoords the y-coordinates defining the polygon shape
     */
    public Territory(Terrain terrain, int[] xCoords, int[] yCoords) {
        this.terrain = terrain;
        super.xpoints = xCoords;
        super.ypoints = yCoords;
        this.isPlayerOwned = false;
    }

    /**
     * Returns the number of troops stationed in the territory.
     *
     * @return the troop count
     */
    public int getTroopAmount() {
        return troopAmount;
    }

    /**
     * Returns the color used to represent the territory on the map.
     *
     * <p>If the territory has no owner, a default color is returned.</p>
     *
     * @return the color representing the territory's owner
     */
    public Color getCurrentColor() {
        if (player == null) {
            return Color.BLUE;
        }
        return player.getColor();
    }

    /**
     * Returns the player that owns the territory.
     *
     * @return the owning player
     */
    public Player getPlayer() {
        return player;
    }

    /**
     * Returns the terrain associated with the territory.
     *
     * @return the terrain type
     */
    public Terrain getTerrain() {
        return terrain;
    }

    /**
     * Indicates whether the territory is currently owned by a player.
     *
     * @return true if the territory has an owner, false otherwise
     */
    public boolean getIsPlayerOwned() {
        return isPlayerOwned;
    }

    /**
     * Sets the player that owns the territory.
     *
     * @param player the new owner of the territory
     */
    public void setPlayer(Player player) {
        this.player = player;
    }

    /**
     * Sets the number of troops stationed in the territory.
     *
     * @param troopAmount the new troop count
     */
    public void setTroopAmount(int troopAmount) {
        this.troopAmount = troopAmount;
    }

    /**
     * Updates whether the territory is owned by a player.
     *
     * @param isPlayerOwned true if the territory is owned, false otherwise
     */
    public void setIsPlayerOwned(boolean isPlayerOwned) {
        this.isPlayerOwned = isPlayerOwned;
    }

    /**
     * Draws the territory polygon onto the game map.
     *
     * @param g the graphics context used for rendering
     */
    public void Draw(Graphics g) {
        g.setColor(this.getCurrentColor());
        g.drawPolygon(super.xpoints, super.ypoints, super.xpoints.length);
        g.fillPolygon(super.xpoints, super.ypoints, super.xpoints.length);
    }

    /**
     * Compares territories based on their troop counts.
     *
     * @param other the territory to compare against
     * @return a positive number if this territory has more troops,
     * zero if equal, or a negative number if fewer troops
     */
    @Override
    public int compareTo(Territory other) {
        if (this.troopAmount > other.troopAmount) {
            return 1;
        } else if (this.troopAmount == other.troopAmount) {
            return 0;
        } else {
            return -1;
        }
    }


    /**
     * Returns a string representation of the territory.
     *
     * @return a formatted description of the territory
     */
    @Override
    public String toString() {
        return ("Territory ID: " + "add id" + " Player: " + player.getName() + " Troop Count: " + troopAmount);
    }
}
