package map;

/**
 * Represents a terrain type used by territories in Battle Nations.
 *
 * <p>Terrain defines combat bonuses and potential troop bonuses that
 * affect gameplay. Each concrete terrain type provides its own values
 * for attack bonuses, defense bonuses, and troop bonuses.</p>
 *
 * <p>Terrain objects also store the image file used to visually represent
 * the terrain on the game map.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author J.D. Reighard
 * @version 1.0
 * @since 2026-03-04
 */
public abstract class Terrain {
    /**
     * The percentage attack bonus provided by this terrain.
     */
    protected final double attackBonusPercentage;
    /**
     * The percentage defense bonus provided by this terrain.
     */
    protected final double defenseBonusPercentage;
    /**
     * Additional troops granted by this terrain.
     */
    protected final int troopBonus;
    /**
     * The image file used to represent the terrain on the game map.
     */
    protected final String imageFile;

    /**
     * Constructs a Terrain object with the specified bonuses and image.
     *
     * @param attackBonusPercentage  the attack bonus percentage provided by the terrain
     * @param defenseBonusPercentage the defense bonus percentage provided by the terrain
     * @param imageFile              the image file used to represent the terrain
     * @param troopBonus             additional troops granted by the terrain
     */
    public Terrain(double attackBonusPercentage, double defenseBonusPercentage, String imageFile, int troopBonus) {
        this.attackBonusPercentage = attackBonusPercentage;
        this.defenseBonusPercentage = defenseBonusPercentage;
        this.troopBonus = troopBonus;
        this.imageFile = imageFile;
    }

    /**
     * @return the terrain's attack bonus percentage
     */
    public double getAttackBonus() {
        return attackBonusPercentage;
    }

    /**
     * @return the terrain's defense bonus percentage
     */
    public double getDefenseBonus() {
        return defenseBonusPercentage;
    }

    /**
     * @return the additional troops granted by this terrain
     */
    public int getTroopBonus() {
        return troopBonus;
    }

    /**
     * @return the image file used to display the terrain
     */
    public String getImageFile() {
        return imageFile;
    }
}
