package map;

import player.Player;
import terrain.Terrain;
import terrain.WaterRouteTerrain;
import terrain.WaterTerrain;

import javax.swing.*;
import java.awt.*;
import java.awt.font.FontRenderContext;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a territory in Battle Nations.
 *
 * <p>A territory is a polygon on the game map that belongs to a {@link Region}.
 * Each territory may be owned by a {@link Player}, contains a {@link Terrain}
 * type, and stores the number of troops currently stationed there.</p>
 *
 * <p>Territories also maintain a list of neighboring territories, which is used
 * to determine valid actions such as attacking and fortifying.</p>
 *
 * <p>The polygon coordinates define the visual shape of the territory when
 * rendered on the game board.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class Territory extends Polygon {
    /**
     * The player that currently owns this territory.
     */
    private Player player;

    /**
     * The terrain type associated with this territory.
     */
    private final Terrain terrain;

    /**
     * The number of troops stationed in the territory.
     */
    private int troopAmount;

    /**
     * boolean to see if a Territory is a capital or not
     */
    private final boolean isCapital;

    /**
     * The list of neighboring territories
     */
    private final List<Territory> neighboringTerritories;

    private boolean isHighlighted = false;

    /**
     * Constructs a territory owned by a player.
     *
     * @param player      the player that owns the territory
     * @param terrain     the terrain type of the territory
     * @param troopAmount the number of troops stationed in the territory
     * @param xCoords     the x-coordinates defining the polygon shape
     * @param yCoords     the y-coordinates defining the polygon shape
     * @param isCapital   whether this territory is a capital
     */
    public Territory(Player player, Terrain terrain, int troopAmount, int[] xCoords, int[] yCoords, boolean isCapital) {
        this(terrain, xCoords, yCoords, isCapital);
        this.player = player;
        this.troopAmount = troopAmount;
    }

    /**
     * Constructs an unowned territory with a terrain type.
     *
     * <p>This constructor is typically used for neutral or water territories.</p>
     *
     * @param terrain   the terrain type of the territory
     * @param xCoords   the x-coordinates defining the polygon shape
     * @param yCoords   the y-coordinates defining the polygon shape
     * @param isCapital whether this territory is a capital
     */
    public Territory(Terrain terrain, int[] xCoords, int[] yCoords, boolean isCapital) {
        this.terrain = terrain;
        super.xpoints = xCoords;
        super.ypoints = yCoords;
        super.npoints = xCoords.length;
        this.isCapital = isCapital;
        this.player = null;
        this.troopAmount = 0;
        this.neighboringTerritories = new ArrayList<>();
    }

    /**
     * Returns the number of troops stationed in the territory.
     *
     * @return the troop count
     */
    public int getTroopAmount() {
        return troopAmount;
    }

    /**
     * Returns the color used to represent the territory on the map.
     *
     * <p>If the territory has no owner, a default color is returned.</p>
     *
     * @return the color representing the territory's owner, or null if territory not assigned
     */
    public Color getCurrentColor() {
        if (player == null) {
            return null;
        }
        return player.getColor();
    }

    /**
     * Returns the player that owns the territory.
     *
     * @return the owning player, or null if no player is assigned
     */
    public Player getPlayer() {
        return player;
    }

    /**
     * Returns the terrain associated with the territory.
     *
     * @return the terrain type
     */
    public Terrain getTerrain() {
        return terrain;
    }

    public boolean isHighlighted() {
        return isHighlighted;
    }

    /**
     * Returns the X points associated with the territory
     *
     * @return the int array of x points
     */
    public int[] getXPoints() {
        return xpoints;
    }

    /**
     * Returns the Y points associated with the territory
     *
     * @return the int array of y points
     */
    public int[] getYPoints() {
        return ypoints;
    }

    /**
     * returns the int value of how many points the polygon has
     *
     * @return the int value of the number of points the polygon has
     */
    public int getNPoints() {
        return npoints;
    }

    /**
     * Returns whether this territory is designated as a capital.
     *
     * @return {@code true} if this territory is a capital; {@code false} otherwise
     */
    public boolean isCapital() {
        return isCapital;
    }

    public void setIsHighlighted(boolean isHighlighted) {
        this.isHighlighted = isHighlighted;
    }

    /**
     * Sets the player that owns the territory.
     *
     * @param player the new owner of the territory
     */
    public void setPlayer(Player player) {
        this.player = player;
    }

    /**
     * Sets the number of troops stationed in the territory.
     *
     * @param troopAmount the new troop count
     */
    public void setTroopAmount(int troopAmount) {
        this.troopAmount = troopAmount;
    }

    /**
     * Draws the territory polygon onto the game map.
     *
     * @param g the graphics context used for rendering
     */
    public void Draw(Graphics g) {
        if (isHighlighted) {
            g.setColor(Color.WHITE);
        } else if (this.getCurrentColor() != null) {
            g.setColor(this.getCurrentColor());
        } else {
            g.setColor(Color.DARK_GRAY);
        }
        g.drawPolygon(super.xpoints, super.ypoints, super.xpoints.length);
        if (isHighlighted) {
            g.setColor(Color.WHITE);
        } else if (this.getCurrentColor() != null) {
            g.setColor(this.getCurrentColor().brighter());
        } else {
            if (this.getTerrain() instanceof WaterTerrain || this.getTerrain() instanceof WaterRouteTerrain) {
                g.setColor(Color.BLUE);
            } else {
                g.setColor(Color.LIGHT_GRAY);
            }
        }

        g.fillPolygon(super.xpoints, super.ypoints, super.xpoints.length);
        ImageIcon watermarkIcon = new ImageIcon(this.getTerrain().getImageFile());
        Image watermark = watermarkIcon.getImage();
        int xLeft = super.xpoints[1];
        int xRight = super.xpoints[2];
        int yTop = super.ypoints[2];
        int yBottom = super.ypoints[5];
        g.drawImage(watermark, xLeft, yTop, xRight - xLeft, yBottom - yTop, g.getColor(), null);

        int xCenter = (xRight + xLeft) / 2;
        int yCenter = (yTop + yBottom) / 2;
        int radius = (xRight - xLeft) / 4;

        g.setColor(Color.BLACK);
        if (this.isCapital()) {
            drawCapitalStar(g);
        }

        // Compute middle, then draw circle of color, then draw string in middle of circle.
        if (this.getPlayer() != null) {
            g.setColor(player.getColor().darker());
            g.fillOval(xCenter - radius, yCenter - radius, 2 * radius, 2 * radius);
            g.setColor(Color.WHITE);

            boolean smallEnough = false;
            int startingFontSize = 18;
            Graphics2D g2 = (Graphics2D) g;
            String troopCount = String.valueOf(this.troopAmount);
            Font numberFont = null;
            Rectangle2D dimentions = null;
            while (!smallEnough) {
                numberFont = new Font("Arial", Font.BOLD, startingFontSize);
                FontRenderContext fontRenderContext = g2.getFontRenderContext();
                dimentions = numberFont.getStringBounds(troopCount, fontRenderContext);
                if (dimentions.getWidth() < 2 * radius) {
                    smallEnough = true;
                } else {
                    startingFontSize--;
                }
            }
            g.setFont(numberFont);
            g.drawString(troopCount, xCenter - (int) (dimentions.getWidth() / 2), yCenter + (int) (dimentions.getHeight() / 4));
        }
    }

    public void drawCapitalStar(Graphics g) {
        double[] xStarPoints = new double[3];
        double[] yStarPoints = new double[3];
        int[] insideHexegonX = new int[5];
        int[] insideHexegonY = new int[5];
        int xLeft = super.xpoints[1];
        int xRight = super.xpoints[2];
        int yTop = super.ypoints[2];
        int yBottom = super.ypoints[5];
        int xCenter = (xRight + xLeft) / 2;
        int yCenter = (yTop + yBottom) / 2;
        int radius = (xRight - xLeft) / 4;

        g.setColor(Color.BLACK);
        for (int i = 0; i < 5; i++) {
            xStarPoints[0] = xCenter + radius * Math.cos(((2 * Math.PI * i) / 5) - (3 * Math.PI / 10));
            xStarPoints[1] = xCenter + radius * Math.cos(((2 * Math.PI * (i + 1)) / 5) - (3 * Math.PI / 10));

            yStarPoints[0] = yCenter + radius * Math.sin(((2 * Math.PI * (i)) / 5) - (3 * Math.PI / 10));
            yStarPoints[1] = yCenter + radius * Math.sin(((2 * Math.PI * (i + 1)) / 5) - (3 * Math.PI / 10));

            double midleX = (xStarPoints[0] + xStarPoints[1]) / 2;
            double midleY = (yStarPoints[0] + yStarPoints[1]) / 2;

            double changeX = (xCenter - midleX);
            double changeY = (yCenter - midleY);

            xStarPoints[2] = changeX * (-2) + midleX;
            yStarPoints[2] = changeY * (-2) + midleY;


            int[] xPoints = new int[3];
            int[] yPoints = new int[3];
            for (int k = 0; k < 3; k++) {
                // Converts the double values into int values by rounding so that the values can be used for drawing
                // in java swing.
                xPoints[k] = (int) Math.round(xStarPoints[k]);
                yPoints[k] = (int) Math.round(yStarPoints[k]);
            }
            insideHexegonX[i] = xPoints[0];
            insideHexegonY[i] = yPoints[0];
            g.fillPolygon(xPoints, yPoints, 3);


        }
        if (this.getPlayer() == null) {
            g.fillPolygon(insideHexegonX, insideHexegonY, 5);
        }
        drawCenterCircle(g);
    }

    private void drawCenterCircle(Graphics g) {
        int xLeft = super.xpoints[1];
        int xRight = super.xpoints[2];
        int yTop = super.ypoints[2];
        int yBottom = super.ypoints[5];

        int xCenter = (xRight + xLeft) / 2;
        int yCenter = (yTop + yBottom) / 2;
        int radius = (xRight - xLeft) / 4;

        g.setColor(Color.BLACK);
        g.fillOval(xCenter - radius, yCenter - radius, 2 * radius, 2 * radius);
    }

    /**
     * Returns a string representation of the territory.
     *
     * @return a formatted description of the territory
     */
    @Override
    public String toString() {
        return "Player: " + (player != null ? player.getName() : "None")
                + " Troop Count: " + troopAmount;
    }

    /**
     * Adds a neighboring territory.
     *
     * <p>This is used during map initialization to establish adjacency
     * relationships between territories.</p>
     *
     * @param t the neighboring territory to add
     */
    public void addToTerritoryNeighbors(Territory t) {
        neighboringTerritories.add(t);
    }

    /**
     * Returns all neighboring territories.
     *
     * @return the list of adjacent territories
     */
    public List<Territory> getNeighboringTerritories() {
        return neighboringTerritories;
    }

    /**
     * Determines whether the given territory is adjacent to this one.
     *
     * @param t the territory to check
     * @return {@code true} if the territories are neighbors; {@code false} otherwise
     */
    public boolean hasNeighbor(Territory t) {
        return (neighboringTerritories.contains(t));
    }
}
