package map;

import player.Player;
import terrain.TerrainType;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static java.awt.Color.*;

/**
 * Tests the core behavior of the {@link Region} class.
 *
 * <p>This test class verifies region initialization, territory addition,
 * and conquered-region logic. Each test method prints whether it passed
 * or failed and returns a boolean result.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Google AI Overview – Referenced for the use of
 *   Collections.addAll(list, "item1", "item2", "item3") when adding
 *   multiple elements to a list at once for my test code.</li>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 * <p><b>Note:</b> Test code may still be a work in progress.</p>
 *
 * @author J.D. Reighard
 * @version 1.0
 * @since 2026-03-04
 */
public class TestRegion {

    /**
     * Runs all Region test methods and prints an overall result.
     *
     * @param args command-line arguments not used by this program
     */
    public static void main(String[] args) {
        boolean passed = true;
        System.out.println("Testing Methods");
        if (!testMultipleTerritoriesInit()) passed = false;
        if (!testAddTerritory()) passed = false;
        if (!testIsRegionConquered()) passed = false;
        if (passed) {
            System.out.println("All Tests Passed");
        } else {
            System.err.println("At least one Test Failed");
        }
    }


    /**
     * Tests that a Region initializes correctly with multiple territories.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testMultipleTerritoriesInit() {
        boolean passed = true;
        System.out.print("Testing Initializer with multiple territores as paramater: ");
        // setting up all required elements for a region
        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);
        Territory t2 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 10,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.DESERT.getTerrain(), 30,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t4 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 50,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t5 = new Territory(player, TerrainType.CITY.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        List<Territory> temp = new ArrayList<>();
        Collections.addAll(temp, t1, t2, t3, t4, t5);
        int regionSize = temp.size();

        // add all territories to a region
        Region region = new Region(temp);
        if (region.getSize() != regionSize) {
            passed = false;
            System.err.println("Region was not the proper size");
        }

        if (!temp.equals(region.getTerritories())) {
            passed = false;
            System.err.println("regions territories are not the same as what was passed into initializer");
        }

        for (Territory t : temp) {
            if (!region.hasTerritory(t)) {
                passed = false;
                System.err.println("A territory was not found in the region");
            }
        }
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that territories can be added to a Region and that the
     * region size updates correctly.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testAddTerritory() {
        boolean passed = true;
        System.out.print("testing addTerritory Method: ");
        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);

        List<Territory> territories = new ArrayList<>();
        territories.add(t1);
        Region region = new Region(territories);
        int size = region.getSize();
        if (size != 1) {
            System.err.println("Error has occurred in region initializer. Test cannot be ran");
            return false;
        }
        Territory t2 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        region.addTerritory(t2);
        size++;
        if (region.getSize() != size) {
            passed = false;
            System.err.println("Regions size did not grow properly when adding a territory");
        }

        for (int i = 0; i < 100; i++) {
            Territory temp = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                    new int[]{1, 2, 3, 4, 5, 6},
                    new int[]{1, 2, 3, 4, 5, 6}, false);
            region.addTerritory(temp);
            size++;
            if (region.getSize() != size) {
                passed = false;
                System.err.println("Region size did not properly grow when adding territories in a loop");
            }

            if (!region.hasTerritory(temp)) {
                passed = false;
                System.err.println("Region does not have newly added territory in loop");
            }
        }
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests whether a Region is correctly identified as conquered when all
     * territories belong to the same player, and not conquered when multiple
     * players own territories in the region.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testIsRegionConquered() {
        boolean passed = true;
        System.out.print("testing isRegionConquered Method: ");

        Player bluePlayer = new Player("p1", BLUE);
        Territory t1 = new Territory(bluePlayer, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);

        List<Territory> territories = new ArrayList<>();
        territories.add(t1);
        Region region = new Region(territories);
        if (!region.isRegionConquered()) {
            passed = false;
            System.err.println("Region was not conquered when there was only 1 territory in the region");
        }

        Player redPlayer = new Player("p2", RED);
        for (int i = 0; i < 100; i++) {
            Territory temp = new Territory(redPlayer, TerrainType.DESERT.getTerrain(), 20,
                    new int[]{1, 2, 3, 4, 5, 6},
                    new int[]{1, 2, 3, 4, 5, 6}, false);
            region.addTerritory(temp);

            if (region.isRegionConquered()) {
                passed = false;
                System.err.println("Region was conquered when territories were owned by both red and blue players");
            }
        }

        t1.setPlayer(redPlayer);

        if (!region.isRegionConquered()) {
            passed = false;
            System.err.println("Region was not flagged as conquered when territories were all owned by red player");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Placeholder for future testing of region.clearRegion().
     *
     * @return false until implemented
     */
    private static boolean testClearRegion() {
        boolean passed = true;
        System.out.print("Testing Initializer with multiple territores as paramater: ");
        // setting up all required elements for a region
        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);
        Territory t2 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 10,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.DESERT.getTerrain(), 30,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t4 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 50,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t5 = new Territory(player, TerrainType.CITY.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        List<Territory> temp = new ArrayList<>();
        Collections.addAll(temp, t1, t2, t3, t4, t5);
        int regionSize = temp.size();

        // add all territories to a region
        Region region = new Region(temp);

        region.clearRegion();
        if (region.getSize() != 0) {
            passed = false;
            System.err.println("The size of the region was not zero after the clear.");
        }
        return passed;

        if (region.hasTerritory(t1) || region.hasTerritory(t2) || region.hasTerritory(t3) ||
                region.hasTerritory(t4) || region.hasTerritory(t5)) {
            passed = false;
            System.err.println("");
        }
    }

    /**
     * Placeholder for future testing of Region.hasTerritory().
     *
     * @return false until implemented
     */
    private static boolean testHasTerritory() {
        return false;
    }

    private static boolean testSingleCapitalTerritory() {
        return false;
    }
}
