package map;

import player.Player;
import terrain.TerrainType;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static java.awt.Color.BLUE;
import static java.awt.Color.RED;

/**
 * Tests the core behavior of the {@link Region} class.
 *
 * <p>This test class verifies region initialization, territory addition,
 * and conquered-region logic. Each test method prints whether it passed
 * or failed and returns a boolean result.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Google AI Overview – Referenced for the use of
 *   Collections.addAll(list, "item1", "item2", "item3") when adding
 *   multiple elements to a list at once for my test code.</li>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class TestRegion {

    /**
     * Runs all Region tests.
     * <p>
     * Executes each test method and prints whether all tests passed.
     *
     * @param args command-line arguments (not used)
     */
    public static void main(String[] args) {
        boolean passed = true;
        System.out.println("Testing Methods");
        if (!testMultipleTerritoriesInit()) passed = false;
        if (!testAddTerritory()) passed = false;
        if (!testIsRegionConquered()) passed = false;
        if (!testClearRegion()) passed = false;
        if (!testHasTerritory()) passed = false;
        if (passed) {
            System.out.println("All Tests Passed");
        } else {
            System.err.println("At least one Test Failed");
        }
    }

    /**
     * Tests initializing a Region with multiple territories.
     * <p>
     * Verifies that the region size is correct, the territories list
     * matches the input, and all territories are contained in the region.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testMultipleTerritoriesInit() {
        boolean passed = true;
        System.out.print("Testing Initializer with multiple territores as paramater: ");

        // Setting up all required elements for a region
        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);
        Territory t2 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 10,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.DESERT.getTerrain(), 30,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t4 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 50,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t5 = new Territory(player, TerrainType.CITY.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        List<Territory> temp = new ArrayList<>();
        Collections.addAll(temp, t1, t2, t3, t4, t5);

        // Store expected size before passing to region to compare against later
        int regionSize = temp.size();

        // Add all territories to a region
        Region region = new Region(temp);
        if (region.getSize() != regionSize) {
            passed = false;
            System.err.println("Region was not the proper size");
        }

        if (!temp.equals(region.getTerritories())) {
            passed = false;
            System.err.println("regions territories are not the same as what was passed into initializer");
        }

        for (Territory t : temp) {
            if (!region.hasTerritory(t)) {
                passed = false;
                System.err.println("A territory was not found in the region");
            }
        }
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests adding territories to a Region.
     * <p>
     * Ensures that the region size increases correctly and that
     * added territories are properly stored.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testAddTerritory() {
        boolean passed = true;
        System.out.print("testing addTerritory Method: ");
        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);

        List<Territory> territories = new ArrayList<>();
        territories.add(t1);
        Region region = new Region(territories);
        int size = region.getSize();

        // Confirm initializer worked correctly before testing addTerritory
        if (size != 1) {
            System.err.println("Error has occurred in region initializer. Test cannot be ran");
            return false;
        }
        Territory t2 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        region.addTerritory(t2);
        size++;
        if (region.getSize() != size) {
            passed = false;
            System.err.println("Regions size did not grow properly when adding a territory");
        }

        for (int i = 0; i < 100; i++) {
            Territory temp = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                    new int[]{1, 2, 3, 4, 5, 6},
                    new int[]{1, 2, 3, 4, 5, 6}, false);
            region.addTerritory(temp);
            size++;
            if (region.getSize() != size) {
                passed = false;
                System.err.println("Region size did not properly grow when adding territories in a loop");
            }

            if (!region.hasTerritory(temp)) {
                passed = false;
                System.err.println("Region does not have newly added territory in loop");
            }
        }
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests whether a Region is correctly identified as conquered.
     * <p>
     * A region should be conquered when all territories belong
     * to the same player and not conquered otherwise.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testIsRegionConquered() {
        boolean passed = true;
        System.out.print("testing isRegionConquered Method: ");

        Player bluePlayer = new Player("p1", BLUE);
        Territory t1 = new Territory(bluePlayer, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);

        List<Territory> territories = new ArrayList<>();
        territories.add(t1);
        Region region = new Region(territories);
        if (!region.isRegionConquered()) {
            passed = false;
            System.err.println("Region was not conquered when there was only 1 territory in the region");
        }

        Player redPlayer = new Player("p2", RED);
        for (int i = 0; i < 100; i++) {
            Territory temp = new Territory(redPlayer, TerrainType.DESERT.getTerrain(), 20,
                    new int[]{1, 2, 3, 4, 5, 6},
                    new int[]{1, 2, 3, 4, 5, 6}, false);
            region.addTerritory(temp);

            if (region.isRegionConquered()) {
                passed = false;
                System.err.println("Region was conquered when territories were owned by both red and blue players");
            }
        }

        // Transfer t1 to red player so all territories are now owned by red
        t1.setPlayer(redPlayer);

        if (!region.isRegionConquered()) {
            passed = false;
            System.err.println("Region was not flagged as conquered when territories were all owned by red player");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests clearing all territories from a Region.
     * <p>
     * Verifies that the region becomes empty and that no
     * territories remain after clearing.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testClearRegion() {
        boolean passed = true;
        System.out.print("Testing clearRegion method: ");

        // Setting up all required elements for a region
        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);
        Territory t2 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 10,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.DESERT.getTerrain(), 30,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t4 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 50,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t5 = new Territory(player, TerrainType.CITY.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        List<Territory> temp = new ArrayList<>();
        Collections.addAll(temp, t1, t2, t3, t4, t5);

        // Add all territories to a region
        Region region = new Region(temp);

        region.clearRegion();
        if (region.getSize() != 0) {
            passed = false;
            System.err.println("The size of the region was not zero after the clear.");
        }

        // Verify no individual territory remains after clearing
        if (region.hasTerritory(t1) || region.hasTerritory(t2) || region.hasTerritory(t3) ||
                region.hasTerritory(t4) || region.hasTerritory(t5)) {
            passed = false;
            System.err.println("The region still contains a territory even after the clear");
        }

        for (int i = 0; i < 1000; i++) {
            region.addTerritory(t1);
            region.clearRegion();
            if (region.hasTerritory(t1)) {
                passed = false;
                System.err.println("Region still contained a territory even after clearRegion() was called");
            }

            if (region.getSize() != 0) {
                passed = false;
                System.err.println("Region's size was not zero after clearRegion was called");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }

        return passed;
    }

    /**
     * Tests the hasTerritory method.
     * <p>
     * Ensures that the method correctly identifies whether
     * a territory exists in the region before and after removal.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testHasTerritory() {
        boolean passed = true;
        System.out.print("Testing hasTerritory method: ");

        // Setting up all required elements for a region
        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);
        Territory t2 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 10,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.DESERT.getTerrain(), 30,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t4 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 50,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t5 = new Territory(player, TerrainType.CITY.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        List<Territory> temp = new ArrayList<>();
        Collections.addAll(temp, t1, t2, t3, t4, t5);

        // Add all territories to a region
        Region region = new Region(temp);

        if (!region.hasTerritory(t1)) {
            passed = false;
            System.err.println("Region did not contain t1");
        }

        if (!region.hasTerritory(t2)) {
            passed = false;
            System.err.println("Region did not contain t2");
        }

        if (!region.hasTerritory(t3)) {
            passed = false;
            System.err.println("Region did not contain t3");
        }

        if (!region.hasTerritory(t4)) {
            passed = false;
            System.err.println("Region did not contain t4");
        }

        if (!region.hasTerritory(t5)) {
            passed = false;
            System.err.println("Region did not contain t5");
        }

        region.clearRegion();

        if (region.hasTerritory(t1)) {
            passed = false;
            System.err.println("Region hasTerritory returned true after t1 was removed");
        }

        if (region.hasTerritory(t2)) {
            passed = false;
            System.err.println("Region hasTerritory returned true after t2 was removed");
        }

        if (region.hasTerritory(t3)) {
            passed = false;
            System.err.println("Region hasTerritory returned true after t3 was removed");
        }

        if (region.hasTerritory(t4)) {
            passed = false;
            System.err.println("Region hasTerritory returned true after t4 was removed");
        }

        if (region.hasTerritory(t5)) {
            passed = false;
            System.err.println("Region hasTerritory returned true after t5 was removed");
        }

        for (int i = 0; i < 1000; i++) {
            region.addTerritory(t2);
            if (!region.hasTerritory(t2)) {
                passed = false;
                System.err.println("Fail in loop: region.hasTerritory returned false when value should have been true");
            }

            region.clearRegion();
            if (region.hasTerritory(t2)) {
                passed = false;
                System.err.println("Fail in loop. region.hasTerritory returned true when value should have been false");
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }
}