package map;

import player.Player;
import terrain.TerrainType;

import java.awt.*;

/**
 * Manual test suite for {@link GenerateNeighborService} in Battle Nations.
 *
 * <p>Tests that neighbors are correctly assigned between territories in a
 * variety of grid configurations, including valid diagonal adjacency, null
 * territories, vertical connections, water route connections, and duplicate
 * neighbor prevention. Each test method is self-contained, builds its own
 * state, and returns true or false. The {@code main} method runs all tests
 * and reports whether the suite passed or failed overall.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public class TestGenerateNeighborService {

    /**
     * Runs all tests in the suite and prints the overall result.
     *
     * <p>Each test method is called in sequence. If any one of them fails,
     * the suite is marked as failed. Results are printed to stdout on pass
     * and stderr on fail.</p>
     *
     * @param args command-line arguments (not used)
     */
    public static void main(String[] args) {
        // Tracks whether every test in this file passed.
        boolean passed = true;

        System.out.println("Testing Methods");

        // Run each test method and mark the suite as failed if any individual test fails.
        if (!testDiagonalNeighborsAssignedFromEvenRow()) passed = false;
        if (!testDiagonalNeighborsAssignedFromOddRow()) passed = false;
        if (!testVerticalNeighborsAssigned()) passed = false;
        if (!testNeighborsAreNotDuplicated()) passed = false;
        if (!testNullTerritoriesAreSkipped()) passed = false;
        if (!testWaterRouteConnectsNonAdjacentTerritories()) passed = false;

        // Print overall test results after all test methods have been executed.
        if (passed) {
            System.out.println("All Tests Passed");
        } else {
            System.err.println("At least one Test Failed");
        }
    }

    /**
     * Tests that diagonal neighbors are correctly assigned from an even row.
     *
     * <p>Places two territories in an even row (row 0) and one territory in the
     * odd row below (row 1). Verifies that the even-row territories are assigned
     * as diagonal neighbors of the odd-row territory after {@code generateNeighbors}
     * is called.</p>
     *
     * @return true if diagonal neighbors are correctly assigned, false otherwise
     */
    private static boolean testDiagonalNeighborsAssignedFromEvenRow() {
        boolean passed = true;
        System.out.print("Testing diagonal neighbors assigned from an even row: ");

        Player player = new Player("p1", Color.RED);
        Territory t1 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // Row 0 is even, row 1 is odd (one fewer column)
        // t3 in row 1 col 0 should be a diagonal neighbor of t1 (row 0 col 0) and t2 (row 0 col 1)
        Territory[][] grid = {
                {t1, t2},
                {t3}
        };

        GenerateNeighborService service = new GenerateNeighborService();
        service.generateNeighbors(grid);

        if (!t1.hasNeighbor(t3)) {
            passed = false;
            System.err.println("t1 should have t3 as a neighbor but does not");
        }
        if (!t3.hasNeighbor(t1)) {
            passed = false;
            System.err.println("t3 should have t1 as a neighbor but does not");
        }
        if (!t2.hasNeighbor(t3)) {
            passed = false;
            System.err.println("t2 should have t3 as a neighbor but does not");
        }
        if (!t3.hasNeighbor(t2)) {
            passed = false;
            System.err.println("t3 should have t2 as a neighbor but does not");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that diagonal neighbors are correctly assigned from an odd row.
     *
     * <p>Places one territory in an even row (row 0) and two territories in the
     * odd row below (row 1). Verifies that the odd-row territories correctly
     * recognize the even-row territory as a neighbor.</p>
     *
     * @return true if diagonal neighbors are correctly assigned from an odd row, false otherwise
     */
    private static boolean testDiagonalNeighborsAssignedFromOddRow() {
        boolean passed = true;
        System.out.print("Testing diagonal neighbors assigned from an odd row: ");

        Player player = new Player("p1", Color.BLUE);
        Territory t1 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // t1 in row 0 col 0, t2 and t3 in row 1
        // from odd row 1: t2 col 0 should connect to t1 col 0, t3 col 1 should connect to t1 col 0 via j+1 logic
        Territory[][] grid = {
                {t1},
                {t2, t3}
        };

        GenerateNeighborService service = new GenerateNeighborService();
        service.generateNeighbors(grid);

        if (!t2.hasNeighbor(t1)) {
            passed = false;
            System.err.println("t2 should have t1 as a neighbor but does not");
        }
        if (!t1.hasNeighbor(t2)) {
            passed = false;
            System.err.println("t1 should have t2 as a neighbor but does not");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that territories two rows apart are assigned as direct vertical neighbors.
     *
     * <p>Places one territory in row 0 and one in row 2 at the same column index.
     * Verifies they are assigned as neighbors since the service connects territories
     * that are exactly two rows apart at the same column.</p>
     *
     * @return true if vertical neighbors are correctly assigned, false otherwise
     */
    private static boolean testVerticalNeighborsAssigned() {
        boolean passed = true;
        System.out.print("Testing vertical neighbors assigned two rows apart: ");

        Player player = new Player("p1", Color.RED);
        Territory t1 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // t1 row 0, t2 row 1 (odd, acts as spacer), t3 row 2 — t1 and t3 should be vertical neighbors
        Territory[][] grid = {
                {t1},
                {t2},
                {t3}
        };

        GenerateNeighborService service = new GenerateNeighborService();
        service.generateNeighbors(grid);

        if (!t1.hasNeighbor(t3)) {
            passed = false;
            System.err.println("t1 should have t3 as a vertical neighbor but does not");
        }
        if (!t3.hasNeighbor(t1)) {
            passed = false;
            System.err.println("t3 should have t1 as a vertical neighbor but does not");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that calling generateNeighbors multiple times does not add duplicate neighbors.
     *
     * <p>Runs {@code generateNeighbors} on the same grid 100 times and verifies
     * that each territory's neighbor list does not grow beyond the expected size.</p>
     *
     * @return true if no duplicates are added across all iterations, false otherwise
     */
    private static boolean testNeighborsAreNotDuplicated() {
        boolean passed = true;
        System.out.print("Testing that neighbors are not duplicated on repeated calls: ");

        Player player = new Player("p1", Color.BLUE);
        Territory t1 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        // t1 row 0 col 0, t2 row 1 col 0 — diagonal neighbors
        Territory[][] grid = {
                {t1},
                {t2}
        };

        GenerateNeighborService service = new GenerateNeighborService();

        for (int i = 0; i < 100; i++) {
            service.generateNeighbors(grid);
        }

        int t1NeighborCount = t1.getNeighboringTerritories().size();
        int t2NeighborCount = t2.getNeighboringTerritories().size();

        if (t1NeighborCount != 1) {
            passed = false;
            System.err.println("t1 should have exactly 1 neighbor but has " + t1NeighborCount);
        }
        if (t2NeighborCount != 1) {
            passed = false;
            System.err.println("t2 should have exactly 1 neighbor but has " + t2NeighborCount);
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that null territories in the grid are skipped without errors.
     *
     * <p>Places a null in the grid alongside valid territories and verifies
     * that {@code generateNeighbors} completes without throwing an exception.</p>
     *
     * @return true if no exception is thrown, false otherwise
     */
    private static boolean testNullTerritoriesAreSkipped() {
        boolean passed = true;
        System.out.print("Testing that null territories in the grid are skipped: ");

        Player player = new Player("p1", Color.GREEN);
        Territory t1 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t2 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        Territory[][] grid = {
                {t1, null},
                {t2}
        };

        GenerateNeighborService service = new GenerateNeighborService();

        try {
            service.generateNeighbors(grid);
        } catch (Exception e) {
            passed = false;
            System.err.println("generateNeighbors threw an exception on a null territory: " + e);
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that a water route territory connects two otherwise non-adjacent territories.
     *
     * <p>Places a water route territory as a neighbor of a plain territory and verifies
     * that after {@code generateNeighbors} the two plain territories are connected
     * to each other through the water route.</p>
     *
     * @return true if the non-adjacent territories are connected via the water route, false otherwise
     */
    private static boolean testWaterRouteConnectsNonAdjacentTerritories() {
        boolean passed = true;
        System.out.print("Testing that a water route connects non-adjacent territories: ");

        Player player = new Player("p1", Color.RED);
        Territory plain1 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory waterRoute = new Territory(TerrainType.WATERROUTE.getTerrain(), new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory plain2 = new Territory(player, TerrainType.PLAIN.getTerrain(), 5, new int[]{1, 2, 3, 4, 5, 6}, new int[]{1, 2, 3, 4, 5, 6}, false);

        Territory[][] grid = {
                {plain1, waterRoute},
                {plain2}
        };

        GenerateNeighborService service = new GenerateNeighborService();
        service.generateNeighbors(grid);

        if (!plain1.hasNeighbor(plain2)) {
            passed = false;
            System.err.println("plain1 should be connected to plain2 via the water route but is not");
        }
        if (!plain2.hasNeighbor(plain1)) {
            passed = false;
            System.err.println("plain2 should be connected to plain1 via the water route but is not");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }
}