package map;

import player.Player;
import terrain.TerrainType;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Tests the core behavior of the {@link World} implementations.
 *
 * <p>This test class verifies territory retrieval, ownership tracking,
 * region control logic, and win-condition behavior for different world types
 * including {@link DummyWorld}, {@link TotalDominationWorld}, and
 * {@link CapitalDominationWorld}. Each test method prints whether it passed
 * or failed and returns a boolean result.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */

public class TestWorld {

    /**
     * Entry point for running all tests.
     *
     * @param args command line arguments (not used)
     */
    public static void main(String[] args) {
        boolean passed = true;
        System.out.println("Testing Methods");

        // Run all tests
        if (!testGetTerritoryCount()) passed = false;
        if (!testGetAllTerritories()) passed = false;
        if (!testGetTerritoriesOwnedByPlayer()) passed = false;
        if (!testGetTerritoryCountOwnedByPlayer()) passed = false;
        if (!testGetRegionCountControlledByPlayer()) passed = false;
        if (!testIsRegionControlledByPlayer()) passed = false;
        if (!testIsGameOverTotalDomination()) passed = false;
        if (!testIsGameOverCapitalDomination()) passed = false;

        // Final result
        if (passed) {
            System.out.println("All Tests Passed");
        } else {
            System.err.println("At least one Test Failed");
        }
    }

    /**
         * Wrapper class used to return both a world and its associated player.
         */
        private record WorldSetupWrapper(DummyWorld world, Player player1) {
        /**
         * Constructs a wrapper containing a world and player.
         *
         * @param world   the generated world
         * @param player1 the primary player
         */
        private WorldSetupWrapper {
        }
        }

    /**
     * Generates a basic test world with:
     * <ul>
     *     <li>5 regions</li>
     *     <li>3 territories per region</li>
     *     <li>All territories owned by player1</li>
     * </ul>
     *
     * @return a wrapper containing the world and player1
     */
    private static WorldSetupWrapper generateWorld() {
        Player player1 = new Player("p1", Color.BLUE);
        ArrayList<Region> regions = new ArrayList<>();

        // Create 5 regions
        for (int i = 0; i < 5; i++) {
            ArrayList<Territory> territories = new ArrayList<>();

            // Add 3 territories to each region
            for (int j = 0; j < 3; j++) {
                Territory t1 = new Territory(player1, TerrainType.DESERT.getTerrain(), 20,
                        new int[]{1, 2, 3, 4, 5, 6},
                        new int[]{1, 2, 3, 4, 5, 6}, false);
                territories.add(t1);
            }
            Region region = new Region(territories);
            regions.add(region);
        }

        return new WorldSetupWrapper(new DummyWorld(regions), player1);
    }

    /**
     * Tests that getAllTerritories returns all territories in the world.
     *
     * @return true if test passes, false otherwise
     */
    private static boolean testGetAllTerritories() {
        boolean passed = true;
        System.out.print("Testing getAllTerritories method: ");

        // Generate a fresh world setup
        WorldSetupWrapper setup = generateWorld();
        DummyWorld world = setup.world;

        ArrayList<Territory> allTerritories = new ArrayList<>();

        // Collect all territories manually
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                allTerritories.add(territory);
            }
        }

        // Get territories from world method (actual result)
        List<Territory> worldTerritories = world.getAllTerritories();

        // Verify all expected territories exist
        for (Territory territory : allTerritories) {
            if (!worldTerritories.contains(territory)) {
                passed = false;
                System.err.println("get all territories, did not contain a territory from initial world creation ");
            }
        }

        // Create a second player and add one new territory to each region
        Player temp = new Player("p2", Color.RED);
        for (Region region : world.getRegions()) {
            Territory tempTerritory = new Territory(temp, TerrainType.DESERT.getTerrain(), 20,
                    new int[]{1, 2, 3, 4, 5, 6},
                    new int[]{1, 2, 3, 4, 5, 6}, false);
            region.addTerritory(tempTerritory);
            // track expected list
            allTerritories.add(tempTerritory);

        }

        // Re-fetch world territories after modification
        worldTerritories = world.getAllTerritories();

        // Validate all territories still match expected list
        for (Territory territory : allTerritories) {
            if (!worldTerritories.contains(territory)) {
                passed = false;
                System.err.println("get all territories, did not contain a territory after adding one to each region");
            }
        }

        // Ensure total count matches expected
        if (worldTerritories.size() != allTerritories.size()) {
            passed = false;
            System.err.println("getAllTerritories returned the wrong number of territories");
        }

        // Add 100 territories to each region and validate incrementally
        for (Region region : world.getRegions()) {
            for (int i = 0; i < 100; i++) {
                Territory tempTerritory = new Territory(temp, TerrainType.DESERT.getTerrain(), 20,
                        new int[]{1, 2, 3, 4, 5, 6},
                        new int[]{1, 2, 3, 4, 5, 6}, false);
                region.addTerritory(tempTerritory);
                allTerritories.add(tempTerritory);
            }

            // Validate after modifying each region
            worldTerritories = world.getAllTerritories();
            for (Territory territory : allTerritories) {
                if (!worldTerritories.contains(territory)) {
                    passed = false;
                    System.err.println("get all territories, did not contain a territory after adding 100 territories to one region");
                }
            }

            // Check count consistency after each region update
            if (worldTerritories.size() != allTerritories.size()) {
                passed = false;
                System.err.println("getAllTerritories returned the wrong number of territories");
            }
        }

        // Final validation after all regions updated
        worldTerritories = world.getAllTerritories();
        for (Territory territory : allTerritories) {
            if (!worldTerritories.contains(territory)) {
                passed = false;
                System.err.println("get all territories, did not contain a territory after adding 100 territories to every region");
            }
        }

        // Final size check
        if (worldTerritories.size() != allTerritories.size()) {
            passed = false;
            System.err.println("getAllTerritories returned the wrong number of territories");
        }

        // Print result
        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }

        return passed;
    }

    /**
     * Tests the getTerritoryCount method.
     *
     * <p>This test verifies that {@link World#getTerritoryCount()} correctly
     * returns the total number of territories in the world after initial
     * creation, after adding one territory to each region, and after adding
     * multiple territories to regions.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testGetTerritoryCount() {
        boolean passed = true;
        System.out.print("Testing getTerritoryCount method: ");

        // Generate a fresh world setup
        WorldSetupWrapper setup = generateWorld();
        DummyWorld world = setup.world;

        int territoryCount = 0;

        // Manually count all territories from regions (expected value)
        for (Region r : world.getRegions()) {
            territoryCount += r.getSize();
        }

        // Validate initial territory count
        if (territoryCount != world.getTerritoryCount()) {
            passed = false;
            System.err.println("world did not produce the proper territory count after initial world creation");
        }

        // Add one territory to each region and update expected count
        Player temp = new Player("p2", Color.RED);
        for (Region region : world.getRegions()) {
            region.addTerritory(new Territory(temp, TerrainType.DESERT.getTerrain(), 20,
                    new int[]{1, 2, 3, 4, 5, 6},
                    new int[]{1, 2, 3, 4, 5, 6}, false));
            territoryCount++;
        }

        // Validate after adding one territory per region
        if (territoryCount != world.getTerritoryCount()) {
            passed = false;
            System.err.println("World did not get proper territory count after adding one territory to each region");
        }

        // Add 100 territories to each region and validate incrementally
        for (Region region : world.getRegions()) {
            for (int i = 0; i < 100; i++) {
                region.addTerritory(new Territory(temp, TerrainType.DESERT.getTerrain(), 20,
                        new int[]{1, 2, 3, 4, 5, 6},
                        new int[]{1, 2, 3, 4, 5, 6}, false));
                territoryCount++;
            }

            // Validate after modifying each region
            if (world.getTerritoryCount() != territoryCount) {
                passed = false;
                System.err.println("World did not get proper territory count after adding 100 territories to one region");
            }
        }

        // Final validation after all regions updated
        if (world.getTerritoryCount() != territoryCount) {
            passed = false;
            System.err.println("World did not get proper territory count after all regions gained 100 territories");
        }

        // Print result
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }

        return passed;
    }

    /**
     * Tests the getTerritoriesOwnedByPlayer method.
     *
     * <p>This test verifies that {@link World#getTerritoriesOwnedByPlayer(Player)}
     * correctly returns all territories owned by a given player after initial
     * world creation and after territory ownership is reassigned to another
     * player.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testGetTerritoriesOwnedByPlayer() {
        boolean passed = true;
        System.out.print("Testing getTerritoriesOwnedByPlayer method: ");

        // Generate a fresh world setup
        WorldSetupWrapper setup = generateWorld();
        DummyWorld world = setup.world;
        Player player1 = setup.player1;

        // Manually collect all territories initially owned by player1
        ArrayList<Territory> playerOwnedTerritories = new ArrayList<>();
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                if (territory.getPlayer() == player1) {
                    playerOwnedTerritories.add(territory);
                }
            }
        }

        // Verify all player1-owned territories are returned initially
        List<Territory> testGetAllPlayerTerritories = world.getTerritoriesOwnedByPlayer(player1);
        for (Territory territory : playerOwnedTerritories) {
            if (!testGetAllPlayerTerritories.contains(territory)) {
                passed = false;
                System.err.println("World did not properly return all player owned territories after its initial creation");
            }
        }

        // Reassign territories to player2 and validate results for both players
        Player player2 = new Player("p2", Color.RED);
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                territory.setPlayer(player2);

                // Player1 should no longer own the territory
                testGetAllPlayerTerritories = world.getTerritoriesOwnedByPlayer(player1);
                if (testGetAllPlayerTerritories.contains(territory)) {
                    passed = false;
                    System.err.println("World returned a territory that was no longer owned by player");
                }

                // Player2 should now own the territory
                testGetAllPlayerTerritories = world.getTerritoriesOwnedByPlayer(player2);
                if (!testGetAllPlayerTerritories.contains(territory)) {
                    System.err.println("World did not return a territory that was no owned by player2");
                }
            }
        }

        // Player1 should own no territories after all have been reassigned
        testGetAllPlayerTerritories = world.getTerritoriesOwnedByPlayer(player1);
        if (testGetAllPlayerTerritories.size() != 0) {
            passed = false;
            System.err.println("World returned territories for player1 when they owned 0");
        }

        // Print result
        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }

        return passed;
    }

    /**
     * Tests the getTerritoryCountOwnedByPlayer method.
     *
     * <p>This test verifies that {@link World#getTerritoryCountOwnedByPlayer(Player)}
     * correctly returns the number of territories owned by a player after initial
     * world creation, after territory ownership changes, and after new territories
     * are added for a player.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testGetTerritoryCountOwnedByPlayer() {
        boolean passed = true;
        System.out.print("Testing getTerritoryCountOwnedByPlayer method: ");

        // Generate a fresh world setup
        WorldSetupWrapper setup = generateWorld();
        DummyWorld world = setup.world;
        Player player1 = setup.player1;

        int player1TerritoryCount = 0;

        // Manually count territories initially owned by player1
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                if (territory.getPlayer() == player1) {
                    player1TerritoryCount++;
                }
            }
        }

        // Validate initial ownership count for player1
        if (world.getTerritoryCountOwnedByPlayer(player1) != player1TerritoryCount) {
            passed = false;
            System.err.println("World Did not return the proper Territory Count owned by player1 after initial world creation");
        }

        // Reassign territories to player2 and validate counts incrementally
        Player player2 = new Player("p2", Color.RED);
        int player2TerritoryCount = 0;
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                territory.setPlayer(player2);
                player2TerritoryCount++;
                player1TerritoryCount--;

                // player1 territory count should have lowered by 1
                if (player1TerritoryCount != world.getTerritoryCountOwnedByPlayer(player1)) {
                    passed = false;
                    System.err.println("World did not return proper player1 territory count after changing a territories owner");
                }

                // player2 territory count should have incremented by 1
                if (player2TerritoryCount != world.getTerritoryCountOwnedByPlayer(player2)) {
                    passed = false;
                    System.err.println("World did not return proper player2 territory count after setting a territories ownership to player2");
                }
            }
        }

        // Player1 should own 0 territories after reassignment
        if (world.getTerritoryCountOwnedByPlayer(player1) != 0) {
            passed = false;
            System.err.println("World didnt return 0 for player1 territory count when player1 owned 0 territories");
        }

        // Add new territories owned by player1 and validate count updates
        for (Region region : world.getRegions()) {
            for (int i = 0; i < 100; i++) {
                Territory tempTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 20,
                        new int[]{1, 2, 3, 4, 5, 6},
                        new int[]{1, 2, 3, 4, 5, 6}, false);
                region.addTerritory(tempTerritory);
                player1TerritoryCount++;

                if (player1TerritoryCount != world.getTerritoryCountOwnedByPlayer(player1)) {
                    passed = false;
                    System.err.println("World did not return proper player1 territory count after adding a territory to a region that player 1 owns");
                }
            }

        }

        // Print result
        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests the getRegionCountControlledByPlayer method.
     *
     * <p>This test verifies that {@link World#getRegionCountControlledByPlayer(Player)}
     * correctly returns the number of regions controlled by a player after initial
     * world creation, after partial loss of control, and after another player gains
     * full control of regions.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testGetRegionCountControlledByPlayer() {
        boolean passed = true;
        System.out.print("Testing getRegionCountControlledByPlayer method: ");

        // Generate a fresh world setup
        WorldSetupWrapper setup = generateWorld();
        DummyWorld world = setup.world;
        Player player1 = setup.player1;

        int player1RegionCount = 0;

        // Count regions initially controlled by player1
        for (Region region : world.getRegions()) {
            if (region.getPlayerConqueredRegion() == player1) {
                player1RegionCount++;
            }
        }

        // Validate initial controlled-region count for player1
        if (player1RegionCount != world.getRegionCountControlledByPlayer(player1)) {
            passed = false;
            System.err.println("World did not return player 1's controlled region count properly after initial world creation");
        }

        // Assign one territory in each region to player2 to remove player1's control
        Player player2 = new Player("p2", Color.RED);
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                territory.setPlayer(player2);
                break;
            }

            player1RegionCount--;
            if (player1RegionCount != world.getRegionCountControlledByPlayer(player1)) {
                passed = false;
                System.err.println("World did not return proper player1 controlled region count after assigning a territory to player 2 in a region");
            }
        }

        int player2RegionCount = 0;

        // Give player2 full ownership of each region and validate control count
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                territory.setPlayer(player2);
            }

            player2RegionCount++;
            if (player2RegionCount != world.getRegionCountControlledByPlayer(player2)) {
                passed = false;
                System.err.println("World did not return proper player2 controlled region count after player2 fully controlled a region");
            }
        }

        // Print result
        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests the isRegionControlledByPlayer method.
     *
     * <p>This test verifies that {@link World#isRegionControlledByPlayer(Region, Player)}
     * correctly identifies when a player fully controls a region, when control is
     * lost due to another player's ownership of a territory, and when another player
     * fully gains control of the region.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testIsRegionControlledByPlayer() {
        boolean passed = true;
        System.out.print("Testing isRegionControlledByPlayer method: ");

        // Generate a fresh world setup
        WorldSetupWrapper setup = generateWorld();
        DummyWorld world = setup.world;
        Player player1 = setup.player1;

        // Initially, player1 should control every region
        for (Region region : world.getRegions()) {
            if (!world.isRegionControlledByPlayer(region, player1)) {
                passed = false;
                System.err.println("isRegionControlledByPlayer returned false for player1 when region was controlled by player1");
            }
        }

        // Assign one territory in each region to player2 and verify player1 loses control
        Player player2 = new Player("p2", Color.RED);
        for (Region region : world.getRegions()) {

            // set first territory to player 2
            for (Territory territory : region.getTerritories()) {
                territory.setPlayer(player2);
                break;
            }

            if (world.isRegionControlledByPlayer(region, player1)) {
                passed = false;
                System.err.println("isRegionControlledByPlayer returned true when a territory's owner was set to player2 in region");
            }
        }

        // Give player2 full ownership of each region and verify control
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                territory.setPlayer(player2);
            }

            if (!world.isRegionControlledByPlayer(region, player2)) {
                passed = false;
                System.err.println("isRegionControlledByPlayer returned false when a region was fully owned by player2");
            }
        }

        // Print result
        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests the total domination win condition.
     *
     * <p>This test verifies that {@link TotalDominationWorld#isGameWon(List)}
     * returns true when one player owns all territories, false when ownership is
     * split between players, and true again when the second player owns all
     * territories.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testIsGameOverTotalDomination() {
        boolean passed = true;
        System.out.print("Testing testIsGameOverTotalDomination method: ");

        Player player1 = new Player("p1", Color.BLUE);
        ArrayList<Region> regions = new ArrayList<>();

        // Build a world where player1 initially owns every territory
        for (int i = 0; i < 5; i++) {
            ArrayList<Territory> territories = new ArrayList<>();
            for (int j = 0; j < 3; j++) {
                Territory t1 = new Territory(player1, TerrainType.DESERT.getTerrain(), 20,
                        new int[]{1, 2, 3, 4, 5, 6},
                        new int[]{1, 2, 3, 4, 5, 6}, false);
                territories.add(t1);
            }
            Region region = new Region(territories);
            regions.add(region);
        }

        TotalDominationWorld world = new TotalDominationWorld(regions);

        Player player2 = new Player("p2", Color.RED);
        List<Player> players = new ArrayList<>();
        players.add(player1);
        players.add(player2);

        // Game should be won when player1 owns all territories
        if (!world.isGameWon(players)) {
            passed = false;
            System.err.println("game was marked as not won when player1 owned all territories");
        }

        // Change ownership of one territory to player2 so the game should no longer be won
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                territory.setPlayer(player2);
                break;
            }
            break;
        }

        if (world.isGameWon(players)) {
            passed = false;
            System.err.println("game was marked as won, when 1 territory was owned by player 2");
        }

        // Give player2 ownership of every territory so the game should be won again
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                territory.setPlayer(player2);
            }
        }

        if (!world.isGameWon(players)) {
            passed = false;
            System.err.println("game was not marked won when player2 owned every territory");
        }

        // Print result
        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests the capital domination win condition.
     *
     * <p>This test verifies that {@link CapitalDominationWorld#isGameWon(List)}
     * returns true when one player owns all capital territories, false when a
     * capital territory is lost to another player, and true again when the second
     * player owns all capital territories.</p>
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testIsGameOverCapitalDomination() {
        boolean passed = true;
        System.out.print("Testing testIsGameOverTotalDomination method: ");

        Player player1 = new Player("p1", Color.BLUE);
        ArrayList<Region> regions = new ArrayList<>();

        // Build a world where each region contains one capital territory owned by player1
        for (int i = 0; i < 5; i++) {
            ArrayList<Territory> territories = new ArrayList<>();
            for (int j = 0; j < 3; j++) {
                Territory t1 = new Territory(player1, TerrainType.DESERT.getTerrain(), 20,
                        new int[]{1, 2, 3, 4, 5, 6},
                        new int[]{1, 2, 3, 4, 5, 6}, false);
                territories.add(t1);
            }

            Territory capitalTerritory = new Territory(player1, TerrainType.DESERT.getTerrain(), 20,
                    new int[]{1, 2, 3, 4, 5, 6},
                    new int[]{1, 2, 3, 4, 5, 6}, true);
            territories.add(capitalTerritory);

            Region region = new Region(territories);
            regions.add(region);
        }

        CapitalDominationWorld world = new CapitalDominationWorld(regions);

        Player player2 = new Player("p2", Color.RED);
        List<Player> players = new ArrayList<>();
        players.add(player1);
        players.add(player2);

        // Game should be won when player1 owns all capital territories
        if (!world.isGameWon(players)) {
            passed = false;
            System.err.println("game was not marked as won when player 1 owned all capital territories");
        }

        // set all territories in one region to player2, so one capital is owned by player2
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                territory.setPlayer(player2);
            }
            break;
        }

        if (world.isGameWon(players)) {
            passed = false;
            System.err.println("Game was marked as won when player 1 no longer owned all capital territories");
        }

        // set all territories to player 2, so it owns all capital territories as well
        for (Region region : world.getRegions()) {
            for (Territory territory : region.getTerritories()) {
                territory.setPlayer(player2);
            }
        }

        if (!world.isGameWon(players)) {
            passed = false;
            System.err.println("Game was marked as not won, when player 2 owned all capital territories");
        }

        // Print result
        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }
}
