package map;

import player.Player;
import terrain.TerrainType;

import java.awt.*;
import java.awt.image.BufferedImage;

import static java.awt.Color.BLUE;
import static java.awt.Color.GREEN;

/**
 * Tests the core functionality of the Territory class.
 *
 * <p>This class verifies initialization, player assignment,
 * neighbor relationships, and ensures that rendering
 * does not cause runtime errors. Each test method is self-contained,
 * builds its own state, and returns true or false. The {@code main}
 * method runs all tests and reports whether the suite passed or
 * failed overall.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 *   <li>ChatGPT – Assisted with identifying a simple and reliable way to obtain
 *   a Graphics object for testing purposes by using a BufferedImage. Specifically,
 *   the lines {@code BufferedImage img = new BufferedImage(...);} and
 *   {@code Graphics g = img.getGraphics();} were used to allow the Draw method
 *   to execute without requiring a GUI.</li>
 * </ul>
 */
public class TestTerritory {

    /**
     * Runs all tests in the suite and prints the overall result.
     *
     * <p>Each test method is called in sequence. If any one of them fails,
     * the suite is marked as failed. Results are printed to stdout on pass
     * and stderr on fail.</p>
     *
     * @param args command-line arguments (not used)
     */
    public static void main(String[] args) {
        boolean passed = true;
        System.out.println("Testing Methods");
        if (!testInitializer()) passed = false;
        if (!testSetPlayer()) passed = false;
        if (!testAddNeighbor()) passed = false;
        if (!testHasNeighbor()) passed = false;
        if (!testDrawDoesntCrash()) passed = false;
        if (passed) {
            System.out.println("All Tests Passed");
        } else {
            System.err.println("At least one Test Failed");
        }
    }

    /**
     * Tests the Territory constructor.
     * <p>
     * Verifies that player, terrain, troop amount,
     * and capital status are correctly initialized.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testInitializer() {
        boolean passed = true;
        System.out.print("Testing Initializer: ");

        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);

        // Verify each field was set correctly by the constructor
        if (t1.getPlayer() != player) {
            passed = false;
            System.err.println("Player was not properly set in initializer");
        }

        if (t1.getTerrain() != TerrainType.DESERT.getTerrain()) {
            passed = false;
            System.err.println("Terrain Type was not properly set in initializer");
        }

        if (!t1.isCapital()) {
            passed = false;
            System.err.println("isCapital was not properly set in initializer");
        }

        if (t1.getTroopAmount() != 20) {
            passed = false;
            System.err.println("Troop Amount was not properly set in initializer");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }

        return passed;
    }

    /**
     * Tests the setPlayer method.
     * <p>
     * Ensures that the player is updated correctly and
     * that repeated updates behave consistently.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testSetPlayer() {
        boolean passed = true;
        System.out.print("Testing setPlayer: ");

        Player player1 = new Player("p1", BLUE);
        Player player2 = new Player("p2", GREEN);

        Territory t1 = new Territory(player1, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);

        // Verify the initial player was set correctly by the constructor
        if (t1.getPlayer() != player1) {
            passed = false;
            System.err.println("getPlayer did not return the player set in initializer");
        }

        t1.setPlayer(player2);
        if (t1.getPlayer() != player2) {
            passed = false;
            System.err.println("get player did not return player2 after setting territories player to player2");
        }

        // Alternate between players 1000 times to confirm updates are consistent
        for (int i = 0; i < 1000; i++) {
            t1.setPlayer(player1);
            if (t1.getPlayer() != player1) {
                System.err.println("Failed during loop: getPlayer() did not return player1 when it was supposed to");
            }

            t1.setPlayer(player2);
            if (t1.getPlayer() != player2) {
                System.err.println("Failed during loop: getPlayer() did not return player2 when it was supposed to");
            }
        }
        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }
        return passed;
    }

    /**
     * Tests adding neighboring territories.
     * <p>
     * Verifies that territories are properly added to the
     * neighbor list and can be retrieved using hasNeighbor().
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testAddNeighbor() {
        boolean passed = true;
        System.out.print("test addNeighbor method: ");

        // Setting up all required elements for testing
        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);
        Territory t2 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 10,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.DESERT.getTerrain(), 30,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t4 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 50,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t5 = new Territory(player, TerrainType.CITY.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);

        // Add each territory as a neighbor and verify it was stored correctly
        t1.addToTerritoryNeighbors(t2);
        if (!t1.hasNeighbor(t2)) {
            passed = false;
            System.err.println("t2 was not properly added to t1's neighbors");
        }

        t1.addToTerritoryNeighbors(t3);
        if (!t1.hasNeighbor(t3)) {
            passed = false;
            System.err.println("t3 was not properly added to t1's neighbors");
        }

        t1.addToTerritoryNeighbors(t4);
        if (!t1.hasNeighbor(t4)) {
            passed = false;
            System.err.println("t4 was not properly added to t1's neighbors");
        }

        t1.addToTerritoryNeighbors(t5);
        if (!t1.hasNeighbor(t5)) {
            passed = false;
            System.err.println("t5 was not properly added to t1's neighbors");
        }

        // Add 1000 more neighbors in a loop to confirm behavior scales correctly
        for (int i = 0; i < 1000; i++) {
            Territory temp = new Territory(player, TerrainType.CITY.getTerrain(), i,
                    new int[]{1, 2, 3, 4, 5, 6},
                    new int[]{1, 2, 3, 4, 5, 6}, false);

            t1.addToTerritoryNeighbors(temp);
            if (!t1.hasNeighbor(temp)) {
                passed = false;
                System.err.println("Looping Failed: t1 did not add the newest temp territory in its list of neighbors");
            }
        }
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests the hasNeighbor method.
     * <p>
     * Ensures that the method correctly identifies whether
     * a territory exists in the neighbor list.
     *
     * @return true if the test passes, false otherwise
     */
    private static boolean testHasNeighbor() {
        boolean passed = true;
        System.out.print("test hasNeighbor method: ");

        // Setting up all required elements for testing
        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);
        Territory t2 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 10,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t3 = new Territory(player, TerrainType.DESERT.getTerrain(), 30,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t4 = new Territory(player, TerrainType.MOUNTAIN.getTerrain(), 50,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);
        Territory t5 = new Territory(player, TerrainType.CITY.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, false);

        // Add each territory and immediately verify hasNeighbor returns true
        t1.addToTerritoryNeighbors(t2);
        if (!t1.hasNeighbor(t2)) {
            passed = false;
            System.err.println("hasNeighbor returned false when t2 was added to t1 neighbors list");
        }

        t1.addToTerritoryNeighbors(t3);
        if (!t1.hasNeighbor(t3)) {
            passed = false;
            System.err.println("hasNeighbor returned false when t3 was added to t1 neighbors list");
        }

        t1.addToTerritoryNeighbors(t4);
        if (!t1.hasNeighbor(t4)) {
            passed = false;
            System.err.println("hasNeighbor returned false when t4 was added to t1 neighbors list");
        }

        t1.addToTerritoryNeighbors(t5);
        if (!t1.hasNeighbor(t5)) {
            passed = false;
            System.err.println("hasNeighbor returned false when t5 was added to t1 neighbors list");
        }

        // Add 1000 more neighbors in a loop to confirm behavior scales correctly
        for (int i = 0; i < 1000; i++) {
            Territory temp = new Territory(player, TerrainType.CITY.getTerrain(), i,
                    new int[]{1, 2, 3, 4, 5, 6},
                    new int[]{1, 2, 3, 4, 5, 6}, false);

            t1.addToTerritoryNeighbors(temp);
            if (!t1.hasNeighbor(temp)) {
                passed = false;
                System.err.println("Looping Failed: t1 did not contain the newest temp territory in its list of neighbors");
            }
        }
        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Tests that the Draw method executes without throwing exceptions.
     * <p>
     * This test does not verify rendering correctness, only that
     * the method runs safely under repeated calls.
     *
     * @return true if no exceptions are thrown, false otherwise
     */
    private static boolean testDrawDoesntCrash() {
        boolean passed = true;
        System.out.print("Testing Draw Method to ensure it doesnt crash program: ");

        Player player = new Player("p1", BLUE);
        Territory t1 = new Territory(player, TerrainType.DESERT.getTerrain(), 20,
                new int[]{1, 2, 3, 4, 5, 6},
                new int[]{1, 2, 3, 4, 5, 6}, true);

        // Start of code from ChatGPT
        // Create an off-screen image to get a Graphics object without needing a GUI
        BufferedImage img = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);
        Graphics g = img.getGraphics();
        // End of code from ChatGPT

        // Call Draw 1000 times and catch any exceptions that would indicate a crash
        for (int i = 0; i < 1000; i++) {
            try {
                t1.draw(g);
            } catch (Exception any) {
                passed = false;
                System.err.println("Drawing has failed. Error: " + any);
            }
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.err.println("Failed");
        }

        return passed;
    }
}