package map;

import player.Player;

import java.util.List;

/**
 * A game world where the win condition is conquering all regions on the map.
 *
 * <p>In Total Domination, a player wins by fully controlling every region.
 * A region is considered controlled when all of its territories are owned
 * by the same player. This mode encourages players to expand across the
 * entire map rather than focusing on specific targets.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public class TotalDominationWorld extends AbstractWorld {

    /**
     * Constructs a TotalDominationWorld with a predefined list of regions.
     *
     * @param regions the regions that make up the world
     */
    public TotalDominationWorld(List<Region> regions) {
        super(regions);
    }

    /**
     * Determines whether any player has won by controlling all regions.
     *
     * @param players the list of players in the game
     * @return true if a player controls every region, false otherwise
     */
    @Override
    public boolean isGameWon(List<Player> players) {
        for (Player player : players) {
            // Win condition — player controls every region on the map
            if (getRegionCountControlledByPlayer(player) == regions.size()) {
                return true;
            }
        }
        return false;
    }

    /**
     * Returns the player who controls all regions, or null if no one has won yet.
     *
     * @param players the list of players in the game
     * @return the winning player, or null if the game is still in progress
     */
    public Player getWinningPlayer(List<Player> players) {
        for (Player player : players) {
            // Return the first player found who owns all regions
            if (getRegionCountControlledByPlayer(player) == regions.size()) {
                return player;
            }
        }
        return null;
    }
}