package map;

import player.Player;

import java.util.List;

/**
 * Defines the contract for a game world in Battle Nations.
 *
 * <p>A world contains all regions and territories on the map and provides
 * methods for querying ownership, region control, and win conditions.
 * Different game modes implement this interface to define their own
 * win conditions while sharing the same core world structure.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Claude (Anthropic) – Assisted with generating Javadoc and inline comments.
 *   All comments were reviewed by the author. No code was generated by Claude.</li>
 * </ul>
 */
public interface World {

    /**
     * Returns all regions in the world.
     *
     * @return the list of all regions
     */
    List<Region> getRegions();

    /**
     * Returns every territory across all regions in the world.
     *
     * @return the list of all territories
     */
    List<Territory> getAllTerritories();

    /**
     * Returns the total number of territories in the world.
     *
     * @return the territory count
     */
    int getTerritoryCount();

    /**
     * Returns all territories currently owned by the given player.
     *
     * @param player the player to check ownership for
     * @return the list of territories owned by the player
     */
    List<Territory> getTerritoriesOwnedByPlayer(Player player);

    /**
     * Returns the number of territories currently owned by the given player.
     *
     * @param player the player to check ownership for
     * @return the number of territories owned by the player
     */
    int getTerritoryCountOwnedByPlayer(Player player);

    /**
     * Returns all regions fully controlled by the given player.
     *
     * <p>A region is considered controlled when all of its territories
     * are owned by the same player.</p>
     *
     * @param player the player to check control for
     * @return the list of regions controlled by the player
     */
    List<Region> getRegionsControlledByPlayer(Player player);

    /**
     * Returns the number of regions fully controlled by the given player.
     *
     * @param player the player to check control for
     * @return the number of regions controlled by the player
     */
    int getRegionCountControlledByPlayer(Player player);

    /**
     * Determines whether the given region is fully controlled by the given player.
     *
     * @param region the region to check
     * @param player the player to check control for
     * @return true if the player controls the region, false otherwise
     */
    boolean isRegionControlledByPlayer(Region region, Player player);

    /**
     * Determines whether the win condition for this world has been met.
     *
     * <p>The specific win condition depends on the implementing class.</p>
     *
     * @param players the list of players in the game
     * @return true if the game has been won, false otherwise
     */
    boolean isGameWon(List<Player> players);

    /**
     * Returns the player who has met the win condition, or null if no one has won yet.
     *
     * <p>The specific win condition depends on the implementing class.</p>
     *
     * @param players the list of players in the game
     * @return the winning player, or null if the game is still in progress
     */
    Player getWinningPlayer(List<Player> players);
}