package gameGUI;

import game.*;
import map.*;
import player.Player;
import startGUI.StartController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 * Controls the main gameplay flow for Battle Nations.
 *
 * <p>This class manages user interaction during the game, including handling
 * territory clicks, coordinating turn phases, updating on-screen text, and
 * transitioning between the main game display and the win screen.</p>
 *
 * <p>The controller delegates core gameplay rules such as attacking,
 * reinforcing, and fortifying to the GameLogic class and related services.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>https://www.baeldung.com/java-text-blocks</li>
 *   <li>ChatGPT – Assisted with generating Javadoc and inline comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 */
public class GameController {
    /**
     * Handles the main game logic and phase progression.
     */
    private final GameLogic gameLogic;

    /**
     * List of all territories in the current world.
     */
    private final List<Territory> territories;

    /**
     * Main game window display.
     */
    private final JFrame display;

    /**
     * Label showing the current phase of the game.
     */
    private final JLabel gameStatusLabel;

    /**
     * Label showing instructions for the current player.
     */
    private final JLabel instructionText;

    /**
     * Label showing general information about the current player and turn.
     */
    private final JLabel generalInfoLabel;

    /**
     * Label used to display error messages to the user.
     */
    private final JLabel errorText;

    /**
     * Label used to display success messages to the user.
     */
    private final JLabel successText;

    /**
     * Panel containing game information and buttons.
     */
    private final JPanel gameInfoPanel;

    /**
     * Panel used to display region information.
     */
    private final RegionPanel regionPanel;

    /**
     * Button used to continue to the next phase or turn.
     */
    private final JButton continueButton;

    /**
     * Stores the first selected territory during attack or fortify actions.
     */
    private Territory firstTerritoryClicked;

    /**
     * Tracks whether the player has already used fortify during the current turn.
     */
    private boolean fortifyUsedThisTurn;

    /**
     * Button used to switch between map and region displays.
     */
    private JButton changeDisplayButton;

    /**
     * Start Controller used to return back to the main menu after the game
     */
    private StartController startController;

    private boolean showingRegions = false;

    /**
     * Constructs the game controller and initializes gameplay components.
     *
     * @param world            the world being played on
     * @param players          the players participating in the game
     * @param display          the main game window
     * @param mapPanel         the panel displaying the game map
     * @param gameInfoPanel    the panel containing game information
     * @param regionPanel      the panel displaying region information
     * @param gameStatusLabel  label showing the current phase
     * @param generalInfoLabel label showing current player information
     * @param instructionText  label showing turn instructions
     * @param errorText        label showing error messages
     * @param successText      label showing success messages
     * @param startController  controller in charge of the setting up of a new game
     */
    public GameController(World world, List<Player> players, JFrame display, MapPanel mapPanel, JPanel gameInfoPanel, RegionPanel regionPanel, JLabel gameStatusLabel, JLabel generalInfoLabel, JLabel instructionText, JLabel errorText, JLabel successText, StartController startController) {
        gameLogic = new GameLogic(world, players, new AttackService(), new ReinforcementService(), new FortifyService());
        gameLogic.calculateReinforcement();
        territories = world.getAllTerritories();
        fortifyUsedThisTurn = false;
        this.startController = startController;

        this.display = display;
        this.gameInfoPanel = gameInfoPanel;
        this.gameStatusLabel = gameStatusLabel;
        this.generalInfoLabel = generalInfoLabel;
        this.instructionText = instructionText;
        this.errorText = errorText;
        this.successText = successText;
        this.regionPanel = regionPanel;

        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        changeDisplayButton = new JButton("Show Regions");
        changeDisplayButton.setVisible(true);
        changeDisplayButton.addActionListener(e -> {
            // If the button currently says "Show Map", switch back to the map display
            if (changeDisplayButton.getText().equals("Show Map")) {
                display.remove(regionPanel);
                display.add(mapPanel);
                changeDisplayButton.setText("Show Regions");
                showingRegions = false;
            } else {
                // Otherwise remove the map and region panel to prepare for region view
                display.remove(mapPanel);
                display.add(regionPanel);
                regionPanel.setBounds(0, 0, screen.width, (int)(screen.height * 0.8));
                changeDisplayButton.setText("Show Map");
                showingRegions = true;
                regionPanel.repaint();
            }
            display.revalidate();
            display.repaint();
            updateText();
        });

        changeDisplayButton.setBounds(gameInfoPanel.getWidth() - 200, 10, 200, 50);

        gameInfoPanel.add(changeDisplayButton);

        JButton terrainInfoButton = new JButton("Terrain Info");
        terrainInfoButton.setBounds(gameInfoPanel.getWidth() - 200, 65, 200, 50);
        terrainInfoButton.addActionListener(e -> showTerrainInfo());
        gameInfoPanel.add(terrainInfoButton);

        continueButton = new JButton("Continue");
        continueButton.setBounds(gameInfoPanel.getWidth() - 200, 120, 200, 50);
        continueButton.setEnabled(false);

        continueButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Advances the game to the next phase or player turn
                endTurn();
            }
        });
        this.gameInfoPanel.add(continueButton);
        mapPanel.switchToGameController(this);
        updateText();
        display.revalidate();
        display.repaint();
        displayStartPopup();

        // Immediately show the win page if the game has already ended
        if (gameLogic.isGameOver()) {
            showWinPage();
        }
    }

    /**
     * Handles a click on the map by determining which territory was selected.
     *
     * @param point the point clicked on the map
     */
    public void getTerritoryClicked(Point point) {
        errorText.setText("");
        successText.setText("");

        // Check each territory to see if the clicked point falls inside it
        for (Territory territory : territories) {
            if (territory != null && territory.contains(point)) {
                // Route the click to the correct handler based on the current phase
                if (gameLogic.getCurrentPhase() == TurnPhase.REINFORCEMENT) {
                    reinforcementPhaseTerritoryClicked(territory);
                } else if (gameLogic.getCurrentPhase() == TurnPhase.ATTACK) {
                    attackPhaseTerritoryClick(territory);
                } else {
                    fortifyPhaseTerritoryClicked(territory);
                }
                updateText();
                return;
            }
        }

        // If no valid territory was clicked, show an error
        errorText.setText("Error: Click a Playable Territory");
    }

    /**
     * Handles territory selection during the attack phase.
     *
     * @param territory the territory clicked by the player
     */
    private void attackPhaseTerritoryClick(Territory territory) {
        if (firstTerritoryClicked == null) {
            // The first click must be a territory owned by the current player
            if (!gameLogic.isTerritoryPlayerOwned(territory)) {
                errorText.setText("ERROR: Select a territory you own to attack from");
                return;
            }

            // The attacking territory must have more than one troop
            if (territory.getTroopAmount() <= 1) {
                errorText.setText("ERROR: Not enough troops to attack from this territory");
                return;
            }

            // Store and highlight the attacking territory
            firstTerritoryClicked = territory;
            firstTerritoryClicked.setIsHighlighted(true);

        } else {

            // Clicking the same territory again cancels the selection
            if (firstTerritoryClicked == territory) {
                firstTerritoryClicked.setIsHighlighted(false);
                firstTerritoryClicked = null;
                return;
            }

            // The target territory must not be owned by the current player
            if (gameLogic.isTerritoryPlayerOwned(territory)) {
                errorText.setText("ERROR: Select a valid territory you do not own to attack");
                return;
            }

            // Attempt the attack through game logic validation
            ValidationResult result = gameLogic.attack(firstTerritoryClicked, territory);
            if (!result.isValid()) {
                errorText.setText(result.message());
                return;
            }
            successText.setText(result.message());

            // Clear the selected territory after the attack completes
            firstTerritoryClicked.setIsHighlighted(false);
            firstTerritoryClicked = null;

            // Show the win page if the attack ended the game
            if (gameLogic.isGameOver()) {
                showWinPage();
            }
        }
    }

    /**
     * Handles territory selection during the reinforcement phase.
     *
     * @param territory the territory clicked by the player
     */
    private void reinforcementPhaseTerritoryClicked(Territory territory) {
        // Prevent reinforcing if there are no troops left to place
        if (gameLogic.getCurrentPlayer().getTroopsToPlace() <= 0) {
            errorText.setText("No troops left to place.");
            return;
        }

        // Only owned territories may be reinforced
        if (!gameLogic.isTerritoryPlayerOwned(territory)) {
            errorText.setText("Select an owned territory to reinforce");
            return;
        }

        // Highlight the selected territory before prompting for troop amount
        firstTerritoryClicked = territory;
        firstTerritoryClicked.setIsHighlighted(true);
        display.repaint();

        Integer troopsToPlace = getTroopAmountToPlaceOnTerritories(gameLogic.getCurrentPlayer().getTroopsToPlace());
        if (troopsToPlace == null) {
            // Cancel selection if the player closes the popup
            firstTerritoryClicked.setIsHighlighted(false);
            firstTerritoryClicked = null;
            return;
        }

        // Attempt to reinforce using the selected troop amount
        ValidationResult result = gameLogic.reinforce(gameLogic.getCurrentPlayer(), territory, troopsToPlace);
        if (!result.isValid()) {
            firstTerritoryClicked.setIsHighlighted(false);
            errorText.setText(result.message());
            firstTerritoryClicked = null;
            return;
        }

        // Clear highlight and show success after reinforcement
        firstTerritoryClicked.setIsHighlighted(false);
        successText.setText(result.message());
        firstTerritoryClicked = null;
    }

    /**
     * Handles territory selection during the fortify phase.
     *
     * @param territory the territory clicked by the player
     */
    private void fortifyPhaseTerritoryClicked(Territory territory) {
        // A player may only fortify once per turn
        if (fortifyUsedThisTurn) {
            errorText.setText("Fortify already used this turn. Press Continue.");
            return;
        }

        if (firstTerritoryClicked == null) {
            // The first fortify selection must be an owned territory
            if (!gameLogic.isTerritoryPlayerOwned(territory)) {
                errorText.setText("Select a territory YOU OWN to move troops from");
                return;
            }

            // The source territory must have at least one movable troop
            if (territory.getTroopAmount() <= 1) {
                errorText.setText("Not enough troops to move");
                return;
            }

            // Store and highlight the source territory
            firstTerritoryClicked = territory;
            firstTerritoryClicked.setIsHighlighted(true);
            return;
        }

        // Clicking the same territory again cancels the selection
        if (territory == firstTerritoryClicked) {
            firstTerritoryClicked.setIsHighlighted(false);
            firstTerritoryClicked = null;
            return;
        }

        // Prompt the player to choose how many troops to move, leaving one behind
        Integer troopsToMove = getTroopAmountToMoveFromTerritory(firstTerritoryClicked.getTroopAmount() - 1);

        if (troopsToMove == null) {
            return;
        }

        // Attempt to move troops between the selected territories
        ValidationResult result = gameLogic.fortify(firstTerritoryClicked, territory, troopsToMove);

        if (!result.isValid()) {
            errorText.setText(result.message());
            return;
        }

        // Mark fortify as used and enable the continue button once successful
        successText.setText(result.message());
        instructionText.setText("Fortify Stage done, Press Continue Button");
        firstTerritoryClicked.setIsHighlighted(false);
        firstTerritoryClicked = null;
        fortifyUsedThisTurn = true;
        continueButton.setEnabled(true);

    }

    /**
     * Displays a popup allowing the player to choose how many troops to place.
     *
     * @param maxTroops the maximum number of troops that may be placed
     * @return the number of troops selected, or null if canceled
     */
    private Integer getTroopAmountToPlaceOnTerritories(int maxTroops) {
        Integer[] options = new Integer[maxTroops];

        // Fill the options array with values from 1 up to maxTroops
        for (int i = 0; i < maxTroops; i++) {
            options[i] = i + 1;
        }

        Object selection = JOptionPane.showInputDialog(
                display,
                "Select number of troops to place:",
                "Troop Placement",
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
        );

        // Return null if the user closes or cancels the dialog
        if (selection == null) {
            return null;
        }

        return (Integer) selection;
    }

    /**
     * Displays a popup allowing the player to choose how many troops to move.
     *
     * @param maxTroops the maximum number of troops that may be moved
     * @return the number of troops selected, or null if canceled
     */
    private Integer getTroopAmountToMoveFromTerritory(int maxTroops) {
        Integer[] options = new Integer[maxTroops];

        // Fill the options array with values from 1 up to maxTroops
        for (int i = 0; i < maxTroops; i++) {
            options[i] = i + 1;
        }

        Object selection = JOptionPane.showInputDialog(
                display,
                "Select number of troops to move:",
                "Troop Movement",
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
        );

        // Return null if the user closes or cancels the dialog
        if (selection == null) {
            return null;
        }

        return (Integer) selection;
    }

    /**
     * Ends the current phase or turn and advances the game.
     */
    private void endTurn() {
        // If the game is already over, immediately show the win page
        if (gameLogic.isGameOver()) {
            showWinPage();
            return;
        }

        // Clear any existing territory highlight before changing phase
        if (firstTerritoryClicked != null) {
            firstTerritoryClicked.setIsHighlighted(false);
            firstTerritoryClicked = null;
        }

        fortifyUsedThisTurn = false;
        errorText.setText("");
        successText.setText("");
        gameLogic.changePhase();

        // Recalculate reinforcement at the start of a new reinforcement phase
        if (gameLogic.getCurrentPhase() == TurnPhase.REINFORCEMENT) {
            gameLogic.calculateReinforcement();
        }

        updateText();
        display.repaint();
    }

    /**
     * Updates all on-screen labels and button states based on the current phase.
     */
    private void updateText() {
        Player currentPlayer = gameLogic.getCurrentPlayer();
        if (!showingRegions) {
            errorText.setVisible(true);
            successText.setVisible(true);
            if (gameLogic.getCurrentPhase() == TurnPhase.REINFORCEMENT) {
                gameStatusLabel.setText("REINFORCEMENT");
                generalInfoLabel.setText(
                        "Player: " + currentPlayer.getName() + " | Color: " + currentPlayer.getColorName()
                                + " | Troops left: " + currentPlayer.getTroopsToPlace()
                );

                instructionText.setText("Select a territory you own to reinforce.");

                // Continue is only enabled once all reinforcement troops are placed
                continueButton.setEnabled(currentPlayer.getTroopsToPlace() <= 0);

            } else if (gameLogic.getCurrentPhase() == TurnPhase.ATTACK) {
                gameStatusLabel.setText("ATTACK");
                generalInfoLabel.setText("Current Player: " + currentPlayer.getName() + " | Color: " + currentPlayer.getColorName());

                // Show different instructions depending on whether an attacking territory is already selected
                if (firstTerritoryClicked == null) {
                    instructionText.setText("Select a territory you own to attack from.");
                } else {
                    instructionText.setText("Select a territory to attack.");
                }

                continueButton.setEnabled(true);

            } else {
                gameStatusLabel.setText("FORTIFY");
                generalInfoLabel.setText("Current Player: " + currentPlayer.getName() + " | Color: " + currentPlayer.getColorName());

                // Show fortify instructions based on the current step of the phase
                if (fortifyUsedThisTurn) {
                    instructionText.setText("Fortify complete. Press Continue to end your turn.");
                } else if (firstTerritoryClicked == null) {
                    instructionText.setText("Select a territory you own to move troops from.");
                } else {
                    instructionText.setText("Select a territory to move troops to.");
                }

                continueButton.setEnabled(true);
            }
        } else {
            errorText.setVisible(false);
            successText.setVisible(false);
            World world = gameLogic.getWorld();
            if (world instanceof  TotalDominationWorld) {
                int territoriesOwned = world.getTerritoryCountOwnedByPlayer(currentPlayer);
                int totalTerritories = world.getTerritoryCount();

                gameStatusLabel.setText("REGION VIEW");
                generalInfoLabel.setText("Player: " + currentPlayer.getName() + " | Color: " + currentPlayer.getColorName()
                        + " | Total Territories Owned: " + territoriesOwned + " / " + totalTerritories);

                StringBuilder regionStats = new StringBuilder();
                regionStats.append("Territories Owned in each region: ");
                for (Region region : world.getRegions()) {
                    int playerTerritoriesInRegion = 0;
                    int totalTerritoriesInRegion = region.getTerritories().size();
                    for (Territory territory : region.getTerritories()) {
                        if (currentPlayer.equals(territory.getPlayer())) {
                            playerTerritoriesInRegion++;
                        }
                    }
                    regionStats.append(region.getColorName())
                            .append(": ")
                            .append(playerTerritoriesInRegion)
                            .append("/")
                            .append(totalTerritoriesInRegion)
                            .append("  ");
                }

                instructionText.setText(regionStats.toString());
            } else {
                int capitalsOwned = 0;
                int totalCapitals = 0;
                for (Region region : world.getRegions()) {
                    Territory capital = region.getCapitalTerritory();
                    if (capital != null) {
                        totalCapitals++;
                        if (currentPlayer.equals(capital.getPlayer())) {
                            capitalsOwned++;
                        }
                    }
                }
                instructionText.setText("Total Capitals Owned: " + capitalsOwned + " / " + totalCapitals);
            }
        }

        gameInfoPanel.repaint();
    }

    /**
     * Displays the startup popup describing the selected game mode and rules.
     */
    private void displayStartPopup() {
        String worldType;

        // Determine which world mode is currently being played
        if (gameLogic.getWorld() instanceof CapitalDominationWorld) {
            worldType = "Capital Domination";
        } else {
            worldType = "Total Domination";
        }

        JOptionPane.showMessageDialog(display, "Setup Completed. Game has now started!\n" + "Game Mode Selected: " + worldType +
                "\n" + "Each player will take turns Reinforcing Their Territories, Attacking Territories, Then Fortifying Territories.\n" +
                "The game Does not end until a player has reached the objective of " + worldType +
                "\n" + "Refer to bottom of the screen to see what players turn it is, as well as directions on what to do next", "Battle Nations", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Returns the player to the main menu and resets the game.
     */
    public void returnToMainMenu() {
        display.getContentPane().removeAll();
        startController.reset(); // resets game
    }

    /**
     * Displays the win page for the winning player.
     */
    private void showWinPage() {
        Player winner = gameLogic.getWinner();
        if (winner == null) {
            return;
        }

        String mode;

        // Determine which game mode was won
        if (gameLogic.getWorld() instanceof CapitalDominationWorld) {
            mode = "Capital Domination";
        } else {
            mode = "Total Domination";
        }

        display.getContentPane().removeAll();

        WinPage winPage = new WinPage(this, winner, mode);
        display.add(winPage.getPanel());

        display.revalidate();
        display.repaint();
    }

    private void showTerrainInfo() {
        String info = """
            TERRAIN TYPES & BONUSES
            ________________________
            
            Plain
              - Attack Bonus:   0%
              - Defense Bonus:  0%
              - Troop Bonus:    +0
            
            Desert
              - Attack Bonus:   +9%
              - Defense Bonus:  0%
              - Troop Bonus:    +0
            
            Mountain
              - Attack Bonus:   0%
              - Defense Bonus:  +10%
              - Troop Bonus:    +0
            
            City
              - Attack Bonus:   0%
              - Defense Bonus:  0%
              - Troop Bonus:    +1
            
            Water
              - Not ownable or attackable
            
            Water Route
              - Connects non-adjacent territories
              - Not ownable or attackable
            
            Capital (Star on map)
              - No combat bonuses
              - Must be captured to win in Capital Domination
            """;
        JOptionPane.showMessageDialog(display, info, "Terrain Info", JOptionPane.INFORMATION_MESSAGE);
    }
}