/**
 * Represents a player in Battle Nations.
 *
 * <p>A player has a name, a color, and a number of troops they are allowed
 * to place each round. A player may also receive attack, defense, and troop
 * bonuses depending on game mechanics.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file, All comments were reviewed by author.
 *    No code was generated by ChatGPT.</li>
 * </ul>
 *
 * @author J.D. Reighard
 * @version 1.0
 * @since 2026-02-26
 *
 */
package player;

import java.awt.Color;

public class Player {
    /** The name of the player. */
    private String name;
    /** The color used to represent the player's territories. */
    private Color color;
    /** The number of troops the player is allowed to place. */
    private int troopsToPlace;
    /** The player's attack bonus multiplier. (applied if whole region is conquered) */
    private double attackBonusMultiplier;
    /** The player's defense bonus multiplier. */
    private double defenseBonusMultiplier;
    /** The player's additional troop bonus. */
    private int troopBonus;

    /**
     * Constructor for player
     * @param name the name of the player
     * @param color the color used to represent the player's territories
     */
    public Player(String name, Color color) {
        this.name = name;
        this.color = color;
    }

    /** @return the player's attack bonus multiplier */
    public double getAttackBonusMultiplier() {
        return attackBonusMultiplier;
    }

    /** @return the player's defense bonus multiplier */
    public double getDefenseBonusMultiplier() {
        return defenseBonusMultiplier;
    }

    /** @return the player's troop bonus */
    public int getTroopBonus() {
        return troopBonus;
    }

    /** @return the number of troops the player can place */
    public int getTroopsToPlace() {
        return troopsToPlace;
    }

    /** @return the player's name */
    public String getName() {
        return name;
    }


    /** @return the player's color */
    public Color getColor() {
        return color;
    }

    /** Sets the number of troops the player can place.
     * @param troopsToPlace the number of troops available to place
     */
    public void setTroopsToPlace(int troopsToPlace) {
        this.troopsToPlace = troopsToPlace;
    }

    /** Sets the player's attack bonus multiplier.
     * @param attackBonusMultiplier the attack bonus multiplier
     */
    public void setAttackBonusMultiplier(double attackBonusMultiplier) {
        this.attackBonusMultiplier = attackBonusMultiplier;
    }

    /** Sets the player's defense bonus multiplier.
     * @param defenseBonusMultiplier the defense bonus multiplier
     */
    public void setDefenseBonusMultiplier(double defenseBonusMultiplier) {
        this.defenseBonusMultiplier = defenseBonusMultiplier;
    }

    /** Sets the player's troop bonus.
     * @param troopBonus the troop bonus
     */
    public void setTroopBonus(int troopBonus) {
        this.troopBonus = troopBonus;
    }
}

