/**
 * Represents a player in Battle Nations.
 *
 * <p>A player has a name, a color, and a number of troops they are allowed
 * to place each round. A player may also receive attack, defense, and troop
 * bonuses depending on game mechanics.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file, All comments were reviewed by author.
 *    No code was generated by ChatGPT.</li>
 * </ul>
 *
 *
 */
package player;

import java.awt.Color;

public class Player {
    /**
     * The name of the player.
     */
    private String name;

    /**
     * The color used to represent the player's territories.
     */
    private Color color;

    /**
     * The number of troops the player is allowed to place.
     */
    private int troopsToPlace;


    /**
     * Constructs a new Player with the specified name and color.
     *
     * <p>The player is initialized without any bonuses or troops assigned.
     * These values are expected to be set during gameplay.</p>
     *
     * @param name  the name used to identify the player
     * @param color the color used to represent the player's territories
     */
    public Player(String name, Color color) {
        this.name = name;
        this.color = color;
    }

    /**
     * Returns the number of troops the player is allowed to place.
     *
     * <p>This value represents the available reinforcements for the current turn.</p>
     *
     * @return the number of troops available to place
     */
    public int getTroopsToPlace() {
        return troopsToPlace;
    }

    /**
     * Returns the name of this player.
     *
     * @return the player's name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the color associated with this player.
     *
     * @return the player's color
     */
    public Color getColor() {
        return color;
    }

    /**
     * Updates the number of troops the player can place.
     *
     * <p>This value determines how many reinforcements are available
     * during the current turn.</p>
     *
     * @param troopsToPlace the number of troops available to place
     */
    public void setTroopsToPlace(int troopsToPlace) {
        this.troopsToPlace = troopsToPlace;
    }
}

