package player;

import java.awt.*;

/**
 * Represents a player in Battle Nations.
 *
 * <p>A player has a name, a color, and a number of troops they are allowed
 * to place each round.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file, All comments were reviewed by author.
 *    No code was generated by ChatGPT.</li>
 * </ul>
 *
 *
 */

public class Player {
    /**
     * The name of the player.
     */
    private final String name;

    /**
     * The color used to represent the player's territories.
     */
    private final Color color;

    /**
     * The name of the color to display as text
     */
    private String colorName;

    /**
     * The number of troops the player is allowed to place.
     */
    private int troopsToPlace;


    /**
     * Constructs a new Player with the specified name and color.
     *
     * <p>The player is initialized without any bonuses or troops assigned.
     * These values are expected to be set during gameplay.</p>
     *
     * @param name  the name used to identify the player
     * @param color the color used to represent the player's territories
     */
    public Player(String name, Color color, String colorName) {
        this(name, color);
        this.colorName = colorName;
    }

    public Player(String name, Color color) {
        this.name = name;
        this.color = color;
    }

    /**
     * Returns the number of troops the player is allowed to place.
     *
     * <p>This value represents the available reinforcements for the current turn.</p>
     *
     * @return the number of troops available to place
     */
    public int getTroopsToPlace() {
        return troopsToPlace;
    }

    /**
     * Returns the name of this player.
     *
     * @return the player's name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the color associated with this player.
     *
     * @return the player's color
     */
    public Color getColor() {
        return color;
    }

    public String getColorName() {
        return colorName;
    }

    /**
     * Sets string value of the color name of the players color
     *
     * @param colorName the string name of the player's color
     */
    public void setColorName(String colorName) {
        this.colorName = colorName;
    }

    /**
     * Updates the number of troops the player can place.
     *
     * <p>This value determines how many reinforcements are available
     * during the current turn.</p>
     *
     * @param troopsToPlace the number of troops available to place
     */
    public void setTroopsToPlace(int troopsToPlace) {
        this.troopsToPlace = troopsToPlace;
    }
}

