package soundMaker;

import javax.sound.sampled.*;
import java.io.File;
import java.io.IOException;

/**
 * Handles button sound effects for the Battle Nations application.
 *
 * <p>
 * This class loads a sound file and plays short audio clips when triggered,
 * typically in response to button interactions. It also tracks whether the
 * audio system is functioning and whether sound effects are enabled.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class ButtonSound {

    /** The audio clip used for button sound effects. */
    private Clip buttonSound;

    /** Determines whether the audio system is working correctly. */
    private boolean soundWorking = true;

    /** Stores the current volume level on a scale from 0 to 10. */
    private float volume;

    /**
     * Constructs a ButtonSound object and attempts to load the specified sound file.
     *
     * <p>
     * If the file cannot be found or loaded, sound playback will be disabled
     * and the system will be marked as not working.
     * </p>
     *
     * @param fileName the file path of the sound file to be loaded
     */
    public ButtonSound(String fileName) {
        // Gets the file type of the file that's trying to be opened.
        String fileExtension = fileName.substring(fileName.lastIndexOf("."));

        // Opens the sound file.
        File soundFile = new File(fileName);

        // Checks to see if the file successfully opened, if it didn't, it stops trying to load the sound object.
        if (!soundFile.exists()) {
            System.err.println("Sound file not found: " + fileName);
            soundWorking = false;
            return;
        }

        // Loads the audio file and give it to a clip. If an error occurs creates an error message based on what happened.
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(soundFile);
            buttonSound = AudioSystem.getClip();
            buttonSound.open(audio);
        } catch (UnsupportedAudioFileException e) {
            System.err.println("Unsupported audio type: " + fileExtension);
            soundWorking = false;
        } catch (IOException e) {
            System.err.println("Error reading sound file: " + fileName);
            soundWorking = false;
        } catch (LineUnavailableException e) {
            System.err.println("Audio System unavailable");
            soundWorking = false;
        }

        volume = 10;
    }

    /**
     * Checks whether the sound system is working correctly.
     *
     * @return true if the sound system is working, false otherwise
     */
    public boolean isSoundWorking() {
        return soundWorking;
    }

    /**
     * Plays the button sound effect starting from a specified frame position.
     *
     * <p>
     * The sound will only play if the audio system is working and sound effects
     * are enabled. The clip is stopped before restarting to ensure consistent playback.
     * </p>
     *
     * @param frameStart the frame position within the audio clip to begin playback
     */
    public void playSound(int frameStart) {
        if (soundWorking) {
            buttonSound.stop();
            buttonSound.setFramePosition(frameStart);
            buttonSound.start();
        }
    }

    /**
     * Retrieves the current volume level.
     *
     * @return the volume level on a scale from 0 (muted) to 10 (maximum)
     */
    public float getVolume() {
        return volume;
    }

    /**
     * Sets the volume of the button sound.
     *
     * <p>
     * The provided value is expected to be between 0 and 10 and is mapped
     * to the audio system's internal decibel range using a linear scale.
     * </p>
     *
     * <p>
     * A value of 0 will mute the audio by setting it to the minimum gain.
     * </p>
     *
     * @param volume the desired volume level (0–10)
     */
    public void setVolume(float volume) {
        // The controller which is in charge of increasing or decreasing the decibels of an audio clip.
        FloatControl volumeControl = (FloatControl) buttonSound.getControl(FloatControl.Type.MASTER_GAIN);
        this.volume = volume;

        // If volume is zero, set to the minimum sound level (muted).
        if (volume == 0) {
            volumeControl.setValue(volumeControl.getMinimum());
        }

        float min = volumeControl.getMinimum();
        float max = volumeControl.getMaximum();

        // Linearly maps 0-10 range to the system's decibel range.
        volumeControl.setValue((min + (volume * (max - min) / 10)));
    }


}
