package soundMaker;

import javax.sound.sampled.*;
import java.io.File;
import java.io.IOException;

/**
 * Handles background music playback for the Battle Nations application.
 *
 * <p>
 * This class loads an audio file and manages looping playback for background music.
 * It also tracks whether the audio system is functioning and whether music is enabled.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class Music {

    /** The audio clip used for playing background music. */
    private Clip music;

    /** Determines whether the audio system is working correctly. */
    private boolean soundWorking = true;

    /** Stores the current volume level on a scale from 0 to 10. */
    private float volume;

    /**
     * Constructs a Music object and attempts to load the specified audio file.
     *
     * <p>
     * If the file cannot be found or loaded, music playback will be disabled
     * and the system will be marked as not working.
     * </p>
     *
     * @param fileName the file path of the audio file to be loaded
     */
    public Music(String fileName) {
        // Gets the file type of the file that's trying to be opened.
        String fileExtension = fileName.substring(fileName.lastIndexOf("."));

        // Opens the sound file.
        File soundFile = new File(fileName);

        // Checks to see if the file successfully opened, if it didn't, it stops trying to create the sound object.
        if (!soundFile.exists()) {
            System.err.println("Sound file not found: " + fileName);
            soundWorking = false;
            return;
        }

        // Loads the audio file and give it to a clip. If an error occurs creates an error message based on what happened.
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(soundFile);
            music = AudioSystem.getClip();
            music.open(audio);
        } catch (UnsupportedAudioFileException e) {
            System.err.println("Unsupported audio type: " + fileExtension);
            soundWorking = false;
        } catch (IOException e) {
            System.err.println("Error reading sound file: " + fileName);
            soundWorking = false;
        } catch (LineUnavailableException e) {
            System.err.println("Audio System unavailable");
            soundWorking = false;
        }

        volume = 10;
    }

    /**
     * Checks whether the music system is working correctly.
     *
     * @return true if the music system is working, false otherwise
     */
    public boolean isMusicWorking() {
        return soundWorking;
    }

    /**
     * Starts playing the background music in a loop.
     *
     * <p>
     * Music will only play if the audio system is working and music is enabled.
     * </p>
     */
    public void startMusic() {
        if (soundWorking) {
            music.loop(Clip.LOOP_CONTINUOUSLY);
        }
    }

    /**
     * Retrieves the current volume level.
     *
     * @return the volume level on a scale from 0 (muted) to 10 (maximum)
     */
    public float getVolume() {
        return volume;
    }

    /**
     * Sets the volume of the background music.
     *
     * <p>
     * The provided value is expected to be between 0 and 10 and is mapped
     * to the audio system's internal decibel range using a linear scale.
     * </p>
     *
     * <p>
     * A value of 0 will mute the audio by setting it to the minimum gain.
     * </p>
     *
     * @param volume the desired volume level (0–10)
     */
    public void setVolume(float volume) {
        // The controller which is in charge of increasing or decreasing the decibels of an audio clip.
        FloatControl volumeControl = (FloatControl) music.getControl(FloatControl.Type.MASTER_GAIN);
        this.volume = volume;

        // If volume is zero, set to the minimum sound level (muted).
        if (volume == 0) {
            volumeControl.setValue(volumeControl.getMinimum());
        }

        float min = volumeControl.getMinimum();
        float max = volumeControl.getMaximum();

        // Linearly maps 0-10 range to the system's decibel range.
        volumeControl.setValue((min + (volume * (max - min) / 10)));
    }
}

