package terrain;

/**
 * Represents city terrain in Battle Nations.
 *
 * <p>City terrain grants additional troops when controlled, representing
 * strategic populated areas that players are encouraged to fight over.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 *
 */
public class CityTerrain extends Terrain {

    /** Attack bonus percentage provided by city terrain. */
    private static final double ATTACK_BONUS_PERCENTAGE = 0;

    /** Defense bonus percentage provided by city terrain. */
    private static final double DEFENSE_BONUS_PERCENTAGE = 0;

    /** Additional troops granted by city terrain. */
    private static final int TROOP_BONUS = 1;

    /** Image file used to represent city terrain on the map. */
    private static final String ICON_FILENAME = "src/gameImages/CityTerrain.png";

    /**
     * Constructs a CityTerrain object with predefined terrain bonuses.
     */
    public CityTerrain() {
        super(ATTACK_BONUS_PERCENTAGE, DEFENSE_BONUS_PERCENTAGE, ICON_FILENAME, TROOP_BONUS);
    }
}
