package terrain;

/**
 * Represents mountain terrain in Battle Nations.
 *
 * <p>Mountain terrain provides a defensive bonus but does not grant
 * an attack bonus or additional troops. This terrain type is intended
 * to represent difficult terrain that favors defensive play.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class MountainTerrain extends Terrain {

    /** Attack bonus percentage provided by mountain terrain. */
    private static final double ATTACK_BONUS_PERCENTAGE = 0;

    /** Defense bonus percentage provided by mountain terrain. */
    private static final double DEFENSE_BONUS_PERCENTAGE = .1;

    /** Additional troops granted by mountain terrain. */
    private static final int TROOP_BONUS = 0;

    /** Image file used to represent mountain terrain on the map. */
    private static final String ICON_FILENAME = "src/gameImages/MountainTerrain.png";

    /**
     * Constructs a MountainTerrain object with predefined terrain bonuses.
     */
    public MountainTerrain() {
        super(ATTACK_BONUS_PERCENTAGE, DEFENSE_BONUS_PERCENTAGE, ICON_FILENAME, TROOP_BONUS);
    }
}
