package terrain;

/**
 * Represents plain terrain in Battle Nations.
 *
 * <p>Plain terrain provides no attack, defense, or troop bonuses.
 * It represents neutral ground with no strategic advantages.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class PlainTerrain extends Terrain {

    /**
     * Attack bonus percentage provided by plain terrain.
     */
    private static final double ATTACK_BONUS_PERCENTAGE = 0;
    /**
     * Defense bonus percentage provided by plain terrain.
     */
    private static final double DEFENSE_BONUS_PERCENTAGE = 0;
    /**
     * Additional troops granted by plain terrain.
     */
    private static final int TROOP_BONUS = 0;
    /**
     * Image file used to represent plain terrain on the map.
     */
    private static final String ICON_FILENAME = "temp";

    /**
     * Constructs a PlainTerrain object with predefined terrain bonuses.
     */
    public PlainTerrain() {
        super(ATTACK_BONUS_PERCENTAGE, DEFENSE_BONUS_PERCENTAGE, ICON_FILENAME, TROOP_BONUS);
    }
}
