package map;

/**
 * Defines the available terrain types used in Battle Nations.
 *
 * <p>The enum is used as a factory to create concrete {@link Terrain}
 * objects. This simplifies terrain creation and allows the terrain
 * system to scale easily as new terrain types are added.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>Oracle Java Documentation
 *   https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html</li>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file, All comments were reviewed by author.
 *     No code was generated by ChatGPT.</li>
 * </ul>
 *
 * <p>I needed my enum constants to be associated with their respective Terrain objects.
 * I knew parameters could be passed into an enum type, but referenced the
 * 'public enum Planet' example in the Oracle documentation to see how to
 * structure the constructor and variables. My TerrainType design was inspired
 * by the 'public enum Planet' example.</p>
 *
 * @author J.D. Reighard
 * @version 1.0
 * @since 2026-03-04
 */
public enum TerrainType {
    /**
     * Represents a city terrain type.
     */
    CITY(new CityTerrain()),
    /**
     * Represents a desert terrain type.
     */
    DESERT(new DesertTerrain()),
    /**
     * Represents a mountain terrain type.
     */
    MOUNTAIN(new MountainTerrain()),
    /**
     * Represents a water terrain type.
     */
    WATER(new WaterTerrain()),

    PLAIN(new PlainTerrain()),

    WATERROUTE(new WaterRouteTerrain());
    /** The terrain instance associated with this terrain type. */
    private final Terrain terrain;

    TerrainType(Terrain terrain) {
        this.terrain = terrain;
    }
    /**
     * Returns the terrain associated with this terrain type.
     * @return the terrain instance represented by this enum constant
     */
    public Terrain getTerrain() {
        return this.terrain;
    }

}


