package terrain;

/**
 * Provides basic tests for verifying TerrainType functionality.
 *
 * <p>This class tests whether each TerrainType enum constant correctly
 * returns its associated Terrain instance using the {@code getTerrain()}
 * method.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class TestTerrainType {

    /**
     * Tests whether each TerrainType enum constant returns the correct
     * concrete Terrain implementation.
     *
     * <p>This method verifies that calling {@code getTerrain()} on each
     * TerrainType returns an object of the expected class.</p>
     *
     * @return {@code true} if all terrain types return the correct class;
     * {@code false} otherwise
     */
    private static boolean testCreateTerrainType() {
        System.out.print("testing enumerators getTerrain() method: ");

        boolean passed = true;

        Terrain city = TerrainType.CITY.getTerrain();
        Terrain mountain = TerrainType.MOUNTAIN.getTerrain();
        Terrain desert = TerrainType.DESERT.getTerrain();
        Terrain water = TerrainType.WATER.getTerrain();
        Terrain waterRoute = TerrainType.WATERROUTE.getTerrain();
        Terrain plain = TerrainType.PLAIN.getTerrain();

        if (!city.getClass().equals(CityTerrain.class)) {
            passed = false;
            System.err.println("Error In City TerrainType");
        }

        if (!mountain.getClass().equals(MountainTerrain.class)) {
            passed = false;
            System.err.println("Error in Mountain TerrainType");

        }

        if (!desert.getClass().equals(DesertTerrain.class)) {
            passed = false;
            System.err.println("Error in Desert TerrainType");
        }

        if (!water.getClass().equals(WaterTerrain.class)) {
            passed = false;
            System.err.println("Error in Water TerrainType");
        }

        if (!waterRoute.getClass().equals(WaterRouteTerrain.class)) {
            passed = false;
            System.err.println("Error in WaterRoute TerrainType");
        }

        if (!plain.getClass().equals(PlainTerrain.class)) {
            passed = false;
            System.err.println("Error in Plain TerrainType");
        }

        if (passed) {
            System.out.println("Passed");
        } else {
            System.out.println("Failed");
        }
        return passed;
    }

    /**
     * Runs all TerrainType test methods and prints an overall result.
     *
     * @param args command-line arguments not used by this program
     */
    public static void main(String[] args) {
        boolean passed = true;
        System.out.println("Testing Methods");
        if (!testCreateTerrainType()) passed = false;
        if (passed) {
            System.out.println("All Tests Passed");
        } else {
            System.err.println("At least one Test Failed");
        }
    }
}
