package terrain;

/**
 * Represents a water route terrain in Battle Nations.
 *
 * <p>Water route terrain provides no attack, defense, or troop bonuses.
 * It is intended to represent navigable paths over water that allows
 * movement between territories.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class WaterRouteTerrain extends Terrain {

    /** Attack bonus percentage provided by water route terrain. */
    private static final double ATTACK_BONUS_PERCENTAGE = 0;

    /** Defense bonus percentage provided by water route terrain. */
    private static final double DEFENSE_BONUS_PERCENTAGE = 0;

    /** Additional troops granted by water route terrain. */
    private static final int TROOP_BONUS = 0;

    /** Image file used to represent water route terrain on the map. */
    private static final String ICON_FILENAME = "src/gameImages/WaterRouteTerrain.png";

    /**
     * Constructs a WaterRouteTerrain object with predefined terrain values.
     *
     * <p>All bonuses are set to zero, making this a neutral movement-based terrain.</p>
     */
    public WaterRouteTerrain() {
        super(ATTACK_BONUS_PERCENTAGE, DEFENSE_BONUS_PERCENTAGE, ICON_FILENAME, TROOP_BONUS);
    }
}