package terrain;

/**
 * Represents water terrain in Battle Nations.
 *
 * <p>Water terrain provides no attack, defense, or troop bonuses.
 * It is intended to represent non-playable or non-ownable areas
 * on the map.</p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class WaterTerrain extends Terrain {

    /** Attack bonus percentage provided by water terrain. */
    private static final double ATTACK_BONUS_PERCENTAGE = 0;

    /** Defense bonus percentage provided by water terrain. */
    private static final double DEFENSE_BONUS_PERCENTAGE = 0;

    /** Additional troops granted by water terrain. */
    private static final int TROOP_BONUS = 0;

    /** Image file used to represent water terrain on the map. */
    private static final String ICON_FILENAME = "src/gameImages/WaterTerrain.png";

    /**
     * Constructs a WaterTerrain object with predefined terrain values.
     *
     * <p>All bonuses are set to zero, making this a non-beneficial terrain type.</p>
     */
    public WaterTerrain() {
        super(ATTACK_BONUS_PERCENTAGE, DEFENSE_BONUS_PERCENTAGE, ICON_FILENAME, TROOP_BONUS);
    }
}
