package setUpGUI;

import gameGUI.GameController;
import map.*;
import player.Player;
import startGUI.ImagePanel;
import startGUI.SetUpData;
import startGUI.StartController;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Serves as the main controller for the game setup phase.
 *
 * <p>
 * This class coordinates the setup process by managing transitions between
 * different setup phases, including territory selection and troop placement.
 * It also initializes and updates the map display, region view, and game
 * information panel shown to the user.
 * </p>
 *
 * <p>
 * User interactions such as mouse clicks are delegated to the current active
 * phase, allowing each phase to handle its own logic independently.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class SetUpController {

    /** The main JFrame used to display all setup components. */
    private final JFrame display;

    /** Stores configuration data selected during setup. */
    private final SetUpData gameSetUpData;

    /** Handles rendering and interaction with the map view. */
    private final MapDisplay mapDisplay;

    /** Panel used to display region-based view of the map. */
    private final RegionPanel regionPanel;

    /** Panel displaying game information such as player status and instructions. */
    private final ImagePanel gameInfoPanel;

    /** Label displaying the current player's status. */
    private final JLabel gameStatusLabel;

    /** Label displaying general game information. */
    private final JLabel generalInfoLabel;

    /** Label displaying instructions for the current phase. */
    private final JLabel instructionText;

    /** Label displaying error messages to the user. */
    private final JLabel errorText;

    /** Label displaying success messages to the user. */
    private final JLabel successText;

    /** 2D array representing all territories on the map. */
    private final Territory[][] territories;

    /** Tracks the current setup phase (e.g., Territory or Troop). */
    private String phase;

    /** List of players participating in the game. */
    private final List<Player> players;

    /** List of regions used to construct the game world. */
    private final List<Region> regions;

    /** Controller used for starting or restarting the game. */
    private final StartController startController;

    /** Handles logic for the territory selection phase. */
    private final TerritorySelectionPhase territorySelectionPhase;

    /** Handles logic for the troop placement phase. */
    private final TroopPlacementPhase troopPlacementPhase;


    /** Button used to switch to the map view during setup. */
    private final JButton showMapButton;

    /** Button used to switch to the region view during setup. */
    private final JButton showRegionsButton;

    /**
     * Constructs the SetUpController and initializes all setup components,
     * including the map display, region panel, and game information panel.
     *
     * <p>
     * This constructor also initializes the first setup phase (territory selection)
     * and prepares the UI for user interaction.
     * </p>
     *
     * @param display         the main JFrame used for rendering the setup interface
     * @param setUpData       the data object storing setup configuration
     * @param startController the controller responsible for navigation between GUI pages
     */
    public SetUpController(JFrame display, SetUpData setUpData, StartController startController) {
        //Populates all variable information.
        this.display = display;
        this.gameSetUpData = setUpData;
        this.startController = startController;
        phase = "Territory";
        mapDisplay = new MapDisplay(gameSetUpData, this);
        territories = mapDisplay.getTerritories();
        regions = mapDisplay.getRegions();
        regionPanel = new RegionPanel(territories, regions, this);
        players = gameSetUpData.getPlayers();

        // Gets the dimensions of the screen for reference.
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();

        // Creates the game information panel shown at the bottom of the screen.
        gameInfoPanel = new ImagePanel("src/gameImages/GameInfoBackground.jpg");
        gameInfoPanel.setLayout(null);
        gameInfoPanel.setBounds(0, (int) (screen.getHeight() * 0.8), screen.width, (int) (screen.height * 0.2));

        // Initializes all the Labels used.
        gameStatusLabel = new JLabel();
        generalInfoLabel = new JLabel();
        instructionText = new JLabel();
        errorText = new JLabel();
        successText = new JLabel();

        // Sets label positions.
        gameStatusLabel.setBounds(40, 15, 1000, 28);
        generalInfoLabel.setBounds(40, 50, 1200, 24);
        instructionText.setBounds(40, 80, 1200, 24);
        errorText.setBounds(40, 110, 1200, 24);
        successText.setBounds(40, 140, 1200, 24);

        // Sets label colors.
        gameStatusLabel.setForeground(Color.WHITE);
        generalInfoLabel.setForeground(Color.WHITE);
        instructionText.setForeground(Color.WHITE);
        errorText.setForeground(Color.RED);
        successText.setForeground(Color.GREEN);

        // Sets label fonts.
        gameStatusLabel.setFont(new Font("Arial", Font.BOLD, 22));
        generalInfoLabel.setFont(new Font("Arial", Font.PLAIN, 18));
        instructionText.setFont(new Font("Arial", Font.PLAIN, 18));
        errorText.setFont(new Font("Arial", Font.BOLD, 20));
        successText.setFont(new Font("Arial", Font.BOLD, 20));

        // Adds labels to the information panel.
        gameInfoPanel.add(gameStatusLabel);
        gameInfoPanel.add(generalInfoLabel);
        gameInfoPanel.add(instructionText);
        gameInfoPanel.add(errorText);
        gameInfoPanel.add(successText);

        // Button used to toggle map view.
        showMapButton = new JButton("Show Map");
        showMapButton.setBounds(gameInfoPanel.getWidth() - 200, 10, 200, 50);
        showMapButton.setVisible(false);

        // Button used to toggle region view.
        showRegionsButton = new JButton("Show Regions");
        showRegionsButton.setBounds(gameInfoPanel.getWidth() - 200, 10, 200, 50);

        // Switches from region view to map view.
        showMapButton.addActionListener(e -> {
            display.remove(regionPanel);
            showRegionsButton.setVisible(true);
            showMapButton.setVisible(false);
            displayMapDisplay();
            startController.makeSound();
        });

        // Switches from map view to region view.
        showRegionsButton.addActionListener(e -> {
            regionPanel.setBounds(0, 0, screen.width, (int) (screen.height * 0.8));
            mapDisplay.removeMapDisplay(display);
            display.add(regionPanel);
            showRegionsButton.setVisible(false);
            showMapButton.setVisible(true);
            startController.makeSound();
        });

        // Adds buttons to the info panel.
        gameInfoPanel.add(showRegionsButton);
        gameInfoPanel.add(showMapButton);

        // Adds the info panel to the main JFrame display.
        display.add(gameInfoPanel);

        // Updates display.
        displayMapDisplay();

        // Initializes the two phases.
        troopPlacementPhase = new TroopPlacementPhase(this, territories, players, gameSetUpData.isRandomTroopPlacement());
        territorySelectionPhase = new TerritorySelectionPhase(this, territories, players, gameSetUpData.isRandomTerritories());
        if (!gameSetUpData.isRandomTerritories()) {
            JOptionPane.showMessageDialog(display, "Welcome to the territory selection phase.\n" +
                    "You will take turns choosing territories you want to own until\n" +
                    "no territories are left unowned.\n" +
                    "You can refer to the bottom left of the screen to see\n" +
                    "which players turn it is and their color.", "Choose Territories", JOptionPane.INFORMATION_MESSAGE);
            startController.makeSound();
        }
        territorySelectionPhase.initializeGameInfoText();
    }

    /**
     * Returns the main JFrame used for rendering the setup interface.
     *
     * @return the display JFrame
     */
    public JFrame getDisplay() {
        return display;
    }

    /**
     * Adds the map display panel to the main frame.
     */
    public void displayMapDisplay() {
        mapDisplay.addMapDisplay(this.display);
    }

    /**
     * Handles mouse click events and delegates them to the current setup phase.
     *
     * @param point the location of the mouse click
     */
    public void dealWithClick(Point point) {
        if (phase.equals("Territory")) {
            startController.makeSound();
            territorySelectionPhase.dealWithClick(point);
        } else if (phase.equals("Troop")) {
            startController.makeSound();
            troopPlacementPhase.dealWithClick(point);

        }
    }

    /**
     * Initializes the troop placement phase.
     */
    public void placeTroopPhase() {
        troopPlacementPhase.start();
        setPhase("Troop");

        if (!gameSetUpData.isRandomTroopPlacement()) {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    JOptionPane.showMessageDialog(display, "Welcome to the troop placement phase.\n" +
                            "You will take turns placing three troops at a time on your territories until\n" +
                            "no players have any troops left to place.\n" +
                            "You can refer to the bottom left of the screen to see\n" +
                            "which players turn it is, their color, and how many troops\n" +
                            "they have to place.", "Place Troops", JOptionPane.INFORMATION_MESSAGE);
                    startController.makeSound();
                }
            });
        }
    }
    /**
     * Transitions from setup to the main game controller.
     *
     * <p>
     * Creates the appropriate world type based on the selected game mode
     * and initializes the {@link GameController}.
     * </p>
     */
    public void passToGameController() {
        World world;
        if (gameSetUpData.getGameMode().equals("totalDomination")) {
            world = new TotalDominationWorld(regions);
        } else {
            world = new CapitalDominationWorld((ArrayList<Region>) regions);
        }
        showRegionsButton.setVisible(false);
        showMapButton.setVisible(false);
        new GameController(world, players, display, mapDisplay.getMapDisplay(), gameInfoPanel, regionPanel, gameStatusLabel, generalInfoLabel, instructionText, errorText, successText, startController);
    }

    /**
     * Updates the game information panel based on the current phase.
     *
     * <p>
     * Displays the active player, their color, and relevant instructions
     * for the current phase of setup.
     * </p>
     */
    public void updateGameInfoText() {
        errorText.setText("");
        if (phase.equals("Territory")) {
            gameStatusLabel.setText("Player: " + territorySelectionPhase.getActivePlayer().getName() + " | Color: " + territorySelectionPhase.getActivePlayer().getColorName());
            instructionText.setText("Select a territory");
        } else if (phase.equals("Troop")) {
            gameStatusLabel.setText("Player: " + troopPlacementPhase.getActivePlayer().getName() + " | Color: " + troopPlacementPhase.getActivePlayer().getColorName());
            instructionText.setText("Troops left: " + troopPlacementPhase.getActivePlayer().getTroopsToPlace() + " | Place this turn: " + troopPlacementPhase.getTroopsToPlace());
        }

        gameInfoPanel.repaint();
    }

    /**
     * Returns the label used for displaying error messages.
     *
     * @return the error message label
     */
    public JLabel getErrorText() {
        return errorText;
    }

    /**
     * Returns the game information panel.
     *
     * @return the game info panel
     */
    public ImagePanel getGameInfoPanel() {
        return gameInfoPanel;
    }

    /**
     * Sets the current setup phase.
     *
     * @param phase the new phase to transition to
     */
    public void setPhase(String phase) {
        this.phase = phase;
    }

    /**
     * Resets the game back to the start.
     */
    public void reset() {
        mapDisplay.removeMapDisplay(display);
        display.remove(regionPanel);
        display.remove(gameInfoPanel);
        startController.reset();
    }

    /**
     * Closes the game screen without shutting down the program.
     */
    public void minimize() {
        startController.getDisplay().setState(Frame.ICONIFIED);
    }

}
