package setUpGUI;

import map.Territory;
import player.Player;

import java.awt.*;
import java.util.List;
import java.util.Random;

/**
 * Handles the troop placement phase of the game setup process.
 *
 * <p>
 * This class manages player turns, troop distribution, and placement rules.
 * Players take turns placing troops on territories they own until all troops
 * have been distributed. Placement can occur either manually through user
 * interaction or automatically through random assignment.
 * </p>
 *
 * <p>
 * User input is processed through mouse clicks, which are validated to ensure
 * that troops are only placed on valid territories owned by the active player.
 * </p>
 *
 * <p><b>Sources Used:</b></p>
 * <ul>
 *   <li>ChatGPT – Assisted with generating Javadoc comments for this file in conjunction with Max Montowski.
 *   All comments were reviewed by the author. No code was generated by ChatGPT.</li>
 * </ul>
 */
public class TroopPlacementPhase {

    /** Reference to the main setup controller. */
    private final SetUpController setUpController;

    /** 2D array representing all territories on the map. */
    private final Territory[][] territories;

    /** The player whose turn it is to place troops. */
    private Player activePlayer;

    /** List of all players participating in the game. */
    private final List<Player> players;

    /** Tracks the current player's index in the turn order. */
    private int playerTurn = 0;

    /** Number of troops the current player can place during this turn. */
    private int troopsToPlace = 3;

    /** Determines if troop placement is random. */
    private final boolean isRandom;

    /** Keeps track of it troop placement is allowed to process information yet. */
    private boolean started = false;

    /**
     * Constructs the troop placement phase and initializes troop distribution.
     *
     * <p>
     * Each player is assigned an equal number of troops to place. If random
     * placement is enabled, troops are distributed automatically. Otherwise,
     * the phase begins with manual placement.
     * </p>
     *
     * @param setUpController the main setup controller
     * @param territories     the map territories
     * @param players         the list of players
     * @param isRandom        determines whether troop placement is randomized
     */
    public TroopPlacementPhase(SetUpController setUpController, Territory[][] territories, List<Player> players, Boolean isRandom) {
        this.setUpController = setUpController;
        this.territories = territories;
        this.players = players;
        this.activePlayer = players.getFirst();
        this.isRandom = isRandom;
    }

    public void start() {
        // Distributes troops evenly among players.
        giveTroopsToPlace(60);
        started = true;
        if (isRandom) {
            randomlyPlaceTroops();
        } else {
            setUpController.setPhase("Troop");
            setUpController.updateGameInfoText();
        }
    }

    /**
     * Distributes a total number of troops evenly among all players.
     *
     * @param troopsToPlace total number of troops to distribute
     */
    public void giveTroopsToPlace(int troopsToPlace) {
        int troopsPerPlayer = troopsToPlace / players.size();
        for (Player player : players) {
            player.setTroopsToPlace(troopsPerPlayer);
        }
    }

    /**
     * Handles mouse click events and attempts to place a troop
     * on the clicked territory.
     *
     * @param point the location of the mouse click
     */
    public void dealWithClick(Point point) {
        if (started) {
            for (Territory[] row : territories) {
                for (Territory territory : row) {
                    if (territory != null && territory.contains(point)) {
                        placeTroop(territory);
                    }
                }
            }
        }
    }

    /**
     * Automatically distributes troops randomly across valid territories.
     *
     * <p>
     * Troops are placed only on territories owned by the active player.
     * The turn rotates between players until all troops have been placed.
     * </p>
     */
    public void randomlyPlaceTroops() {
        Random random = new Random();

        // Continues to place troops while there are troops to be place.
        while (playersHaveTroopsToPlace()) {

            // Generates a random location on the map and checks to see if it's owned by the active player.
            int row = random.nextInt(territories.length);
            int col = random.nextInt(territories[row].length);
            if (territories[row][col] != null && territories[row][col].getPlayer() == activePlayer) {

                // Adds a troop to the territory and removes one from the player.
                territories[row][col].setTroopAmount(territories[row][col].getTroopAmount() + 1);
                activePlayer.setTroopsToPlace(activePlayer.getTroopsToPlace() - 1);

                // Advances to the next player.
                playerTurn++;
                if (playerTurn >= players.size()) {
                    playerTurn = 0;
                }
                activePlayer = players.get(playerTurn);
            }
        }

        // Transitions to the main game once all troops are placed.
        setUpController.passToGameController();
    }

    /**
     * Attempts to place a troop on the specified territory.
     *
     * <p>
     * Placement is only allowed if:
     * <ul>
     *   <li>The territory is owned by the active player</li>
     *   <li>The terrain allows troop placement</li>
     *   <li>The player has troops remaining to place</li>
     * </ul>
     * </p>
     *
     * @param territory the territory where the troop is to be placed
     */
    public void placeTroop(Territory territory) {
        //Checks to see if the territories owner is the active player.
        if (territory.getPlayer() == activePlayer) {

            // Checks to make sure the player still has troops to place.
            if (activePlayer.getTroopsToPlace() > 0) {

                // Places troop on the territory.
                territory.setTroopAmount(territory.getTroopAmount() + 1);
                activePlayer.setTroopsToPlace(activePlayer.getTroopsToPlace() - 1);
                troopsToPlace--;
                setUpController.updateGameInfoText();

            }

            // If the player has no more troops to place, advances turn to next player.
            if (troopsToPlace <= 0) {
                playerTurn++;
                if (playerTurn >= players.size()) {
                    playerTurn = 0;
                }
                activePlayer = players.get(playerTurn);

                // Determines how many troops can be placed in the next turn.
                if (activePlayer.getTroopsToPlace() > 3) {
                    troopsToPlace = 3;
                } else {
                    troopsToPlace = activePlayer.getTroopsToPlace();

                }
                setUpController.updateGameInfoText();
            }
        } else {

            // Displays error if player selects a territory they do not own.
            setUpController.getErrorText().setText("Territory not owned by " + activePlayer.getName());
            setUpController.getGameInfoPanel().repaint();
        }

        // Ends setup if all troops have been placed.
        if (!playersHaveTroopsToPlace()) {
            setUpController.passToGameController();
        }
    }

    /**
     * Checks whether any player still has troops left to place.
     *
     * @return true if at least one player has troops remaining, false otherwise
     */
    public boolean playersHaveTroopsToPlace() {
        for (Player player : players) {
            if (player.getTroopsToPlace() > 0) {
                return true;
            }
        }
        return false;
    }

    /**
     * Returns the number of troops the active player can place this turn.
     *
     * @return troops remaining for the current turn
     */
    public int getTroopsToPlace() {
        return troopsToPlace;
    }

    /**
     * Returns the currently active player.
     *
     * @return the active player
     */
    public Player getActivePlayer() {
        return activePlayer;
    }

}
